// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"sea-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIVerificationRepo creates a new instance of MockIVerificationRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIVerificationRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIVerificationRepo {
	mock := &MockIVerificationRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIVerificationRepo is an autogenerated mock type for the IVerificationRepo type
type MockIVerificationRepo struct {
	mock.Mock
}

type MockIVerificationRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIVerificationRepo) EXPECT() *MockIVerificationRepo_Expecter {
	return &MockIVerificationRepo_Expecter{mock: &_m.Mock}
}

// Clean provides a mock function for the type MockIVerificationRepo
func (_mock *MockIVerificationRepo) Clean() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clean")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIVerificationRepo_Clean_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clean'
type MockIVerificationRepo_Clean_Call struct {
	*mock.Call
}

// Clean is a helper method to define mock.On call
func (_e *MockIVerificationRepo_Expecter) Clean() *MockIVerificationRepo_Clean_Call {
	return &MockIVerificationRepo_Clean_Call{Call: _e.mock.On("Clean")}
}

func (_c *MockIVerificationRepo_Clean_Call) Run(run func()) *MockIVerificationRepo_Clean_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIVerificationRepo_Clean_Call) Return(err error) *MockIVerificationRepo_Clean_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIVerificationRepo_Clean_Call) RunAndReturn(run func() error) *MockIVerificationRepo_Clean_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockIVerificationRepo
func (_mock *MockIVerificationRepo) Create(verification *models.VerificationCodeModel) error {
	ret := _mock.Called(verification)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.VerificationCodeModel) error); ok {
		r0 = returnFunc(verification)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIVerificationRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIVerificationRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - verification *models.VerificationCodeModel
func (_e *MockIVerificationRepo_Expecter) Create(verification interface{}) *MockIVerificationRepo_Create_Call {
	return &MockIVerificationRepo_Create_Call{Call: _e.mock.On("Create", verification)}
}

func (_c *MockIVerificationRepo_Create_Call) Run(run func(verification *models.VerificationCodeModel)) *MockIVerificationRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.VerificationCodeModel
		if args[0] != nil {
			arg0 = args[0].(*models.VerificationCodeModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIVerificationRepo_Create_Call) Return(err error) *MockIVerificationRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIVerificationRepo_Create_Call) RunAndReturn(run func(verification *models.VerificationCodeModel) error) *MockIVerificationRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockIVerificationRepo
func (_mock *MockIVerificationRepo) Delete(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIVerificationRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIVerificationRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int64
func (_e *MockIVerificationRepo_Expecter) Delete(id interface{}) *MockIVerificationRepo_Delete_Call {
	return &MockIVerificationRepo_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockIVerificationRepo_Delete_Call) Run(run func(id int64)) *MockIVerificationRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIVerificationRepo_Delete_Call) Return(err error) *MockIVerificationRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIVerificationRepo_Delete_Call) RunAndReturn(run func(id int64) error) *MockIVerificationRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCode provides a mock function for the type MockIVerificationRepo
func (_mock *MockIVerificationRepo) GetByCode(code string) (*models.VerificationCodeModel, error) {
	ret := _mock.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *models.VerificationCodeModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.VerificationCodeModel, error)); ok {
		return returnFunc(code)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.VerificationCodeModel); ok {
		r0 = returnFunc(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.VerificationCodeModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIVerificationRepo_GetByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCode'
type MockIVerificationRepo_GetByCode_Call struct {
	*mock.Call
}

// GetByCode is a helper method to define mock.On call
//   - code string
func (_e *MockIVerificationRepo_Expecter) GetByCode(code interface{}) *MockIVerificationRepo_GetByCode_Call {
	return &MockIVerificationRepo_GetByCode_Call{Call: _e.mock.On("GetByCode", code)}
}

func (_c *MockIVerificationRepo_GetByCode_Call) Run(run func(code string)) *MockIVerificationRepo_GetByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIVerificationRepo_GetByCode_Call) Return(verificationCodeModel *models.VerificationCodeModel, err error) *MockIVerificationRepo_GetByCode_Call {
	_c.Call.Return(verificationCodeModel, err)
	return _c
}

func (_c *MockIVerificationRepo_GetByCode_Call) RunAndReturn(run func(code string) (*models.VerificationCodeModel, error)) *MockIVerificationRepo_GetByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type MockIVerificationRepo
func (_mock *MockIVerificationRepo) GetByUserID(user_id int64) (*models.VerificationCodeModel, error) {
	ret := _mock.Called(user_id)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *models.VerificationCodeModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*models.VerificationCodeModel, error)); ok {
		return returnFunc(user_id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *models.VerificationCodeModel); ok {
		r0 = returnFunc(user_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.VerificationCodeModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(user_id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIVerificationRepo_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockIVerificationRepo_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - user_id int64
func (_e *MockIVerificationRepo_Expecter) GetByUserID(user_id interface{}) *MockIVerificationRepo_GetByUserID_Call {
	return &MockIVerificationRepo_GetByUserID_Call{Call: _e.mock.On("GetByUserID", user_id)}
}

func (_c *MockIVerificationRepo_GetByUserID_Call) Run(run func(user_id int64)) *MockIVerificationRepo_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIVerificationRepo_GetByUserID_Call) Return(verificationCodeModel *models.VerificationCodeModel, err error) *MockIVerificationRepo_GetByUserID_Call {
	_c.Call.Return(verificationCodeModel, err)
	return _c
}

func (_c *MockIVerificationRepo_GetByUserID_Call) RunAndReturn(run func(user_id int64) (*models.VerificationCodeModel, error)) *MockIVerificationRepo_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}
