// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"sea-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockICertificateRepository creates a new instance of MockICertificateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICertificateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICertificateRepository {
	mock := &MockICertificateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockICertificateRepository is an autogenerated mock type for the ICertificateRepository type
type MockICertificateRepository struct {
	mock.Mock
}

type MockICertificateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICertificateRepository) EXPECT() *MockICertificateRepository_Expecter {
	return &MockICertificateRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockICertificateRepository
func (_mock *MockICertificateRepository) Create(item models.CertificateModel) (int64, error) {
	ret := _mock.Called(item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.CertificateModel) (int64, error)); ok {
		return returnFunc(item)
	}
	if returnFunc, ok := ret.Get(0).(func(models.CertificateModel) int64); ok {
		r0 = returnFunc(item)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(models.CertificateModel) error); ok {
		r1 = returnFunc(item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICertificateRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockICertificateRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - item models.CertificateModel
func (_e *MockICertificateRepository_Expecter) Create(item interface{}) *MockICertificateRepository_Create_Call {
	return &MockICertificateRepository_Create_Call{Call: _e.mock.On("Create", item)}
}

func (_c *MockICertificateRepository_Create_Call) Run(run func(item models.CertificateModel)) *MockICertificateRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.CertificateModel
		if args[0] != nil {
			arg0 = args[0].(models.CertificateModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICertificateRepository_Create_Call) Return(n int64, err error) *MockICertificateRepository_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockICertificateRepository_Create_Call) RunAndReturn(run func(item models.CertificateModel) (int64, error)) *MockICertificateRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFile provides a mock function for the type MockICertificateRepository
func (_mock *MockICertificateRepository) CreateFile(item models.CertificateFileModel) (int64, error) {
	ret := _mock.Called(item)

	if len(ret) == 0 {
		panic("no return value specified for CreateFile")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.CertificateFileModel) (int64, error)); ok {
		return returnFunc(item)
	}
	if returnFunc, ok := ret.Get(0).(func(models.CertificateFileModel) int64); ok {
		r0 = returnFunc(item)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(models.CertificateFileModel) error); ok {
		r1 = returnFunc(item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICertificateRepository_CreateFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFile'
type MockICertificateRepository_CreateFile_Call struct {
	*mock.Call
}

// CreateFile is a helper method to define mock.On call
//   - item models.CertificateFileModel
func (_e *MockICertificateRepository_Expecter) CreateFile(item interface{}) *MockICertificateRepository_CreateFile_Call {
	return &MockICertificateRepository_CreateFile_Call{Call: _e.mock.On("CreateFile", item)}
}

func (_c *MockICertificateRepository_CreateFile_Call) Run(run func(item models.CertificateFileModel)) *MockICertificateRepository_CreateFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.CertificateFileModel
		if args[0] != nil {
			arg0 = args[0].(models.CertificateFileModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICertificateRepository_CreateFile_Call) Return(n int64, err error) *MockICertificateRepository_CreateFile_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockICertificateRepository_CreateFile_Call) RunAndReturn(run func(item models.CertificateFileModel) (int64, error)) *MockICertificateRepository_CreateFile_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockICertificateRepository
func (_mock *MockICertificateRepository) Delete(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockICertificateRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockICertificateRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int64
func (_e *MockICertificateRepository_Expecter) Delete(id interface{}) *MockICertificateRepository_Delete_Call {
	return &MockICertificateRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockICertificateRepository_Delete_Call) Run(run func(id int64)) *MockICertificateRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICertificateRepository_Delete_Call) Return(err error) *MockICertificateRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockICertificateRepository_Delete_Call) RunAndReturn(run func(id int64) error) *MockICertificateRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockICertificateRepository
func (_mock *MockICertificateRepository) GetAll() ([]models.CertificateModel, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.CertificateModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.CertificateModel, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.CertificateModel); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CertificateModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICertificateRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockICertificateRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockICertificateRepository_Expecter) GetAll() *MockICertificateRepository_GetAll_Call {
	return &MockICertificateRepository_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockICertificateRepository_GetAll_Call) Run(run func()) *MockICertificateRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockICertificateRepository_GetAll_Call) Return(certificateModels []models.CertificateModel, err error) *MockICertificateRepository_GetAll_Call {
	_c.Call.Return(certificateModels, err)
	return _c
}

func (_c *MockICertificateRepository_GetAll_Call) RunAndReturn(run func() ([]models.CertificateModel, error)) *MockICertificateRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllFiles provides a mock function for the type MockICertificateRepository
func (_mock *MockICertificateRepository) GetAllFiles() ([]models.CertificateFileModel, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllFiles")
	}

	var r0 []models.CertificateFileModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.CertificateFileModel, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.CertificateFileModel); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CertificateFileModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICertificateRepository_GetAllFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllFiles'
type MockICertificateRepository_GetAllFiles_Call struct {
	*mock.Call
}

// GetAllFiles is a helper method to define mock.On call
func (_e *MockICertificateRepository_Expecter) GetAllFiles() *MockICertificateRepository_GetAllFiles_Call {
	return &MockICertificateRepository_GetAllFiles_Call{Call: _e.mock.On("GetAllFiles")}
}

func (_c *MockICertificateRepository_GetAllFiles_Call) Run(run func()) *MockICertificateRepository_GetAllFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockICertificateRepository_GetAllFiles_Call) Return(certificateFileModels []models.CertificateFileModel, err error) *MockICertificateRepository_GetAllFiles_Call {
	_c.Call.Return(certificateFileModels, err)
	return _c
}

func (_c *MockICertificateRepository_GetAllFiles_Call) RunAndReturn(run func() ([]models.CertificateFileModel, error)) *MockICertificateRepository_GetAllFiles_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEventIDAndUserIDs provides a mock function for the type MockICertificateRepository
func (_mock *MockICertificateRepository) GetByEventIDAndUserIDs(eventID int64, userIDs []int64) ([]models.CertificateModel, error) {
	ret := _mock.Called(eventID, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetByEventIDAndUserIDs")
	}

	var r0 []models.CertificateModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, []int64) ([]models.CertificateModel, error)); ok {
		return returnFunc(eventID, userIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, []int64) []models.CertificateModel); ok {
		r0 = returnFunc(eventID, userIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CertificateModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64, []int64) error); ok {
		r1 = returnFunc(eventID, userIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICertificateRepository_GetByEventIDAndUserIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEventIDAndUserIDs'
type MockICertificateRepository_GetByEventIDAndUserIDs_Call struct {
	*mock.Call
}

// GetByEventIDAndUserIDs is a helper method to define mock.On call
//   - eventID int64
//   - userIDs []int64
func (_e *MockICertificateRepository_Expecter) GetByEventIDAndUserIDs(eventID interface{}, userIDs interface{}) *MockICertificateRepository_GetByEventIDAndUserIDs_Call {
	return &MockICertificateRepository_GetByEventIDAndUserIDs_Call{Call: _e.mock.On("GetByEventIDAndUserIDs", eventID, userIDs)}
}

func (_c *MockICertificateRepository_GetByEventIDAndUserIDs_Call) Run(run func(eventID int64, userIDs []int64)) *MockICertificateRepository_GetByEventIDAndUserIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 []int64
		if args[1] != nil {
			arg1 = args[1].([]int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockICertificateRepository_GetByEventIDAndUserIDs_Call) Return(certificateModels []models.CertificateModel, err error) *MockICertificateRepository_GetByEventIDAndUserIDs_Call {
	_c.Call.Return(certificateModels, err)
	return _c
}

func (_c *MockICertificateRepository_GetByEventIDAndUserIDs_Call) RunAndReturn(run func(eventID int64, userIDs []int64) ([]models.CertificateModel, error)) *MockICertificateRepository_GetByEventIDAndUserIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetByHash provides a mock function for the type MockICertificateRepository
func (_mock *MockICertificateRepository) GetByHash(hash string) (*models.CertificateModel, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for GetByHash")
	}

	var r0 *models.CertificateModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.CertificateModel, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.CertificateModel); ok {
		r0 = returnFunc(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CertificateModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICertificateRepository_GetByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHash'
type MockICertificateRepository_GetByHash_Call struct {
	*mock.Call
}

// GetByHash is a helper method to define mock.On call
//   - hash string
func (_e *MockICertificateRepository_Expecter) GetByHash(hash interface{}) *MockICertificateRepository_GetByHash_Call {
	return &MockICertificateRepository_GetByHash_Call{Call: _e.mock.On("GetByHash", hash)}
}

func (_c *MockICertificateRepository_GetByHash_Call) Run(run func(hash string)) *MockICertificateRepository_GetByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICertificateRepository_GetByHash_Call) Return(certificateModel *models.CertificateModel, err error) *MockICertificateRepository_GetByHash_Call {
	_c.Call.Return(certificateModel, err)
	return _c
}

func (_c *MockICertificateRepository_GetByHash_Call) RunAndReturn(run func(hash string) (*models.CertificateModel, error)) *MockICertificateRepository_GetByHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockICertificateRepository
func (_mock *MockICertificateRepository) GetByID(id int64) (*models.CertificateModel, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.CertificateModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*models.CertificateModel, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *models.CertificateModel); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CertificateModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICertificateRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockICertificateRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int64
func (_e *MockICertificateRepository_Expecter) GetByID(id interface{}) *MockICertificateRepository_GetByID_Call {
	return &MockICertificateRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockICertificateRepository_GetByID_Call) Run(run func(id int64)) *MockICertificateRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICertificateRepository_GetByID_Call) Return(certificateModel *models.CertificateModel, err error) *MockICertificateRepository_GetByID_Call {
	_c.Call.Return(certificateModel, err)
	return _c
}

func (_c *MockICertificateRepository_GetByID_Call) RunAndReturn(run func(id int64) (*models.CertificateModel, error)) *MockICertificateRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserIDAndEventID provides a mock function for the type MockICertificateRepository
func (_mock *MockICertificateRepository) GetByUserIDAndEventID(user_id int64, eventID int64) (*models.CertificateModel, error) {
	ret := _mock.Called(user_id, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserIDAndEventID")
	}

	var r0 *models.CertificateModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, int64) (*models.CertificateModel, error)); ok {
		return returnFunc(user_id, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, int64) *models.CertificateModel); ok {
		r0 = returnFunc(user_id, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CertificateModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64, int64) error); ok {
		r1 = returnFunc(user_id, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICertificateRepository_GetByUserIDAndEventID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserIDAndEventID'
type MockICertificateRepository_GetByUserIDAndEventID_Call struct {
	*mock.Call
}

// GetByUserIDAndEventID is a helper method to define mock.On call
//   - user_id int64
//   - eventID int64
func (_e *MockICertificateRepository_Expecter) GetByUserIDAndEventID(user_id interface{}, eventID interface{}) *MockICertificateRepository_GetByUserIDAndEventID_Call {
	return &MockICertificateRepository_GetByUserIDAndEventID_Call{Call: _e.mock.On("GetByUserIDAndEventID", user_id, eventID)}
}

func (_c *MockICertificateRepository_GetByUserIDAndEventID_Call) Run(run func(user_id int64, eventID int64)) *MockICertificateRepository_GetByUserIDAndEventID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockICertificateRepository_GetByUserIDAndEventID_Call) Return(certificateModel *models.CertificateModel, err error) *MockICertificateRepository_GetByUserIDAndEventID_Call {
	_c.Call.Return(certificateModel, err)
	return _c
}

func (_c *MockICertificateRepository_GetByUserIDAndEventID_Call) RunAndReturn(run func(user_id int64, eventID int64) (*models.CertificateModel, error)) *MockICertificateRepository_GetByUserIDAndEventID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileByCertificateIDAndLang provides a mock function for the type MockICertificateRepository
func (_mock *MockICertificateRepository) GetFileByCertificateIDAndLang(certificateID int64, lang string) (*models.CertificateFileModel, error) {
	ret := _mock.Called(certificateID, lang)

	if len(ret) == 0 {
		panic("no return value specified for GetFileByCertificateIDAndLang")
	}

	var r0 *models.CertificateFileModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, string) (*models.CertificateFileModel, error)); ok {
		return returnFunc(certificateID, lang)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, string) *models.CertificateFileModel); ok {
		r0 = returnFunc(certificateID, lang)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CertificateFileModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64, string) error); ok {
		r1 = returnFunc(certificateID, lang)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICertificateRepository_GetFileByCertificateIDAndLang_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileByCertificateIDAndLang'
type MockICertificateRepository_GetFileByCertificateIDAndLang_Call struct {
	*mock.Call
}

// GetFileByCertificateIDAndLang is a helper method to define mock.On call
//   - certificateID int64
//   - lang string
func (_e *MockICertificateRepository_Expecter) GetFileByCertificateIDAndLang(certificateID interface{}, lang interface{}) *MockICertificateRepository_GetFileByCertificateIDAndLang_Call {
	return &MockICertificateRepository_GetFileByCertificateIDAndLang_Call{Call: _e.mock.On("GetFileByCertificateIDAndLang", certificateID, lang)}
}

func (_c *MockICertificateRepository_GetFileByCertificateIDAndLang_Call) Run(run func(certificateID int64, lang string)) *MockICertificateRepository_GetFileByCertificateIDAndLang_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockICertificateRepository_GetFileByCertificateIDAndLang_Call) Return(certificateFileModel *models.CertificateFileModel, err error) *MockICertificateRepository_GetFileByCertificateIDAndLang_Call {
	_c.Call.Return(certificateFileModel, err)
	return _c
}

func (_c *MockICertificateRepository_GetFileByCertificateIDAndLang_Call) RunAndReturn(run func(certificateID int64, lang string) (*models.CertificateFileModel, error)) *MockICertificateRepository_GetFileByCertificateIDAndLang_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileById provides a mock function for the type MockICertificateRepository
func (_mock *MockICertificateRepository) GetFileById(id int64) (*models.CertificateFileModel, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetFileById")
	}

	var r0 *models.CertificateFileModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*models.CertificateFileModel, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *models.CertificateFileModel); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CertificateFileModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICertificateRepository_GetFileById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileById'
type MockICertificateRepository_GetFileById_Call struct {
	*mock.Call
}

// GetFileById is a helper method to define mock.On call
//   - id int64
func (_e *MockICertificateRepository_Expecter) GetFileById(id interface{}) *MockICertificateRepository_GetFileById_Call {
	return &MockICertificateRepository_GetFileById_Call{Call: _e.mock.On("GetFileById", id)}
}

func (_c *MockICertificateRepository_GetFileById_Call) Run(run func(id int64)) *MockICertificateRepository_GetFileById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICertificateRepository_GetFileById_Call) Return(certificateFileModel *models.CertificateFileModel, err error) *MockICertificateRepository_GetFileById_Call {
	_c.Call.Return(certificateFileModel, err)
	return _c
}

func (_c *MockICertificateRepository_GetFileById_Call) RunAndReturn(run func(id int64) (*models.CertificateFileModel, error)) *MockICertificateRepository_GetFileById_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilesByCertificateID provides a mock function for the type MockICertificateRepository
func (_mock *MockICertificateRepository) GetFilesByCertificateID(certificateID int64) ([]models.CertificateFileModel, error) {
	ret := _mock.Called(certificateID)

	if len(ret) == 0 {
		panic("no return value specified for GetFilesByCertificateID")
	}

	var r0 []models.CertificateFileModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) ([]models.CertificateFileModel, error)); ok {
		return returnFunc(certificateID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) []models.CertificateFileModel); ok {
		r0 = returnFunc(certificateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CertificateFileModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(certificateID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICertificateRepository_GetFilesByCertificateID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilesByCertificateID'
type MockICertificateRepository_GetFilesByCertificateID_Call struct {
	*mock.Call
}

// GetFilesByCertificateID is a helper method to define mock.On call
//   - certificateID int64
func (_e *MockICertificateRepository_Expecter) GetFilesByCertificateID(certificateID interface{}) *MockICertificateRepository_GetFilesByCertificateID_Call {
	return &MockICertificateRepository_GetFilesByCertificateID_Call{Call: _e.mock.On("GetFilesByCertificateID", certificateID)}
}

func (_c *MockICertificateRepository_GetFilesByCertificateID_Call) Run(run func(certificateID int64)) *MockICertificateRepository_GetFilesByCertificateID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICertificateRepository_GetFilesByCertificateID_Call) Return(certificateFileModels []models.CertificateFileModel, err error) *MockICertificateRepository_GetFilesByCertificateID_Call {
	_c.Call.Return(certificateFileModels, err)
	return _c
}

func (_c *MockICertificateRepository_GetFilesByCertificateID_Call) RunAndReturn(run func(certificateID int64) ([]models.CertificateFileModel, error)) *MockICertificateRepository_GetFilesByCertificateID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockICertificateRepository
func (_mock *MockICertificateRepository) Update(item *models.CertificateModel) error {
	ret := _mock.Called(item)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.CertificateModel) error); ok {
		r0 = returnFunc(item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockICertificateRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockICertificateRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - item *models.CertificateModel
func (_e *MockICertificateRepository_Expecter) Update(item interface{}) *MockICertificateRepository_Update_Call {
	return &MockICertificateRepository_Update_Call{Call: _e.mock.On("Update", item)}
}

func (_c *MockICertificateRepository_Update_Call) Run(run func(item *models.CertificateModel)) *MockICertificateRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.CertificateModel
		if args[0] != nil {
			arg0 = args[0].(*models.CertificateModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICertificateRepository_Update_Call) Return(err error) *MockICertificateRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockICertificateRepository_Update_Call) RunAndReturn(run func(item *models.CertificateModel) error) *MockICertificateRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFile provides a mock function for the type MockICertificateRepository
func (_mock *MockICertificateRepository) UpdateFile(id int64, storeID int64) error {
	ret := _mock.Called(id, storeID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = returnFunc(id, storeID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockICertificateRepository_UpdateFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFile'
type MockICertificateRepository_UpdateFile_Call struct {
	*mock.Call
}

// UpdateFile is a helper method to define mock.On call
//   - id int64
//   - storeID int64
func (_e *MockICertificateRepository_Expecter) UpdateFile(id interface{}, storeID interface{}) *MockICertificateRepository_UpdateFile_Call {
	return &MockICertificateRepository_UpdateFile_Call{Call: _e.mock.On("UpdateFile", id, storeID)}
}

func (_c *MockICertificateRepository_UpdateFile_Call) Run(run func(id int64, storeID int64)) *MockICertificateRepository_UpdateFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockICertificateRepository_UpdateFile_Call) Return(err error) *MockICertificateRepository_UpdateFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockICertificateRepository_UpdateFile_Call) RunAndReturn(run func(id int64, storeID int64) error) *MockICertificateRepository_UpdateFile_Call {
	_c.Call.Return(run)
	return _c
}
