// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"sea-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIMailService creates a new instance of MockIMailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMailService {
	mock := &MockIMailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIMailService is an autogenerated mock type for the IMailService type
type MockIMailService struct {
	mock.Mock
}

type MockIMailService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIMailService) EXPECT() *MockIMailService_Expecter {
	return &MockIMailService_Expecter{mock: &_m.Mock}
}

// SendEmail provides a mock function for the type MockIMailService
func (_mock *MockIMailService) SendEmail(e models.Email) error {
	ret := _mock.Called(e)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(models.Email) error); ok {
		r0 = returnFunc(e)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIMailService_SendEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmail'
type MockIMailService_SendEmail_Call struct {
	*mock.Call
}

// SendEmail is a helper method to define mock.On call
//   - e models.Email
func (_e *MockIMailService_Expecter) SendEmail(e interface{}) *MockIMailService_SendEmail_Call {
	return &MockIMailService_SendEmail_Call{Call: _e.mock.On("SendEmail", e)}
}

func (_c *MockIMailService_SendEmail_Call) Run(run func(e models.Email)) *MockIMailService_SendEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.Email
		if args[0] != nil {
			arg0 = args[0].(models.Email)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIMailService_SendEmail_Call) Return(err error) *MockIMailService_SendEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIMailService_SendEmail_Call) RunAndReturn(run func(e models.Email) error) *MockIMailService_SendEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendUsersEmails provides a mock function for the type MockIMailService
func (_mock *MockIMailService) SendUsersEmails(e models.UsersEmails) error {
	ret := _mock.Called(e)

	if len(ret) == 0 {
		panic("no return value specified for SendUsersEmails")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(models.UsersEmails) error); ok {
		r0 = returnFunc(e)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIMailService_SendUsersEmails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendUsersEmails'
type MockIMailService_SendUsersEmails_Call struct {
	*mock.Call
}

// SendUsersEmails is a helper method to define mock.On call
//   - e models.UsersEmails
func (_e *MockIMailService_Expecter) SendUsersEmails(e interface{}) *MockIMailService_SendUsersEmails_Call {
	return &MockIMailService_SendUsersEmails_Call{Call: _e.mock.On("SendUsersEmails", e)}
}

func (_c *MockIMailService_SendUsersEmails_Call) Run(run func(e models.UsersEmails)) *MockIMailService_SendUsersEmails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.UsersEmails
		if args[0] != nil {
			arg0 = args[0].(models.UsersEmails)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIMailService_SendUsersEmails_Call) Return(err error) *MockIMailService_SendUsersEmails_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIMailService_SendUsersEmails_Call) RunAndReturn(run func(e models.UsersEmails) error) *MockIMailService_SendUsersEmails_Call {
	_c.Call.Return(run)
	return _c
}

// SendVerificationCode provides a mock function for the type MockIMailService
func (_mock *MockIMailService) SendVerificationCode(to string, data models.VerifyEmail) error {
	ret := _mock.Called(to, data)

	if len(ret) == 0 {
		panic("no return value specified for SendVerificationCode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, models.VerifyEmail) error); ok {
		r0 = returnFunc(to, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIMailService_SendVerificationCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendVerificationCode'
type MockIMailService_SendVerificationCode_Call struct {
	*mock.Call
}

// SendVerificationCode is a helper method to define mock.On call
//   - to string
//   - data models.VerifyEmail
func (_e *MockIMailService_Expecter) SendVerificationCode(to interface{}, data interface{}) *MockIMailService_SendVerificationCode_Call {
	return &MockIMailService_SendVerificationCode_Call{Call: _e.mock.On("SendVerificationCode", to, data)}
}

func (_c *MockIMailService_SendVerificationCode_Call) Run(run func(to string, data models.VerifyEmail)) *MockIMailService_SendVerificationCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 models.VerifyEmail
		if args[1] != nil {
			arg1 = args[1].(models.VerifyEmail)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIMailService_SendVerificationCode_Call) Return(err error) *MockIMailService_SendVerificationCode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIMailService_SendVerificationCode_Call) RunAndReturn(run func(to string, data models.VerifyEmail) error) *MockIMailService_SendVerificationCode_Call {
	_c.Call.Return(run)
	return _c
}
