// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"sea-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockICollaboratorRepo creates a new instance of MockICollaboratorRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICollaboratorRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICollaboratorRepo {
	mock := &MockICollaboratorRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockICollaboratorRepo is an autogenerated mock type for the ICollaboratorRepo type
type MockICollaboratorRepo struct {
	mock.Mock
}

type MockICollaboratorRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICollaboratorRepo) EXPECT() *MockICollaboratorRepo_Expecter {
	return &MockICollaboratorRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockICollaboratorRepo
func (_mock *MockICollaboratorRepo) Create(collab *models.CollaboratorModel) (int64, error) {
	ret := _mock.Called(collab)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.CollaboratorModel) (int64, error)); ok {
		return returnFunc(collab)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.CollaboratorModel) int64); ok {
		r0 = returnFunc(collab)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.CollaboratorModel) error); ok {
		r1 = returnFunc(collab)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICollaboratorRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockICollaboratorRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - collab *models.CollaboratorModel
func (_e *MockICollaboratorRepo_Expecter) Create(collab interface{}) *MockICollaboratorRepo_Create_Call {
	return &MockICollaboratorRepo_Create_Call{Call: _e.mock.On("Create", collab)}
}

func (_c *MockICollaboratorRepo_Create_Call) Run(run func(collab *models.CollaboratorModel)) *MockICollaboratorRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.CollaboratorModel
		if args[0] != nil {
			arg0 = args[0].(*models.CollaboratorModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICollaboratorRepo_Create_Call) Return(n int64, err error) *MockICollaboratorRepo_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockICollaboratorRepo_Create_Call) RunAndReturn(run func(collab *models.CollaboratorModel) (int64, error)) *MockICollaboratorRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockICollaboratorRepo
func (_mock *MockICollaboratorRepo) Delete(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockICollaboratorRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockICollaboratorRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int64
func (_e *MockICollaboratorRepo_Expecter) Delete(id interface{}) *MockICollaboratorRepo_Delete_Call {
	return &MockICollaboratorRepo_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockICollaboratorRepo_Delete_Call) Run(run func(id int64)) *MockICollaboratorRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICollaboratorRepo_Delete_Call) Return(err error) *MockICollaboratorRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockICollaboratorRepo_Delete_Call) RunAndReturn(run func(id int64) error) *MockICollaboratorRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockICollaboratorRepo
func (_mock *MockICollaboratorRepo) GetAll() ([]models.CollaboratorModel, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.CollaboratorModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.CollaboratorModel, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.CollaboratorModel); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CollaboratorModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICollaboratorRepo_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockICollaboratorRepo_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockICollaboratorRepo_Expecter) GetAll() *MockICollaboratorRepo_GetAll_Call {
	return &MockICollaboratorRepo_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockICollaboratorRepo_GetAll_Call) Run(run func()) *MockICollaboratorRepo_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockICollaboratorRepo_GetAll_Call) Return(collaboratorModels []models.CollaboratorModel, err error) *MockICollaboratorRepo_GetAll_Call {
	_c.Call.Return(collaboratorModels, err)
	return _c
}

func (_c *MockICollaboratorRepo_GetAll_Call) RunAndReturn(run func() ([]models.CollaboratorModel, error)) *MockICollaboratorRepo_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockICollaboratorRepo
func (_mock *MockICollaboratorRepo) GetByID(id int64) (*models.CollaboratorModel, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.CollaboratorModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*models.CollaboratorModel, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *models.CollaboratorModel); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CollaboratorModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICollaboratorRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockICollaboratorRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int64
func (_e *MockICollaboratorRepo_Expecter) GetByID(id interface{}) *MockICollaboratorRepo_GetByID_Call {
	return &MockICollaboratorRepo_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockICollaboratorRepo_GetByID_Call) Run(run func(id int64)) *MockICollaboratorRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICollaboratorRepo_GetByID_Call) Return(collaboratorModel *models.CollaboratorModel, err error) *MockICollaboratorRepo_GetByID_Call {
	_c.Call.Return(collaboratorModel, err)
	return _c
}

func (_c *MockICollaboratorRepo_GetByID_Call) RunAndReturn(run func(id int64) (*models.CollaboratorModel, error)) *MockICollaboratorRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockICollaboratorRepo
func (_mock *MockICollaboratorRepo) Update(collab *models.CollaboratorModel) error {
	ret := _mock.Called(collab)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.CollaboratorModel) error); ok {
		r0 = returnFunc(collab)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockICollaboratorRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockICollaboratorRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - collab *models.CollaboratorModel
func (_e *MockICollaboratorRepo_Expecter) Update(collab interface{}) *MockICollaboratorRepo_Update_Call {
	return &MockICollaboratorRepo_Update_Call{Call: _e.mock.On("Update", collab)}
}

func (_c *MockICollaboratorRepo_Update_Call) Run(run func(collab *models.CollaboratorModel)) *MockICollaboratorRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.CollaboratorModel
		if args[0] != nil {
			arg0 = args[0].(*models.CollaboratorModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICollaboratorRepo_Update_Call) Return(err error) *MockICollaboratorRepo_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockICollaboratorRepo_Update_Call) RunAndReturn(run func(collab *models.CollaboratorModel) error) *MockICollaboratorRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}
