// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"sea-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIGalleryRepository creates a new instance of MockIGalleryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIGalleryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIGalleryRepository {
	mock := &MockIGalleryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIGalleryRepository is an autogenerated mock type for the IGalleryRepository type
type MockIGalleryRepository struct {
	mock.Mock
}

type MockIGalleryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIGalleryRepository) EXPECT() *MockIGalleryRepository_Expecter {
	return &MockIGalleryRepository_Expecter{mock: &_m.Mock}
}

// CreateAsset provides a mock function for the type MockIGalleryRepository
func (_mock *MockIGalleryRepository) CreateAsset(asset *models.GalleryAssetModel) (int64, error) {
	ret := _mock.Called(asset)

	if len(ret) == 0 {
		panic("no return value specified for CreateAsset")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.GalleryAssetModel) (int64, error)); ok {
		return returnFunc(asset)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.GalleryAssetModel) int64); ok {
		r0 = returnFunc(asset)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.GalleryAssetModel) error); ok {
		r1 = returnFunc(asset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGalleryRepository_CreateAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAsset'
type MockIGalleryRepository_CreateAsset_Call struct {
	*mock.Call
}

// CreateAsset is a helper method to define mock.On call
//   - asset *models.GalleryAssetModel
func (_e *MockIGalleryRepository_Expecter) CreateAsset(asset interface{}) *MockIGalleryRepository_CreateAsset_Call {
	return &MockIGalleryRepository_CreateAsset_Call{Call: _e.mock.On("CreateAsset", asset)}
}

func (_c *MockIGalleryRepository_CreateAsset_Call) Run(run func(asset *models.GalleryAssetModel)) *MockIGalleryRepository_CreateAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.GalleryAssetModel
		if args[0] != nil {
			arg0 = args[0].(*models.GalleryAssetModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIGalleryRepository_CreateAsset_Call) Return(n int64, err error) *MockIGalleryRepository_CreateAsset_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIGalleryRepository_CreateAsset_Call) RunAndReturn(run func(asset *models.GalleryAssetModel) (int64, error)) *MockIGalleryRepository_CreateAsset_Call {
	_c.Call.Return(run)
	return _c
}

// CreateReference provides a mock function for the type MockIGalleryRepository
func (_mock *MockIGalleryRepository) CreateReference(ref *models.GalleryReferenceModel) (int64, error) {
	ret := _mock.Called(ref)

	if len(ret) == 0 {
		panic("no return value specified for CreateReference")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.GalleryReferenceModel) (int64, error)); ok {
		return returnFunc(ref)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.GalleryReferenceModel) int64); ok {
		r0 = returnFunc(ref)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.GalleryReferenceModel) error); ok {
		r1 = returnFunc(ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGalleryRepository_CreateReference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReference'
type MockIGalleryRepository_CreateReference_Call struct {
	*mock.Call
}

// CreateReference is a helper method to define mock.On call
//   - ref *models.GalleryReferenceModel
func (_e *MockIGalleryRepository_Expecter) CreateReference(ref interface{}) *MockIGalleryRepository_CreateReference_Call {
	return &MockIGalleryRepository_CreateReference_Call{Call: _e.mock.On("CreateReference", ref)}
}

func (_c *MockIGalleryRepository_CreateReference_Call) Run(run func(ref *models.GalleryReferenceModel)) *MockIGalleryRepository_CreateReference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.GalleryReferenceModel
		if args[0] != nil {
			arg0 = args[0].(*models.GalleryReferenceModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIGalleryRepository_CreateReference_Call) Return(n int64, err error) *MockIGalleryRepository_CreateReference_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIGalleryRepository_CreateReference_Call) RunAndReturn(run func(ref *models.GalleryReferenceModel) (int64, error)) *MockIGalleryRepository_CreateReference_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAsset provides a mock function for the type MockIGalleryRepository
func (_mock *MockIGalleryRepository) DeleteAsset(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAsset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIGalleryRepository_DeleteAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAsset'
type MockIGalleryRepository_DeleteAsset_Call struct {
	*mock.Call
}

// DeleteAsset is a helper method to define mock.On call
//   - id int64
func (_e *MockIGalleryRepository_Expecter) DeleteAsset(id interface{}) *MockIGalleryRepository_DeleteAsset_Call {
	return &MockIGalleryRepository_DeleteAsset_Call{Call: _e.mock.On("DeleteAsset", id)}
}

func (_c *MockIGalleryRepository_DeleteAsset_Call) Run(run func(id int64)) *MockIGalleryRepository_DeleteAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIGalleryRepository_DeleteAsset_Call) Return(err error) *MockIGalleryRepository_DeleteAsset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIGalleryRepository_DeleteAsset_Call) RunAndReturn(run func(id int64) error) *MockIGalleryRepository_DeleteAsset_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteReference provides a mock function for the type MockIGalleryRepository
func (_mock *MockIGalleryRepository) DeleteReference(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReference")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIGalleryRepository_DeleteReference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteReference'
type MockIGalleryRepository_DeleteReference_Call struct {
	*mock.Call
}

// DeleteReference is a helper method to define mock.On call
//   - id int64
func (_e *MockIGalleryRepository_Expecter) DeleteReference(id interface{}) *MockIGalleryRepository_DeleteReference_Call {
	return &MockIGalleryRepository_DeleteReference_Call{Call: _e.mock.On("DeleteReference", id)}
}

func (_c *MockIGalleryRepository_DeleteReference_Call) Run(run func(id int64)) *MockIGalleryRepository_DeleteReference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIGalleryRepository_DeleteReference_Call) Return(err error) *MockIGalleryRepository_DeleteReference_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIGalleryRepository_DeleteReference_Call) RunAndReturn(run func(id int64) error) *MockIGalleryRepository_DeleteReference_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteReferencesByAsset provides a mock function for the type MockIGalleryRepository
func (_mock *MockIGalleryRepository) DeleteReferencesByAsset(assetID int64) error {
	ret := _mock.Called(assetID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReferencesByAsset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(assetID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIGalleryRepository_DeleteReferencesByAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteReferencesByAsset'
type MockIGalleryRepository_DeleteReferencesByAsset_Call struct {
	*mock.Call
}

// DeleteReferencesByAsset is a helper method to define mock.On call
//   - assetID int64
func (_e *MockIGalleryRepository_Expecter) DeleteReferencesByAsset(assetID interface{}) *MockIGalleryRepository_DeleteReferencesByAsset_Call {
	return &MockIGalleryRepository_DeleteReferencesByAsset_Call{Call: _e.mock.On("DeleteReferencesByAsset", assetID)}
}

func (_c *MockIGalleryRepository_DeleteReferencesByAsset_Call) Run(run func(assetID int64)) *MockIGalleryRepository_DeleteReferencesByAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIGalleryRepository_DeleteReferencesByAsset_Call) Return(err error) *MockIGalleryRepository_DeleteReferencesByAsset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIGalleryRepository_DeleteReferencesByAsset_Call) RunAndReturn(run func(assetID int64) error) *MockIGalleryRepository_DeleteReferencesByAsset_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteReferencesByObject provides a mock function for the type MockIGalleryRepository
func (_mock *MockIGalleryRepository) DeleteReferencesByObject(objectType models.ObjectType, objectID int64) error {
	ret := _mock.Called(objectType, objectID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReferencesByObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(models.ObjectType, int64) error); ok {
		r0 = returnFunc(objectType, objectID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIGalleryRepository_DeleteReferencesByObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteReferencesByObject'
type MockIGalleryRepository_DeleteReferencesByObject_Call struct {
	*mock.Call
}

// DeleteReferencesByObject is a helper method to define mock.On call
//   - objectType models.ObjectType
//   - objectID int64
func (_e *MockIGalleryRepository_Expecter) DeleteReferencesByObject(objectType interface{}, objectID interface{}) *MockIGalleryRepository_DeleteReferencesByObject_Call {
	return &MockIGalleryRepository_DeleteReferencesByObject_Call{Call: _e.mock.On("DeleteReferencesByObject", objectType, objectID)}
}

func (_c *MockIGalleryRepository_DeleteReferencesByObject_Call) Run(run func(objectType models.ObjectType, objectID int64)) *MockIGalleryRepository_DeleteReferencesByObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.ObjectType
		if args[0] != nil {
			arg0 = args[0].(models.ObjectType)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIGalleryRepository_DeleteReferencesByObject_Call) Return(err error) *MockIGalleryRepository_DeleteReferencesByObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIGalleryRepository_DeleteReferencesByObject_Call) RunAndReturn(run func(objectType models.ObjectType, objectID int64) error) *MockIGalleryRepository_DeleteReferencesByObject_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllAssets provides a mock function for the type MockIGalleryRepository
func (_mock *MockIGalleryRepository) GetAllAssets() ([]models.GalleryAssetModel, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllAssets")
	}

	var r0 []models.GalleryAssetModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.GalleryAssetModel, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.GalleryAssetModel); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.GalleryAssetModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGalleryRepository_GetAllAssets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAssets'
type MockIGalleryRepository_GetAllAssets_Call struct {
	*mock.Call
}

// GetAllAssets is a helper method to define mock.On call
func (_e *MockIGalleryRepository_Expecter) GetAllAssets() *MockIGalleryRepository_GetAllAssets_Call {
	return &MockIGalleryRepository_GetAllAssets_Call{Call: _e.mock.On("GetAllAssets")}
}

func (_c *MockIGalleryRepository_GetAllAssets_Call) Run(run func()) *MockIGalleryRepository_GetAllAssets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIGalleryRepository_GetAllAssets_Call) Return(galleryAssetModels []models.GalleryAssetModel, err error) *MockIGalleryRepository_GetAllAssets_Call {
	_c.Call.Return(galleryAssetModels, err)
	return _c
}

func (_c *MockIGalleryRepository_GetAllAssets_Call) RunAndReturn(run func() ([]models.GalleryAssetModel, error)) *MockIGalleryRepository_GetAllAssets_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllGallery provides a mock function for the type MockIGalleryRepository
func (_mock *MockIGalleryRepository) GetAllGallery() ([]models.GallerySqlModel, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllGallery")
	}

	var r0 []models.GallerySqlModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.GallerySqlModel, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.GallerySqlModel); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.GallerySqlModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGalleryRepository_GetAllGallery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllGallery'
type MockIGalleryRepository_GetAllGallery_Call struct {
	*mock.Call
}

// GetAllGallery is a helper method to define mock.On call
func (_e *MockIGalleryRepository_Expecter) GetAllGallery() *MockIGalleryRepository_GetAllGallery_Call {
	return &MockIGalleryRepository_GetAllGallery_Call{Call: _e.mock.On("GetAllGallery")}
}

func (_c *MockIGalleryRepository_GetAllGallery_Call) Run(run func()) *MockIGalleryRepository_GetAllGallery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIGalleryRepository_GetAllGallery_Call) Return(gallerySqlModels []models.GallerySqlModel, err error) *MockIGalleryRepository_GetAllGallery_Call {
	_c.Call.Return(gallerySqlModels, err)
	return _c
}

func (_c *MockIGalleryRepository_GetAllGallery_Call) RunAndReturn(run func() ([]models.GallerySqlModel, error)) *MockIGalleryRepository_GetAllGallery_Call {
	_c.Call.Return(run)
	return _c
}

// GetAssetByID provides a mock function for the type MockIGalleryRepository
func (_mock *MockIGalleryRepository) GetAssetByID(id int64) (*models.GalleryAssetModel, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetAssetByID")
	}

	var r0 *models.GalleryAssetModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*models.GalleryAssetModel, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *models.GalleryAssetModel); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GalleryAssetModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGalleryRepository_GetAssetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAssetByID'
type MockIGalleryRepository_GetAssetByID_Call struct {
	*mock.Call
}

// GetAssetByID is a helper method to define mock.On call
//   - id int64
func (_e *MockIGalleryRepository_Expecter) GetAssetByID(id interface{}) *MockIGalleryRepository_GetAssetByID_Call {
	return &MockIGalleryRepository_GetAssetByID_Call{Call: _e.mock.On("GetAssetByID", id)}
}

func (_c *MockIGalleryRepository_GetAssetByID_Call) Run(run func(id int64)) *MockIGalleryRepository_GetAssetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIGalleryRepository_GetAssetByID_Call) Return(galleryAssetModel *models.GalleryAssetModel, err error) *MockIGalleryRepository_GetAssetByID_Call {
	_c.Call.Return(galleryAssetModel, err)
	return _c
}

func (_c *MockIGalleryRepository_GetAssetByID_Call) RunAndReturn(run func(id int64) (*models.GalleryAssetModel, error)) *MockIGalleryRepository_GetAssetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetReferenceByID provides a mock function for the type MockIGalleryRepository
func (_mock *MockIGalleryRepository) GetReferenceByID(id int64) (*models.GalleryReferenceModel, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetReferenceByID")
	}

	var r0 *models.GalleryReferenceModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*models.GalleryReferenceModel, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *models.GalleryReferenceModel); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GalleryReferenceModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGalleryRepository_GetReferenceByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReferenceByID'
type MockIGalleryRepository_GetReferenceByID_Call struct {
	*mock.Call
}

// GetReferenceByID is a helper method to define mock.On call
//   - id int64
func (_e *MockIGalleryRepository_Expecter) GetReferenceByID(id interface{}) *MockIGalleryRepository_GetReferenceByID_Call {
	return &MockIGalleryRepository_GetReferenceByID_Call{Call: _e.mock.On("GetReferenceByID", id)}
}

func (_c *MockIGalleryRepository_GetReferenceByID_Call) Run(run func(id int64)) *MockIGalleryRepository_GetReferenceByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIGalleryRepository_GetReferenceByID_Call) Return(galleryReferenceModel *models.GalleryReferenceModel, err error) *MockIGalleryRepository_GetReferenceByID_Call {
	_c.Call.Return(galleryReferenceModel, err)
	return _c
}

func (_c *MockIGalleryRepository_GetReferenceByID_Call) RunAndReturn(run func(id int64) (*models.GalleryReferenceModel, error)) *MockIGalleryRepository_GetReferenceByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetReferenceByObject provides a mock function for the type MockIGalleryRepository
func (_mock *MockIGalleryRepository) GetReferenceByObject(objectType models.ObjectType, objectID int64) (*models.GalleryReferenceModel, error) {
	ret := _mock.Called(objectType, objectID)

	if len(ret) == 0 {
		panic("no return value specified for GetReferenceByObject")
	}

	var r0 *models.GalleryReferenceModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.ObjectType, int64) (*models.GalleryReferenceModel, error)); ok {
		return returnFunc(objectType, objectID)
	}
	if returnFunc, ok := ret.Get(0).(func(models.ObjectType, int64) *models.GalleryReferenceModel); ok {
		r0 = returnFunc(objectType, objectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GalleryReferenceModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(models.ObjectType, int64) error); ok {
		r1 = returnFunc(objectType, objectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGalleryRepository_GetReferenceByObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReferenceByObject'
type MockIGalleryRepository_GetReferenceByObject_Call struct {
	*mock.Call
}

// GetReferenceByObject is a helper method to define mock.On call
//   - objectType models.ObjectType
//   - objectID int64
func (_e *MockIGalleryRepository_Expecter) GetReferenceByObject(objectType interface{}, objectID interface{}) *MockIGalleryRepository_GetReferenceByObject_Call {
	return &MockIGalleryRepository_GetReferenceByObject_Call{Call: _e.mock.On("GetReferenceByObject", objectType, objectID)}
}

func (_c *MockIGalleryRepository_GetReferenceByObject_Call) Run(run func(objectType models.ObjectType, objectID int64)) *MockIGalleryRepository_GetReferenceByObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.ObjectType
		if args[0] != nil {
			arg0 = args[0].(models.ObjectType)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIGalleryRepository_GetReferenceByObject_Call) Return(galleryReferenceModel *models.GalleryReferenceModel, err error) *MockIGalleryRepository_GetReferenceByObject_Call {
	_c.Call.Return(galleryReferenceModel, err)
	return _c
}

func (_c *MockIGalleryRepository_GetReferenceByObject_Call) RunAndReturn(run func(objectType models.ObjectType, objectID int64) (*models.GalleryReferenceModel, error)) *MockIGalleryRepository_GetReferenceByObject_Call {
	_c.Call.Return(run)
	return _c
}

// GetReferencesByAssetID provides a mock function for the type MockIGalleryRepository
func (_mock *MockIGalleryRepository) GetReferencesByAssetID(assetID int64) ([]models.GalleryReferenceModel, error) {
	ret := _mock.Called(assetID)

	if len(ret) == 0 {
		panic("no return value specified for GetReferencesByAssetID")
	}

	var r0 []models.GalleryReferenceModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) ([]models.GalleryReferenceModel, error)); ok {
		return returnFunc(assetID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) []models.GalleryReferenceModel); ok {
		r0 = returnFunc(assetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.GalleryReferenceModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(assetID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGalleryRepository_GetReferencesByAssetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReferencesByAssetID'
type MockIGalleryRepository_GetReferencesByAssetID_Call struct {
	*mock.Call
}

// GetReferencesByAssetID is a helper method to define mock.On call
//   - assetID int64
func (_e *MockIGalleryRepository_Expecter) GetReferencesByAssetID(assetID interface{}) *MockIGalleryRepository_GetReferencesByAssetID_Call {
	return &MockIGalleryRepository_GetReferencesByAssetID_Call{Call: _e.mock.On("GetReferencesByAssetID", assetID)}
}

func (_c *MockIGalleryRepository_GetReferencesByAssetID_Call) Run(run func(assetID int64)) *MockIGalleryRepository_GetReferencesByAssetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIGalleryRepository_GetReferencesByAssetID_Call) Return(galleryReferenceModels []models.GalleryReferenceModel, err error) *MockIGalleryRepository_GetReferencesByAssetID_Call {
	_c.Call.Return(galleryReferenceModels, err)
	return _c
}

func (_c *MockIGalleryRepository_GetReferencesByAssetID_Call) RunAndReturn(run func(assetID int64) ([]models.GalleryReferenceModel, error)) *MockIGalleryRepository_GetReferencesByAssetID_Call {
	_c.Call.Return(run)
	return _c
}

// GetReferencesByObjectType provides a mock function for the type MockIGalleryRepository
func (_mock *MockIGalleryRepository) GetReferencesByObjectType(objectType models.ObjectType) ([]models.GalleryReferenceModel, error) {
	ret := _mock.Called(objectType)

	if len(ret) == 0 {
		panic("no return value specified for GetReferencesByObjectType")
	}

	var r0 []models.GalleryReferenceModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.ObjectType) ([]models.GalleryReferenceModel, error)); ok {
		return returnFunc(objectType)
	}
	if returnFunc, ok := ret.Get(0).(func(models.ObjectType) []models.GalleryReferenceModel); ok {
		r0 = returnFunc(objectType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.GalleryReferenceModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(models.ObjectType) error); ok {
		r1 = returnFunc(objectType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGalleryRepository_GetReferencesByObjectType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReferencesByObjectType'
type MockIGalleryRepository_GetReferencesByObjectType_Call struct {
	*mock.Call
}

// GetReferencesByObjectType is a helper method to define mock.On call
//   - objectType models.ObjectType
func (_e *MockIGalleryRepository_Expecter) GetReferencesByObjectType(objectType interface{}) *MockIGalleryRepository_GetReferencesByObjectType_Call {
	return &MockIGalleryRepository_GetReferencesByObjectType_Call{Call: _e.mock.On("GetReferencesByObjectType", objectType)}
}

func (_c *MockIGalleryRepository_GetReferencesByObjectType_Call) Run(run func(objectType models.ObjectType)) *MockIGalleryRepository_GetReferencesByObjectType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.ObjectType
		if args[0] != nil {
			arg0 = args[0].(models.ObjectType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIGalleryRepository_GetReferencesByObjectType_Call) Return(galleryReferenceModels []models.GalleryReferenceModel, err error) *MockIGalleryRepository_GetReferencesByObjectType_Call {
	_c.Call.Return(galleryReferenceModels, err)
	return _c
}

func (_c *MockIGalleryRepository_GetReferencesByObjectType_Call) RunAndReturn(run func(objectType models.ObjectType) ([]models.GalleryReferenceModel, error)) *MockIGalleryRepository_GetReferencesByObjectType_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnreferencedAssetIDs provides a mock function for the type MockIGalleryRepository
func (_mock *MockIGalleryRepository) GetUnreferencedAssetIDs() ([]models.GalleryAssetModel, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUnreferencedAssetIDs")
	}

	var r0 []models.GalleryAssetModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.GalleryAssetModel, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.GalleryAssetModel); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.GalleryAssetModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIGalleryRepository_GetUnreferencedAssetIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnreferencedAssetIDs'
type MockIGalleryRepository_GetUnreferencedAssetIDs_Call struct {
	*mock.Call
}

// GetUnreferencedAssetIDs is a helper method to define mock.On call
func (_e *MockIGalleryRepository_Expecter) GetUnreferencedAssetIDs() *MockIGalleryRepository_GetUnreferencedAssetIDs_Call {
	return &MockIGalleryRepository_GetUnreferencedAssetIDs_Call{Call: _e.mock.On("GetUnreferencedAssetIDs")}
}

func (_c *MockIGalleryRepository_GetUnreferencedAssetIDs_Call) Run(run func()) *MockIGalleryRepository_GetUnreferencedAssetIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIGalleryRepository_GetUnreferencedAssetIDs_Call) Return(galleryAssetModels []models.GalleryAssetModel, err error) *MockIGalleryRepository_GetUnreferencedAssetIDs_Call {
	_c.Call.Return(galleryAssetModels, err)
	return _c
}

func (_c *MockIGalleryRepository_GetUnreferencedAssetIDs_Call) RunAndReturn(run func() ([]models.GalleryAssetModel, error)) *MockIGalleryRepository_GetUnreferencedAssetIDs_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAsset provides a mock function for the type MockIGalleryRepository
func (_mock *MockIGalleryRepository) UpdateAsset(asset *models.GalleryAssetModel) error {
	ret := _mock.Called(asset)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAsset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.GalleryAssetModel) error); ok {
		r0 = returnFunc(asset)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIGalleryRepository_UpdateAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAsset'
type MockIGalleryRepository_UpdateAsset_Call struct {
	*mock.Call
}

// UpdateAsset is a helper method to define mock.On call
//   - asset *models.GalleryAssetModel
func (_e *MockIGalleryRepository_Expecter) UpdateAsset(asset interface{}) *MockIGalleryRepository_UpdateAsset_Call {
	return &MockIGalleryRepository_UpdateAsset_Call{Call: _e.mock.On("UpdateAsset", asset)}
}

func (_c *MockIGalleryRepository_UpdateAsset_Call) Run(run func(asset *models.GalleryAssetModel)) *MockIGalleryRepository_UpdateAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.GalleryAssetModel
		if args[0] != nil {
			arg0 = args[0].(*models.GalleryAssetModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIGalleryRepository_UpdateAsset_Call) Return(err error) *MockIGalleryRepository_UpdateAsset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIGalleryRepository_UpdateAsset_Call) RunAndReturn(run func(asset *models.GalleryAssetModel) error) *MockIGalleryRepository_UpdateAsset_Call {
	_c.Call.Return(run)
	return _c
}
