// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"sea-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockICmsRepository creates a new instance of MockICmsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICmsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICmsRepository {
	mock := &MockICmsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockICmsRepository is an autogenerated mock type for the ICmsRepository type
type MockICmsRepository struct {
	mock.Mock
}

type MockICmsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICmsRepository) EXPECT() *MockICmsRepository_Expecter {
	return &MockICmsRepository_Expecter{mock: &_m.Mock}
}

// CreateBlogPost provides a mock function for the type MockICmsRepository
func (_mock *MockICmsRepository) CreateBlogPost(post *models.BlogPostModel) (int64, error) {
	ret := _mock.Called(post)

	if len(ret) == 0 {
		panic("no return value specified for CreateBlogPost")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.BlogPostModel) (int64, error)); ok {
		return returnFunc(post)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.BlogPostModel) int64); ok {
		r0 = returnFunc(post)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.BlogPostModel) error); ok {
		r1 = returnFunc(post)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICmsRepository_CreateBlogPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBlogPost'
type MockICmsRepository_CreateBlogPost_Call struct {
	*mock.Call
}

// CreateBlogPost is a helper method to define mock.On call
//   - post *models.BlogPostModel
func (_e *MockICmsRepository_Expecter) CreateBlogPost(post interface{}) *MockICmsRepository_CreateBlogPost_Call {
	return &MockICmsRepository_CreateBlogPost_Call{Call: _e.mock.On("CreateBlogPost", post)}
}

func (_c *MockICmsRepository_CreateBlogPost_Call) Run(run func(post *models.BlogPostModel)) *MockICmsRepository_CreateBlogPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.BlogPostModel
		if args[0] != nil {
			arg0 = args[0].(*models.BlogPostModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICmsRepository_CreateBlogPost_Call) Return(n int64, err error) *MockICmsRepository_CreateBlogPost_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockICmsRepository_CreateBlogPost_Call) RunAndReturn(run func(post *models.BlogPostModel) (int64, error)) *MockICmsRepository_CreateBlogPost_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTeamMember provides a mock function for the type MockICmsRepository
func (_mock *MockICmsRepository) CreateTeamMember(member *models.TeamMemberModel) (int64, error) {
	ret := _mock.Called(member)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeamMember")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.TeamMemberModel) (int64, error)); ok {
		return returnFunc(member)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.TeamMemberModel) int64); ok {
		r0 = returnFunc(member)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.TeamMemberModel) error); ok {
		r1 = returnFunc(member)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICmsRepository_CreateTeamMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeamMember'
type MockICmsRepository_CreateTeamMember_Call struct {
	*mock.Call
}

// CreateTeamMember is a helper method to define mock.On call
//   - member *models.TeamMemberModel
func (_e *MockICmsRepository_Expecter) CreateTeamMember(member interface{}) *MockICmsRepository_CreateTeamMember_Call {
	return &MockICmsRepository_CreateTeamMember_Call{Call: _e.mock.On("CreateTeamMember", member)}
}

func (_c *MockICmsRepository_CreateTeamMember_Call) Run(run func(member *models.TeamMemberModel)) *MockICmsRepository_CreateTeamMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.TeamMemberModel
		if args[0] != nil {
			arg0 = args[0].(*models.TeamMemberModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICmsRepository_CreateTeamMember_Call) Return(n int64, err error) *MockICmsRepository_CreateTeamMember_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockICmsRepository_CreateTeamMember_Call) RunAndReturn(run func(member *models.TeamMemberModel) (int64, error)) *MockICmsRepository_CreateTeamMember_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBlogPost provides a mock function for the type MockICmsRepository
func (_mock *MockICmsRepository) DeleteBlogPost(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlogPost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockICmsRepository_DeleteBlogPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBlogPost'
type MockICmsRepository_DeleteBlogPost_Call struct {
	*mock.Call
}

// DeleteBlogPost is a helper method to define mock.On call
//   - id int64
func (_e *MockICmsRepository_Expecter) DeleteBlogPost(id interface{}) *MockICmsRepository_DeleteBlogPost_Call {
	return &MockICmsRepository_DeleteBlogPost_Call{Call: _e.mock.On("DeleteBlogPost", id)}
}

func (_c *MockICmsRepository_DeleteBlogPost_Call) Run(run func(id int64)) *MockICmsRepository_DeleteBlogPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICmsRepository_DeleteBlogPost_Call) Return(err error) *MockICmsRepository_DeleteBlogPost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockICmsRepository_DeleteBlogPost_Call) RunAndReturn(run func(id int64) error) *MockICmsRepository_DeleteBlogPost_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTeamMember provides a mock function for the type MockICmsRepository
func (_mock *MockICmsRepository) DeleteTeamMember(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTeamMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockICmsRepository_DeleteTeamMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTeamMember'
type MockICmsRepository_DeleteTeamMember_Call struct {
	*mock.Call
}

// DeleteTeamMember is a helper method to define mock.On call
//   - id int64
func (_e *MockICmsRepository_Expecter) DeleteTeamMember(id interface{}) *MockICmsRepository_DeleteTeamMember_Call {
	return &MockICmsRepository_DeleteTeamMember_Call{Call: _e.mock.On("DeleteTeamMember", id)}
}

func (_c *MockICmsRepository_DeleteTeamMember_Call) Run(run func(id int64)) *MockICmsRepository_DeleteTeamMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICmsRepository_DeleteTeamMember_Call) Return(err error) *MockICmsRepository_DeleteTeamMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockICmsRepository_DeleteTeamMember_Call) RunAndReturn(run func(id int64) error) *MockICmsRepository_DeleteTeamMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllBlogPosts provides a mock function for the type MockICmsRepository
func (_mock *MockICmsRepository) GetAllBlogPosts(publishedOnly bool) ([]models.BlogPostModel, error) {
	ret := _mock.Called(publishedOnly)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBlogPosts")
	}

	var r0 []models.BlogPostModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(bool) ([]models.BlogPostModel, error)); ok {
		return returnFunc(publishedOnly)
	}
	if returnFunc, ok := ret.Get(0).(func(bool) []models.BlogPostModel); ok {
		r0 = returnFunc(publishedOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.BlogPostModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(bool) error); ok {
		r1 = returnFunc(publishedOnly)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICmsRepository_GetAllBlogPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllBlogPosts'
type MockICmsRepository_GetAllBlogPosts_Call struct {
	*mock.Call
}

// GetAllBlogPosts is a helper method to define mock.On call
//   - publishedOnly bool
func (_e *MockICmsRepository_Expecter) GetAllBlogPosts(publishedOnly interface{}) *MockICmsRepository_GetAllBlogPosts_Call {
	return &MockICmsRepository_GetAllBlogPosts_Call{Call: _e.mock.On("GetAllBlogPosts", publishedOnly)}
}

func (_c *MockICmsRepository_GetAllBlogPosts_Call) Run(run func(publishedOnly bool)) *MockICmsRepository_GetAllBlogPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICmsRepository_GetAllBlogPosts_Call) Return(blogPostModels []models.BlogPostModel, err error) *MockICmsRepository_GetAllBlogPosts_Call {
	_c.Call.Return(blogPostModels, err)
	return _c
}

func (_c *MockICmsRepository_GetAllBlogPosts_Call) RunAndReturn(run func(publishedOnly bool) ([]models.BlogPostModel, error)) *MockICmsRepository_GetAllBlogPosts_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTeamMembers provides a mock function for the type MockICmsRepository
func (_mock *MockICmsRepository) GetAllTeamMembers(activeOnly bool) ([]models.TeamMemberModel, error) {
	ret := _mock.Called(activeOnly)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTeamMembers")
	}

	var r0 []models.TeamMemberModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(bool) ([]models.TeamMemberModel, error)); ok {
		return returnFunc(activeOnly)
	}
	if returnFunc, ok := ret.Get(0).(func(bool) []models.TeamMemberModel); ok {
		r0 = returnFunc(activeOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TeamMemberModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(bool) error); ok {
		r1 = returnFunc(activeOnly)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICmsRepository_GetAllTeamMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTeamMembers'
type MockICmsRepository_GetAllTeamMembers_Call struct {
	*mock.Call
}

// GetAllTeamMembers is a helper method to define mock.On call
//   - activeOnly bool
func (_e *MockICmsRepository_Expecter) GetAllTeamMembers(activeOnly interface{}) *MockICmsRepository_GetAllTeamMembers_Call {
	return &MockICmsRepository_GetAllTeamMembers_Call{Call: _e.mock.On("GetAllTeamMembers", activeOnly)}
}

func (_c *MockICmsRepository_GetAllTeamMembers_Call) Run(run func(activeOnly bool)) *MockICmsRepository_GetAllTeamMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICmsRepository_GetAllTeamMembers_Call) Return(teamMemberModels []models.TeamMemberModel, err error) *MockICmsRepository_GetAllTeamMembers_Call {
	_c.Call.Return(teamMemberModels, err)
	return _c
}

func (_c *MockICmsRepository_GetAllTeamMembers_Call) RunAndReturn(run func(activeOnly bool) ([]models.TeamMemberModel, error)) *MockICmsRepository_GetAllTeamMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlogPostByID provides a mock function for the type MockICmsRepository
func (_mock *MockICmsRepository) GetBlogPostByID(id int64) (*models.BlogPostModel, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetBlogPostByID")
	}

	var r0 *models.BlogPostModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*models.BlogPostModel, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *models.BlogPostModel); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BlogPostModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICmsRepository_GetBlogPostByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlogPostByID'
type MockICmsRepository_GetBlogPostByID_Call struct {
	*mock.Call
}

// GetBlogPostByID is a helper method to define mock.On call
//   - id int64
func (_e *MockICmsRepository_Expecter) GetBlogPostByID(id interface{}) *MockICmsRepository_GetBlogPostByID_Call {
	return &MockICmsRepository_GetBlogPostByID_Call{Call: _e.mock.On("GetBlogPostByID", id)}
}

func (_c *MockICmsRepository_GetBlogPostByID_Call) Run(run func(id int64)) *MockICmsRepository_GetBlogPostByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICmsRepository_GetBlogPostByID_Call) Return(blogPostModel *models.BlogPostModel, err error) *MockICmsRepository_GetBlogPostByID_Call {
	_c.Call.Return(blogPostModel, err)
	return _c
}

func (_c *MockICmsRepository_GetBlogPostByID_Call) RunAndReturn(run func(id int64) (*models.BlogPostModel, error)) *MockICmsRepository_GetBlogPostByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlogPostBySlug provides a mock function for the type MockICmsRepository
func (_mock *MockICmsRepository) GetBlogPostBySlug(slug string) (*models.BlogPostModel, error) {
	ret := _mock.Called(slug)

	if len(ret) == 0 {
		panic("no return value specified for GetBlogPostBySlug")
	}

	var r0 *models.BlogPostModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.BlogPostModel, error)); ok {
		return returnFunc(slug)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.BlogPostModel); ok {
		r0 = returnFunc(slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BlogPostModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICmsRepository_GetBlogPostBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlogPostBySlug'
type MockICmsRepository_GetBlogPostBySlug_Call struct {
	*mock.Call
}

// GetBlogPostBySlug is a helper method to define mock.On call
//   - slug string
func (_e *MockICmsRepository_Expecter) GetBlogPostBySlug(slug interface{}) *MockICmsRepository_GetBlogPostBySlug_Call {
	return &MockICmsRepository_GetBlogPostBySlug_Call{Call: _e.mock.On("GetBlogPostBySlug", slug)}
}

func (_c *MockICmsRepository_GetBlogPostBySlug_Call) Run(run func(slug string)) *MockICmsRepository_GetBlogPostBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICmsRepository_GetBlogPostBySlug_Call) Return(blogPostModel *models.BlogPostModel, err error) *MockICmsRepository_GetBlogPostBySlug_Call {
	_c.Call.Return(blogPostModel, err)
	return _c
}

func (_c *MockICmsRepository_GetBlogPostBySlug_Call) RunAndReturn(run func(slug string) (*models.BlogPostModel, error)) *MockICmsRepository_GetBlogPostBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamMemberByID provides a mock function for the type MockICmsRepository
func (_mock *MockICmsRepository) GetTeamMemberByID(id int64) (*models.TeamMemberModel, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamMemberByID")
	}

	var r0 *models.TeamMemberModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*models.TeamMemberModel, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *models.TeamMemberModel); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TeamMemberModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICmsRepository_GetTeamMemberByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamMemberByID'
type MockICmsRepository_GetTeamMemberByID_Call struct {
	*mock.Call
}

// GetTeamMemberByID is a helper method to define mock.On call
//   - id int64
func (_e *MockICmsRepository_Expecter) GetTeamMemberByID(id interface{}) *MockICmsRepository_GetTeamMemberByID_Call {
	return &MockICmsRepository_GetTeamMemberByID_Call{Call: _e.mock.On("GetTeamMemberByID", id)}
}

func (_c *MockICmsRepository_GetTeamMemberByID_Call) Run(run func(id int64)) *MockICmsRepository_GetTeamMemberByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICmsRepository_GetTeamMemberByID_Call) Return(teamMemberModel *models.TeamMemberModel, err error) *MockICmsRepository_GetTeamMemberByID_Call {
	_c.Call.Return(teamMemberModel, err)
	return _c
}

func (_c *MockICmsRepository_GetTeamMemberByID_Call) RunAndReturn(run func(id int64) (*models.TeamMemberModel, error)) *MockICmsRepository_GetTeamMemberByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamMemberByUserID provides a mock function for the type MockICmsRepository
func (_mock *MockICmsRepository) GetTeamMemberByUserID(userID int64) (*models.TeamMemberModel, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamMemberByUserID")
	}

	var r0 *models.TeamMemberModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*models.TeamMemberModel, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *models.TeamMemberModel); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TeamMemberModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICmsRepository_GetTeamMemberByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamMemberByUserID'
type MockICmsRepository_GetTeamMemberByUserID_Call struct {
	*mock.Call
}

// GetTeamMemberByUserID is a helper method to define mock.On call
//   - userID int64
func (_e *MockICmsRepository_Expecter) GetTeamMemberByUserID(userID interface{}) *MockICmsRepository_GetTeamMemberByUserID_Call {
	return &MockICmsRepository_GetTeamMemberByUserID_Call{Call: _e.mock.On("GetTeamMemberByUserID", userID)}
}

func (_c *MockICmsRepository_GetTeamMemberByUserID_Call) Run(run func(userID int64)) *MockICmsRepository_GetTeamMemberByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICmsRepository_GetTeamMemberByUserID_Call) Return(teamMemberModel *models.TeamMemberModel, err error) *MockICmsRepository_GetTeamMemberByUserID_Call {
	_c.Call.Return(teamMemberModel, err)
	return _c
}

func (_c *MockICmsRepository_GetTeamMemberByUserID_Call) RunAndReturn(run func(userID int64) (*models.TeamMemberModel, error)) *MockICmsRepository_GetTeamMemberByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBlogPost provides a mock function for the type MockICmsRepository
func (_mock *MockICmsRepository) UpdateBlogPost(post *models.BlogPostModel) error {
	ret := _mock.Called(post)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBlogPost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.BlogPostModel) error); ok {
		r0 = returnFunc(post)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockICmsRepository_UpdateBlogPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBlogPost'
type MockICmsRepository_UpdateBlogPost_Call struct {
	*mock.Call
}

// UpdateBlogPost is a helper method to define mock.On call
//   - post *models.BlogPostModel
func (_e *MockICmsRepository_Expecter) UpdateBlogPost(post interface{}) *MockICmsRepository_UpdateBlogPost_Call {
	return &MockICmsRepository_UpdateBlogPost_Call{Call: _e.mock.On("UpdateBlogPost", post)}
}

func (_c *MockICmsRepository_UpdateBlogPost_Call) Run(run func(post *models.BlogPostModel)) *MockICmsRepository_UpdateBlogPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.BlogPostModel
		if args[0] != nil {
			arg0 = args[0].(*models.BlogPostModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICmsRepository_UpdateBlogPost_Call) Return(err error) *MockICmsRepository_UpdateBlogPost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockICmsRepository_UpdateBlogPost_Call) RunAndReturn(run func(post *models.BlogPostModel) error) *MockICmsRepository_UpdateBlogPost_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTeamMember provides a mock function for the type MockICmsRepository
func (_mock *MockICmsRepository) UpdateTeamMember(member *models.TeamMemberModel) error {
	ret := _mock.Called(member)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTeamMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.TeamMemberModel) error); ok {
		r0 = returnFunc(member)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockICmsRepository_UpdateTeamMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTeamMember'
type MockICmsRepository_UpdateTeamMember_Call struct {
	*mock.Call
}

// UpdateTeamMember is a helper method to define mock.On call
//   - member *models.TeamMemberModel
func (_e *MockICmsRepository_Expecter) UpdateTeamMember(member interface{}) *MockICmsRepository_UpdateTeamMember_Call {
	return &MockICmsRepository_UpdateTeamMember_Call{Call: _e.mock.On("UpdateTeamMember", member)}
}

func (_c *MockICmsRepository_UpdateTeamMember_Call) Run(run func(member *models.TeamMemberModel)) *MockICmsRepository_UpdateTeamMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.TeamMemberModel
		if args[0] != nil {
			arg0 = args[0].(*models.TeamMemberModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockICmsRepository_UpdateTeamMember_Call) Return(err error) *MockICmsRepository_UpdateTeamMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockICmsRepository_UpdateTeamMember_Call) RunAndReturn(run func(member *models.TeamMemberModel) error) *MockICmsRepository_UpdateTeamMember_Call {
	_c.Call.Return(run)
	return _c
}
