// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"sea-api/internal/models"

	"github.com/jmoiron/sqlx"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIUserRepository creates a new instance of MockIUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUserRepository {
	mock := &MockIUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUserRepository is an autogenerated mock type for the IUserRepository type
type MockIUserRepository struct {
	mock.Mock
}

type MockIUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUserRepository) EXPECT() *MockIUserRepository_Expecter {
	return &MockIUserRepository_Expecter{mock: &_m.Mock}
}

// Activate provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) Activate(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_Activate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activate'
type MockIUserRepository_Activate_Call struct {
	*mock.Call
}

// Activate is a helper method to define mock.On call
//   - id int64
func (_e *MockIUserRepository_Expecter) Activate(id interface{}) *MockIUserRepository_Activate_Call {
	return &MockIUserRepository_Activate_Call{Call: _e.mock.On("Activate", id)}
}

func (_c *MockIUserRepository_Activate_Call) Run(run func(id int64)) *MockIUserRepository_Activate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserRepository_Activate_Call) Return(err error) *MockIUserRepository_Activate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_Activate_Call) RunAndReturn(run func(id int64) error) *MockIUserRepository_Activate_Call {
	_c.Call.Return(run)
	return _c
}

// AddAdmin provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) AddAdmin(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for AddAdmin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_AddAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAdmin'
type MockIUserRepository_AddAdmin_Call struct {
	*mock.Call
}

// AddAdmin is a helper method to define mock.On call
//   - id int64
func (_e *MockIUserRepository_Expecter) AddAdmin(id interface{}) *MockIUserRepository_AddAdmin_Call {
	return &MockIUserRepository_AddAdmin_Call{Call: _e.mock.On("AddAdmin", id)}
}

func (_c *MockIUserRepository_AddAdmin_Call) Run(run func(id int64)) *MockIUserRepository_AddAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserRepository_AddAdmin_Call) Return(err error) *MockIUserRepository_AddAdmin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_AddAdmin_Call) RunAndReturn(run func(id int64) error) *MockIUserRepository_AddAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) Create(user *models.UserModel, tx *sqlx.Tx) error {
	ret := _mock.Called(user, tx)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.UserModel, *sqlx.Tx) error); ok {
		r0 = returnFunc(user, tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - user *models.UserModel
//   - tx *sqlx.Tx
func (_e *MockIUserRepository_Expecter) Create(user interface{}, tx interface{}) *MockIUserRepository_Create_Call {
	return &MockIUserRepository_Create_Call{Call: _e.mock.On("Create", user, tx)}
}

func (_c *MockIUserRepository_Create_Call) Run(run func(user *models.UserModel, tx *sqlx.Tx)) *MockIUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.UserModel
		if args[0] != nil {
			arg0 = args[0].(*models.UserModel)
		}
		var arg1 *sqlx.Tx
		if args[1] != nil {
			arg1 = args[1].(*sqlx.Tx)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_Create_Call) Return(err error) *MockIUserRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_Create_Call) RunAndReturn(run func(user *models.UserModel, tx *sqlx.Tx) error) *MockIUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRole provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) CreateRole(role *models.UserRole) error {
	ret := _mock.Called(role)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.UserRole) error); ok {
		r0 = returnFunc(role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_CreateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRole'
type MockIUserRepository_CreateRole_Call struct {
	*mock.Call
}

// CreateRole is a helper method to define mock.On call
//   - role *models.UserRole
func (_e *MockIUserRepository_Expecter) CreateRole(role interface{}) *MockIUserRepository_CreateRole_Call {
	return &MockIUserRepository_CreateRole_Call{Call: _e.mock.On("CreateRole", role)}
}

func (_c *MockIUserRepository_CreateRole_Call) Run(run func(role *models.UserRole)) *MockIUserRepository_CreateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.UserRole
		if args[0] != nil {
			arg0 = args[0].(*models.UserRole)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserRepository_CreateRole_Call) Return(err error) *MockIUserRepository_CreateRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_CreateRole_Call) RunAndReturn(run func(role *models.UserRole) error) *MockIUserRepository_CreateRole_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) Delete(id int64, tx *sqlx.Tx) error {
	ret := _mock.Called(id, tx)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, *sqlx.Tx) error); ok {
		r0 = returnFunc(id, tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIUserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int64
//   - tx *sqlx.Tx
func (_e *MockIUserRepository_Expecter) Delete(id interface{}, tx interface{}) *MockIUserRepository_Delete_Call {
	return &MockIUserRepository_Delete_Call{Call: _e.mock.On("Delete", id, tx)}
}

func (_c *MockIUserRepository_Delete_Call) Run(run func(id int64, tx *sqlx.Tx)) *MockIUserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 *sqlx.Tx
		if args[1] != nil {
			arg1 = args[1].(*sqlx.Tx)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_Delete_Call) Return(err error) *MockIUserRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_Delete_Call) RunAndReturn(run func(id int64, tx *sqlx.Tx) error) *MockIUserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRole provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) DeleteRole(id int64, role models.Role, tx *sqlx.Tx) error {
	ret := _mock.Called(id, role, tx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, models.Role, *sqlx.Tx) error); ok {
		r0 = returnFunc(id, role, tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_DeleteRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRole'
type MockIUserRepository_DeleteRole_Call struct {
	*mock.Call
}

// DeleteRole is a helper method to define mock.On call
//   - id int64
//   - role models.Role
//   - tx *sqlx.Tx
func (_e *MockIUserRepository_Expecter) DeleteRole(id interface{}, role interface{}, tx interface{}) *MockIUserRepository_DeleteRole_Call {
	return &MockIUserRepository_DeleteRole_Call{Call: _e.mock.On("DeleteRole", id, role, tx)}
}

func (_c *MockIUserRepository_DeleteRole_Call) Run(run func(id int64, role models.Role, tx *sqlx.Tx)) *MockIUserRepository_DeleteRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 models.Role
		if args[1] != nil {
			arg1 = args[1].(models.Role)
		}
		var arg2 *sqlx.Tx
		if args[2] != nil {
			arg2 = args[2].(*sqlx.Tx)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIUserRepository_DeleteRole_Call) Return(err error) *MockIUserRepository_DeleteRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_DeleteRole_Call) RunAndReturn(run func(id int64, role models.Role, tx *sqlx.Tx) error) *MockIUserRepository_DeleteRole_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRolesByUserID provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) DeleteRolesByUserID(id int64, tx *sqlx.Tx) error {
	ret := _mock.Called(id, tx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRolesByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, *sqlx.Tx) error); ok {
		r0 = returnFunc(id, tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_DeleteRolesByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRolesByUserID'
type MockIUserRepository_DeleteRolesByUserID_Call struct {
	*mock.Call
}

// DeleteRolesByUserID is a helper method to define mock.On call
//   - id int64
//   - tx *sqlx.Tx
func (_e *MockIUserRepository_Expecter) DeleteRolesByUserID(id interface{}, tx interface{}) *MockIUserRepository_DeleteRolesByUserID_Call {
	return &MockIUserRepository_DeleteRolesByUserID_Call{Call: _e.mock.On("DeleteRolesByUserID", id, tx)}
}

func (_c *MockIUserRepository_DeleteRolesByUserID_Call) Run(run func(id int64, tx *sqlx.Tx)) *MockIUserRepository_DeleteRolesByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 *sqlx.Tx
		if args[1] != nil {
			arg1 = args[1].(*sqlx.Tx)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_DeleteRolesByUserID_Call) Return(err error) *MockIUserRepository_DeleteRolesByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_DeleteRolesByUserID_Call) RunAndReturn(run func(id int64, tx *sqlx.Tx) error) *MockIUserRepository_DeleteRolesByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTempUser provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) DeleteTempUser(id int64, tx *sqlx.Tx) error {
	ret := _mock.Called(id, tx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTempUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, *sqlx.Tx) error); ok {
		r0 = returnFunc(id, tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_DeleteTempUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTempUser'
type MockIUserRepository_DeleteTempUser_Call struct {
	*mock.Call
}

// DeleteTempUser is a helper method to define mock.On call
//   - id int64
//   - tx *sqlx.Tx
func (_e *MockIUserRepository_Expecter) DeleteTempUser(id interface{}, tx interface{}) *MockIUserRepository_DeleteTempUser_Call {
	return &MockIUserRepository_DeleteTempUser_Call{Call: _e.mock.On("DeleteTempUser", id, tx)}
}

func (_c *MockIUserRepository_DeleteTempUser_Call) Run(run func(id int64, tx *sqlx.Tx)) *MockIUserRepository_DeleteTempUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 *sqlx.Tx
		if args[1] != nil {
			arg1 = args[1].(*sqlx.Tx)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_DeleteTempUser_Call) Return(err error) *MockIUserRepository_DeleteTempUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_DeleteTempUser_Call) RunAndReturn(run func(id int64, tx *sqlx.Tx) error) *MockIUserRepository_DeleteTempUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAdmins provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) GetAdmins() ([]models.UserModel, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAdmins")
	}

	var r0 []models.UserModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.UserModel, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.UserModel); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_GetAdmins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAdmins'
type MockIUserRepository_GetAdmins_Call struct {
	*mock.Call
}

// GetAdmins is a helper method to define mock.On call
func (_e *MockIUserRepository_Expecter) GetAdmins() *MockIUserRepository_GetAdmins_Call {
	return &MockIUserRepository_GetAdmins_Call{Call: _e.mock.On("GetAdmins")}
}

func (_c *MockIUserRepository_GetAdmins_Call) Run(run func()) *MockIUserRepository_GetAdmins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIUserRepository_GetAdmins_Call) Return(userModels []models.UserModel, err error) *MockIUserRepository_GetAdmins_Call {
	_c.Call.Return(userModels, err)
	return _c
}

func (_c *MockIUserRepository_GetAdmins_Call) RunAndReturn(run func() ([]models.UserModel, error)) *MockIUserRepository_GetAdmins_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) GetAll(limit int, page int) ([]models.UserModel, error) {
	ret := _mock.Called(limit, page)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.UserModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]models.UserModel, error)); ok {
		return returnFunc(limit, page)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []models.UserModel); ok {
		r0 = returnFunc(limit, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = returnFunc(limit, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockIUserRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - limit int
//   - page int
func (_e *MockIUserRepository_Expecter) GetAll(limit interface{}, page interface{}) *MockIUserRepository_GetAll_Call {
	return &MockIUserRepository_GetAll_Call{Call: _e.mock.On("GetAll", limit, page)}
}

func (_c *MockIUserRepository_GetAll_Call) Run(run func(limit int, page int)) *MockIUserRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_GetAll_Call) Return(userModels []models.UserModel, err error) *MockIUserRepository_GetAll_Call {
	_c.Call.Return(userModels, err)
	return _c
}

func (_c *MockIUserRepository_GetAll_Call) RunAndReturn(run func(limit int, page int) ([]models.UserModel, error)) *MockIUserRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByIndices provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) GetAllByIndices(indices []int64) ([]models.UserModel, error) {
	ret := _mock.Called(indices)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByIndices")
	}

	var r0 []models.UserModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]int64) ([]models.UserModel, error)); ok {
		return returnFunc(indices)
	}
	if returnFunc, ok := ret.Get(0).(func([]int64) []models.UserModel); ok {
		r0 = returnFunc(indices)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]int64) error); ok {
		r1 = returnFunc(indices)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_GetAllByIndices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByIndices'
type MockIUserRepository_GetAllByIndices_Call struct {
	*mock.Call
}

// GetAllByIndices is a helper method to define mock.On call
//   - indices []int64
func (_e *MockIUserRepository_Expecter) GetAllByIndices(indices interface{}) *MockIUserRepository_GetAllByIndices_Call {
	return &MockIUserRepository_GetAllByIndices_Call{Call: _e.mock.On("GetAllByIndices", indices)}
}

func (_c *MockIUserRepository_GetAllByIndices_Call) Run(run func(indices []int64)) *MockIUserRepository_GetAllByIndices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []int64
		if args[0] != nil {
			arg0 = args[0].([]int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserRepository_GetAllByIndices_Call) Return(userModels []models.UserModel, err error) *MockIUserRepository_GetAllByIndices_Call {
	_c.Call.Return(userModels, err)
	return _c
}

func (_c *MockIUserRepository_GetAllByIndices_Call) RunAndReturn(run func(indices []int64) ([]models.UserModel, error)) *MockIUserRepository_GetAllByIndices_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllRolesByUserIDs provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) GetAllRolesByUserIDs(ids []int64) ([]models.UserRole, error) {
	ret := _mock.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for GetAllRolesByUserIDs")
	}

	var r0 []models.UserRole
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]int64) ([]models.UserRole, error)); ok {
		return returnFunc(ids)
	}
	if returnFunc, ok := ret.Get(0).(func([]int64) []models.UserRole); ok {
		r0 = returnFunc(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserRole)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]int64) error); ok {
		r1 = returnFunc(ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_GetAllRolesByUserIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllRolesByUserIDs'
type MockIUserRepository_GetAllRolesByUserIDs_Call struct {
	*mock.Call
}

// GetAllRolesByUserIDs is a helper method to define mock.On call
//   - ids []int64
func (_e *MockIUserRepository_Expecter) GetAllRolesByUserIDs(ids interface{}) *MockIUserRepository_GetAllRolesByUserIDs_Call {
	return &MockIUserRepository_GetAllRolesByUserIDs_Call{Call: _e.mock.On("GetAllRolesByUserIDs", ids)}
}

func (_c *MockIUserRepository_GetAllRolesByUserIDs_Call) Run(run func(ids []int64)) *MockIUserRepository_GetAllRolesByUserIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []int64
		if args[0] != nil {
			arg0 = args[0].([]int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserRepository_GetAllRolesByUserIDs_Call) Return(userRoles []models.UserRole, err error) *MockIUserRepository_GetAllRolesByUserIDs_Call {
	_c.Call.Return(userRoles, err)
	return _c
}

func (_c *MockIUserRepository_GetAllRolesByUserIDs_Call) RunAndReturn(run func(ids []int64) ([]models.UserRole, error)) *MockIUserRepository_GetAllRolesByUserIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTempUsers provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) GetAllTempUsers(limit int, page int) ([]models.TempUserModel, error) {
	ret := _mock.Called(limit, page)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTempUsers")
	}

	var r0 []models.TempUserModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]models.TempUserModel, error)); ok {
		return returnFunc(limit, page)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []models.TempUserModel); ok {
		r0 = returnFunc(limit, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TempUserModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = returnFunc(limit, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_GetAllTempUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTempUsers'
type MockIUserRepository_GetAllTempUsers_Call struct {
	*mock.Call
}

// GetAllTempUsers is a helper method to define mock.On call
//   - limit int
//   - page int
func (_e *MockIUserRepository_Expecter) GetAllTempUsers(limit interface{}, page interface{}) *MockIUserRepository_GetAllTempUsers_Call {
	return &MockIUserRepository_GetAllTempUsers_Call{Call: _e.mock.On("GetAllTempUsers", limit, page)}
}

func (_c *MockIUserRepository_GetAllTempUsers_Call) Run(run func(limit int, page int)) *MockIUserRepository_GetAllTempUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_GetAllTempUsers_Call) Return(tempUserModels []models.TempUserModel, err error) *MockIUserRepository_GetAllTempUsers_Call {
	_c.Call.Return(tempUserModels, err)
	return _c
}

func (_c *MockIUserRepository_GetAllTempUsers_Call) RunAndReturn(run func(limit int, page int) ([]models.TempUserModel, error)) *MockIUserRepository_GetAllTempUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) GetByEmail(email string) (*models.UserModel, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *models.UserModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.UserModel, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.UserModel); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockIUserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockIUserRepository_Expecter) GetByEmail(email interface{}) *MockIUserRepository_GetByEmail_Call {
	return &MockIUserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", email)}
}

func (_c *MockIUserRepository_GetByEmail_Call) Run(run func(email string)) *MockIUserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserRepository_GetByEmail_Call) Return(userModel *models.UserModel, err error) *MockIUserRepository_GetByEmail_Call {
	_c.Call.Return(userModel, err)
	return _c
}

func (_c *MockIUserRepository_GetByEmail_Call) RunAndReturn(run func(email string) (*models.UserModel, error)) *MockIUserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUniID provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) GetByUniID(uniID int64) (*models.UserModel, error) {
	ret := _mock.Called(uniID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUniID")
	}

	var r0 *models.UserModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*models.UserModel, error)); ok {
		return returnFunc(uniID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *models.UserModel); ok {
		r0 = returnFunc(uniID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(uniID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_GetByUniID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUniID'
type MockIUserRepository_GetByUniID_Call struct {
	*mock.Call
}

// GetByUniID is a helper method to define mock.On call
//   - uniID int64
func (_e *MockIUserRepository_Expecter) GetByUniID(uniID interface{}) *MockIUserRepository_GetByUniID_Call {
	return &MockIUserRepository_GetByUniID_Call{Call: _e.mock.On("GetByUniID", uniID)}
}

func (_c *MockIUserRepository_GetByUniID_Call) Run(run func(uniID int64)) *MockIUserRepository_GetByUniID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserRepository_GetByUniID_Call) Return(userModel *models.UserModel, err error) *MockIUserRepository_GetByUniID_Call {
	_c.Call.Return(userModel, err)
	return _c
}

func (_c *MockIUserRepository_GetByUniID_Call) RunAndReturn(run func(uniID int64) (*models.UserModel, error)) *MockIUserRepository_GetByUniID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) GetByUserID(id int64) (*models.UserModel, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *models.UserModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*models.UserModel, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *models.UserModel); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockIUserRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - id int64
func (_e *MockIUserRepository_Expecter) GetByUserID(id interface{}) *MockIUserRepository_GetByUserID_Call {
	return &MockIUserRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", id)}
}

func (_c *MockIUserRepository_GetByUserID_Call) Run(run func(id int64)) *MockIUserRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserRepository_GetByUserID_Call) Return(userModel *models.UserModel, err error) *MockIUserRepository_GetByUserID_Call {
	_c.Call.Return(userModel, err)
	return _c
}

func (_c *MockIUserRepository_GetByUserID_Call) RunAndReturn(run func(id int64) (*models.UserModel, error)) *MockIUserRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsername provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) GetByUsername(username string) (*models.UserModel, error) {
	ret := _mock.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 *models.UserModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.UserModel, error)); ok {
		return returnFunc(username)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.UserModel); ok {
		r0 = returnFunc(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type MockIUserRepository_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - username string
func (_e *MockIUserRepository_Expecter) GetByUsername(username interface{}) *MockIUserRepository_GetByUsername_Call {
	return &MockIUserRepository_GetByUsername_Call{Call: _e.mock.On("GetByUsername", username)}
}

func (_c *MockIUserRepository_GetByUsername_Call) Run(run func(username string)) *MockIUserRepository_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserRepository_GetByUsername_Call) Return(userModel *models.UserModel, err error) *MockIUserRepository_GetByUsername_Call {
	_c.Call.Return(userModel, err)
	return _c
}

func (_c *MockIUserRepository_GetByUsername_Call) RunAndReturn(run func(username string) (*models.UserModel, error)) *MockIUserRepository_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetPagesCount provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) GetPagesCount(limit int, isTempUser bool) (int, error) {
	ret := _mock.Called(limit, isTempUser)

	if len(ret) == 0 {
		panic("no return value specified for GetPagesCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, bool) (int, error)); ok {
		return returnFunc(limit, isTempUser)
	}
	if returnFunc, ok := ret.Get(0).(func(int, bool) int); ok {
		r0 = returnFunc(limit, isTempUser)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(int, bool) error); ok {
		r1 = returnFunc(limit, isTempUser)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_GetPagesCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPagesCount'
type MockIUserRepository_GetPagesCount_Call struct {
	*mock.Call
}

// GetPagesCount is a helper method to define mock.On call
//   - limit int
//   - isTempUser bool
func (_e *MockIUserRepository_Expecter) GetPagesCount(limit interface{}, isTempUser interface{}) *MockIUserRepository_GetPagesCount_Call {
	return &MockIUserRepository_GetPagesCount_Call{Call: _e.mock.On("GetPagesCount", limit, isTempUser)}
}

func (_c *MockIUserRepository_GetPagesCount_Call) Run(run func(limit int, isTempUser bool)) *MockIUserRepository_GetPagesCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_GetPagesCount_Call) Return(n int, err error) *MockIUserRepository_GetPagesCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIUserRepository_GetPagesCount_Call) RunAndReturn(run func(limit int, isTempUser bool) (int, error)) *MockIUserRepository_GetPagesCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetRolesByUserID provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) GetRolesByUserID(id int64) ([]models.UserRole, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetRolesByUserID")
	}

	var r0 []models.UserRole
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) ([]models.UserRole, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) []models.UserRole); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserRole)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_GetRolesByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRolesByUserID'
type MockIUserRepository_GetRolesByUserID_Call struct {
	*mock.Call
}

// GetRolesByUserID is a helper method to define mock.On call
//   - id int64
func (_e *MockIUserRepository_Expecter) GetRolesByUserID(id interface{}) *MockIUserRepository_GetRolesByUserID_Call {
	return &MockIUserRepository_GetRolesByUserID_Call{Call: _e.mock.On("GetRolesByUserID", id)}
}

func (_c *MockIUserRepository_GetRolesByUserID_Call) Run(run func(id int64)) *MockIUserRepository_GetRolesByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserRepository_GetRolesByUserID_Call) Return(userRoles []models.UserRole, err error) *MockIUserRepository_GetRolesByUserID_Call {
	_c.Call.Return(userRoles, err)
	return _c
}

func (_c *MockIUserRepository_GetRolesByUserID_Call) RunAndReturn(run func(id int64) ([]models.UserRole, error)) *MockIUserRepository_GetRolesByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTempUser provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) GetTempUser(id int64) (*models.TempUserModel, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTempUser")
	}

	var r0 *models.TempUserModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*models.TempUserModel, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *models.TempUserModel); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TempUserModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_GetTempUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTempUser'
type MockIUserRepository_GetTempUser_Call struct {
	*mock.Call
}

// GetTempUser is a helper method to define mock.On call
//   - id int64
func (_e *MockIUserRepository_Expecter) GetTempUser(id interface{}) *MockIUserRepository_GetTempUser_Call {
	return &MockIUserRepository_GetTempUser_Call{Call: _e.mock.On("GetTempUser", id)}
}

func (_c *MockIUserRepository_GetTempUser_Call) Run(run func(id int64)) *MockIUserRepository_GetTempUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserRepository_GetTempUser_Call) Return(tempUserModel *models.TempUserModel, err error) *MockIUserRepository_GetTempUser_Call {
	_c.Call.Return(tempUserModel, err)
	return _c
}

func (_c *MockIUserRepository_GetTempUser_Call) RunAndReturn(run func(id int64) (*models.TempUserModel, error)) *MockIUserRepository_GetTempUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetTempUsersWithNullPasswords provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) GetTempUsersWithNullPasswords() ([]models.TempUserModel, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTempUsersWithNullPasswords")
	}

	var r0 []models.TempUserModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.TempUserModel, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.TempUserModel); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TempUserModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_GetTempUsersWithNullPasswords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTempUsersWithNullPasswords'
type MockIUserRepository_GetTempUsersWithNullPasswords_Call struct {
	*mock.Call
}

// GetTempUsersWithNullPasswords is a helper method to define mock.On call
func (_e *MockIUserRepository_Expecter) GetTempUsersWithNullPasswords() *MockIUserRepository_GetTempUsersWithNullPasswords_Call {
	return &MockIUserRepository_GetTempUsersWithNullPasswords_Call{Call: _e.mock.On("GetTempUsersWithNullPasswords")}
}

func (_c *MockIUserRepository_GetTempUsersWithNullPasswords_Call) Run(run func()) *MockIUserRepository_GetTempUsersWithNullPasswords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIUserRepository_GetTempUsersWithNullPasswords_Call) Return(tempUserModels []models.TempUserModel, err error) *MockIUserRepository_GetTempUsersWithNullPasswords_Call {
	_c.Call.Return(tempUserModels, err)
	return _c
}

func (_c *MockIUserRepository_GetTempUsersWithNullPasswords_Call) RunAndReturn(run func() ([]models.TempUserModel, error)) *MockIUserRepository_GetTempUsersWithNullPasswords_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransaction provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) GetTransaction() (*sqlx.Tx, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTransaction")
	}

	var r0 *sqlx.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*sqlx.Tx, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *sqlx.Tx); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlx.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_GetTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransaction'
type MockIUserRepository_GetTransaction_Call struct {
	*mock.Call
}

// GetTransaction is a helper method to define mock.On call
func (_e *MockIUserRepository_Expecter) GetTransaction() *MockIUserRepository_GetTransaction_Call {
	return &MockIUserRepository_GetTransaction_Call{Call: _e.mock.On("GetTransaction")}
}

func (_c *MockIUserRepository_GetTransaction_Call) Run(run func()) *MockIUserRepository_GetTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIUserRepository_GetTransaction_Call) Return(tx *sqlx.Tx, err error) *MockIUserRepository_GetTransaction_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *MockIUserRepository_GetTransaction_Call) RunAndReturn(run func() (*sqlx.Tx, error)) *MockIUserRepository_GetTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAdmin provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) RemoveAdmin(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAdmin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_RemoveAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAdmin'
type MockIUserRepository_RemoveAdmin_Call struct {
	*mock.Call
}

// RemoveAdmin is a helper method to define mock.On call
//   - id int64
func (_e *MockIUserRepository_Expecter) RemoveAdmin(id interface{}) *MockIUserRepository_RemoveAdmin_Call {
	return &MockIUserRepository_RemoveAdmin_Call{Call: _e.mock.On("RemoveAdmin", id)}
}

func (_c *MockIUserRepository_RemoveAdmin_Call) Run(run func(id int64)) *MockIUserRepository_RemoveAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserRepository_RemoveAdmin_Call) Return(err error) *MockIUserRepository_RemoveAdmin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_RemoveAdmin_Call) RunAndReturn(run func(id int64) error) *MockIUserRepository_RemoveAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveRole provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) RemoveRole(id int64, role models.Role, tx *sqlx.Tx) error {
	ret := _mock.Called(id, role, tx)

	if len(ret) == 0 {
		panic("no return value specified for RemoveRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, models.Role, *sqlx.Tx) error); ok {
		r0 = returnFunc(id, role, tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_RemoveRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveRole'
type MockIUserRepository_RemoveRole_Call struct {
	*mock.Call
}

// RemoveRole is a helper method to define mock.On call
//   - id int64
//   - role models.Role
//   - tx *sqlx.Tx
func (_e *MockIUserRepository_Expecter) RemoveRole(id interface{}, role interface{}, tx interface{}) *MockIUserRepository_RemoveRole_Call {
	return &MockIUserRepository_RemoveRole_Call{Call: _e.mock.On("RemoveRole", id, role, tx)}
}

func (_c *MockIUserRepository_RemoveRole_Call) Run(run func(id int64, role models.Role, tx *sqlx.Tx)) *MockIUserRepository_RemoveRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 models.Role
		if args[1] != nil {
			arg1 = args[1].(models.Role)
		}
		var arg2 *sqlx.Tx
		if args[2] != nil {
			arg2 = args[2].(*sqlx.Tx)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIUserRepository_RemoveRole_Call) Return(err error) *MockIUserRepository_RemoveRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_RemoveRole_Call) RunAndReturn(run func(id int64, role models.Role, tx *sqlx.Tx) error) *MockIUserRepository_RemoveRole_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveSuspensionState provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) RemoveSuspensionState(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for RemoveSuspensionState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_RemoveSuspensionState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveSuspensionState'
type MockIUserRepository_RemoveSuspensionState_Call struct {
	*mock.Call
}

// RemoveSuspensionState is a helper method to define mock.On call
//   - id int64
func (_e *MockIUserRepository_Expecter) RemoveSuspensionState(id interface{}) *MockIUserRepository_RemoveSuspensionState_Call {
	return &MockIUserRepository_RemoveSuspensionState_Call{Call: _e.mock.On("RemoveSuspensionState", id)}
}

func (_c *MockIUserRepository_RemoveSuspensionState_Call) Run(run func(id int64)) *MockIUserRepository_RemoveSuspensionState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserRepository_RemoveSuspensionState_Call) Return(err error) *MockIUserRepository_RemoveSuspensionState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_RemoveSuspensionState_Call) RunAndReturn(run func(id int64) error) *MockIUserRepository_RemoveSuspensionState_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceRoles provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) ReplaceRoles(id int64, roles []models.Role, tx *sqlx.Tx) error {
	ret := _mock.Called(id, roles, tx)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceRoles")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, []models.Role, *sqlx.Tx) error); ok {
		r0 = returnFunc(id, roles, tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_ReplaceRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceRoles'
type MockIUserRepository_ReplaceRoles_Call struct {
	*mock.Call
}

// ReplaceRoles is a helper method to define mock.On call
//   - id int64
//   - roles []models.Role
//   - tx *sqlx.Tx
func (_e *MockIUserRepository_Expecter) ReplaceRoles(id interface{}, roles interface{}, tx interface{}) *MockIUserRepository_ReplaceRoles_Call {
	return &MockIUserRepository_ReplaceRoles_Call{Call: _e.mock.On("ReplaceRoles", id, roles, tx)}
}

func (_c *MockIUserRepository_ReplaceRoles_Call) Run(run func(id int64, roles []models.Role, tx *sqlx.Tx)) *MockIUserRepository_ReplaceRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 []models.Role
		if args[1] != nil {
			arg1 = args[1].([]models.Role)
		}
		var arg2 *sqlx.Tx
		if args[2] != nil {
			arg2 = args[2].(*sqlx.Tx)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIUserRepository_ReplaceRoles_Call) Return(err error) *MockIUserRepository_ReplaceRoles_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_ReplaceRoles_Call) RunAndReturn(run func(id int64, roles []models.Role, tx *sqlx.Tx) error) *MockIUserRepository_ReplaceRoles_Call {
	_c.Call.Return(run)
	return _c
}

// Suspend provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) Suspend(id int64, tx *sqlx.Tx) error {
	ret := _mock.Called(id, tx)

	if len(ret) == 0 {
		panic("no return value specified for Suspend")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, *sqlx.Tx) error); ok {
		r0 = returnFunc(id, tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_Suspend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Suspend'
type MockIUserRepository_Suspend_Call struct {
	*mock.Call
}

// Suspend is a helper method to define mock.On call
//   - id int64
//   - tx *sqlx.Tx
func (_e *MockIUserRepository_Expecter) Suspend(id interface{}, tx interface{}) *MockIUserRepository_Suspend_Call {
	return &MockIUserRepository_Suspend_Call{Call: _e.mock.On("Suspend", id, tx)}
}

func (_c *MockIUserRepository_Suspend_Call) Run(run func(id int64, tx *sqlx.Tx)) *MockIUserRepository_Suspend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 *sqlx.Tx
		if args[1] != nil {
			arg1 = args[1].(*sqlx.Tx)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_Suspend_Call) Return(err error) *MockIUserRepository_Suspend_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_Suspend_Call) RunAndReturn(run func(id int64, tx *sqlx.Tx) error) *MockIUserRepository_Suspend_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) Update(user *models.UserModel, tx *sqlx.Tx) error {
	ret := _mock.Called(user, tx)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.UserModel, *sqlx.Tx) error); ok {
		r0 = returnFunc(user, tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - user *models.UserModel
//   - tx *sqlx.Tx
func (_e *MockIUserRepository_Expecter) Update(user interface{}, tx interface{}) *MockIUserRepository_Update_Call {
	return &MockIUserRepository_Update_Call{Call: _e.mock.On("Update", user, tx)}
}

func (_c *MockIUserRepository_Update_Call) Run(run func(user *models.UserModel, tx *sqlx.Tx)) *MockIUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.UserModel
		if args[0] != nil {
			arg0 = args[0].(*models.UserModel)
		}
		var arg1 *sqlx.Tx
		if args[1] != nil {
			arg1 = args[1].(*sqlx.Tx)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_Update_Call) Return(err error) *MockIUserRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_Update_Call) RunAndReturn(run func(user *models.UserModel, tx *sqlx.Tx) error) *MockIUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) UpdateRole(role *models.UserRole, tx *sqlx.Tx) error {
	ret := _mock.Called(role, tx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.UserRole, *sqlx.Tx) error); ok {
		r0 = returnFunc(role, tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type MockIUserRepository_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - role *models.UserRole
//   - tx *sqlx.Tx
func (_e *MockIUserRepository_Expecter) UpdateRole(role interface{}, tx interface{}) *MockIUserRepository_UpdateRole_Call {
	return &MockIUserRepository_UpdateRole_Call{Call: _e.mock.On("UpdateRole", role, tx)}
}

func (_c *MockIUserRepository_UpdateRole_Call) Run(run func(role *models.UserRole, tx *sqlx.Tx)) *MockIUserRepository_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.UserRole
		if args[0] != nil {
			arg0 = args[0].(*models.UserRole)
		}
		var arg1 *sqlx.Tx
		if args[1] != nil {
			arg1 = args[1].(*sqlx.Tx)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_UpdateRole_Call) Return(err error) *MockIUserRepository_UpdateRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_UpdateRole_Call) RunAndReturn(run func(role *models.UserRole, tx *sqlx.Tx) error) *MockIUserRepository_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTempPasscode provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) UpdateTempPasscode(id int64, passcode string) error {
	ret := _mock.Called(id, passcode)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTempPasscode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, string) error); ok {
		r0 = returnFunc(id, passcode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_UpdateTempPasscode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTempPasscode'
type MockIUserRepository_UpdateTempPasscode_Call struct {
	*mock.Call
}

// UpdateTempPasscode is a helper method to define mock.On call
//   - id int64
//   - passcode string
func (_e *MockIUserRepository_Expecter) UpdateTempPasscode(id interface{}, passcode interface{}) *MockIUserRepository_UpdateTempPasscode_Call {
	return &MockIUserRepository_UpdateTempPasscode_Call{Call: _e.mock.On("UpdateTempPasscode", id, passcode)}
}

func (_c *MockIUserRepository_UpdateTempPasscode_Call) Run(run func(id int64, passcode string)) *MockIUserRepository_UpdateTempPasscode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_UpdateTempPasscode_Call) Return(err error) *MockIUserRepository_UpdateTempPasscode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_UpdateTempPasscode_Call) RunAndReturn(run func(id int64, passcode string) error) *MockIUserRepository_UpdateTempPasscode_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithID provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) UpdateWithID(user *models.UserModel, tx *sqlx.Tx) error {
	ret := _mock.Called(user, tx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.UserModel, *sqlx.Tx) error); ok {
		r0 = returnFunc(user, tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_UpdateWithID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithID'
type MockIUserRepository_UpdateWithID_Call struct {
	*mock.Call
}

// UpdateWithID is a helper method to define mock.On call
//   - user *models.UserModel
//   - tx *sqlx.Tx
func (_e *MockIUserRepository_Expecter) UpdateWithID(user interface{}, tx interface{}) *MockIUserRepository_UpdateWithID_Call {
	return &MockIUserRepository_UpdateWithID_Call{Call: _e.mock.On("UpdateWithID", user, tx)}
}

func (_c *MockIUserRepository_UpdateWithID_Call) Run(run func(user *models.UserModel, tx *sqlx.Tx)) *MockIUserRepository_UpdateWithID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.UserModel
		if args[0] != nil {
			arg0 = args[0].(*models.UserModel)
		}
		var arg1 *sqlx.Tx
		if args[1] != nil {
			arg1 = args[1].(*sqlx.Tx)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_UpdateWithID_Call) Return(err error) *MockIUserRepository_UpdateWithID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_UpdateWithID_Call) RunAndReturn(run func(user *models.UserModel, tx *sqlx.Tx) error) *MockIUserRepository_UpdateWithID_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) Verify(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockIUserRepository_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - id int64
func (_e *MockIUserRepository_Expecter) Verify(id interface{}) *MockIUserRepository_Verify_Call {
	return &MockIUserRepository_Verify_Call{Call: _e.mock.On("Verify", id)}
}

func (_c *MockIUserRepository_Verify_Call) Run(run func(id int64)) *MockIUserRepository_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserRepository_Verify_Call) Return(err error) *MockIUserRepository_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_Verify_Call) RunAndReturn(run func(id int64) error) *MockIUserRepository_Verify_Call {
	_c.Call.Return(run)
	return _c
}
