// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIPDFService creates a new instance of MockIPDFService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPDFService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPDFService {
	mock := &MockIPDFService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPDFService is an autogenerated mock type for the IPDFService type
type MockIPDFService struct {
	mock.Mock
}

type MockIPDFService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPDFService) EXPECT() *MockIPDFService_Expecter {
	return &MockIPDFService_Expecter{mock: &_m.Mock}
}

// GeneratePDFFromHTML provides a mock function for the type MockIPDFService
func (_mock *MockIPDFService) GeneratePDFFromHTML(ctx context.Context, html string) ([]byte, error) {
	ret := _mock.Called(ctx, html)

	if len(ret) == 0 {
		panic("no return value specified for GeneratePDFFromHTML")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, html)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, html)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, html)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPDFService_GeneratePDFFromHTML_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GeneratePDFFromHTML'
type MockIPDFService_GeneratePDFFromHTML_Call struct {
	*mock.Call
}

// GeneratePDFFromHTML is a helper method to define mock.On call
//   - ctx context.Context
//   - html string
func (_e *MockIPDFService_Expecter) GeneratePDFFromHTML(ctx interface{}, html interface{}) *MockIPDFService_GeneratePDFFromHTML_Call {
	return &MockIPDFService_GeneratePDFFromHTML_Call{Call: _e.mock.On("GeneratePDFFromHTML", ctx, html)}
}

func (_c *MockIPDFService_GeneratePDFFromHTML_Call) Run(run func(ctx context.Context, html string)) *MockIPDFService_GeneratePDFFromHTML_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPDFService_GeneratePDFFromHTML_Call) Return(bytes []byte, err error) *MockIPDFService_GeneratePDFFromHTML_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockIPDFService_GeneratePDFFromHTML_Call) RunAndReturn(run func(ctx context.Context, html string) ([]byte, error)) *MockIPDFService_GeneratePDFFromHTML_Call {
	_c.Call.Return(run)
	return _c
}
