// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"sea-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIFileRepository creates a new instance of MockIFileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIFileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIFileRepository {
	mock := &MockIFileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIFileRepository is an autogenerated mock type for the IFileRepository type
type MockIFileRepository struct {
	mock.Mock
}

type MockIFileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIFileRepository) EXPECT() *MockIFileRepository_Expecter {
	return &MockIFileRepository_Expecter{mock: &_m.Mock}
}

// CreateFile provides a mock function for the type MockIFileRepository
func (_mock *MockIFileRepository) CreateFile(item models.FileModel) (int64, error) {
	ret := _mock.Called(item)

	if len(ret) == 0 {
		panic("no return value specified for CreateFile")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.FileModel) (int64, error)); ok {
		return returnFunc(item)
	}
	if returnFunc, ok := ret.Get(0).(func(models.FileModel) int64); ok {
		r0 = returnFunc(item)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(models.FileModel) error); ok {
		r1 = returnFunc(item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFileRepository_CreateFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFile'
type MockIFileRepository_CreateFile_Call struct {
	*mock.Call
}

// CreateFile is a helper method to define mock.On call
//   - item models.FileModel
func (_e *MockIFileRepository_Expecter) CreateFile(item interface{}) *MockIFileRepository_CreateFile_Call {
	return &MockIFileRepository_CreateFile_Call{Call: _e.mock.On("CreateFile", item)}
}

func (_c *MockIFileRepository_CreateFile_Call) Run(run func(item models.FileModel)) *MockIFileRepository_CreateFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.FileModel
		if args[0] != nil {
			arg0 = args[0].(models.FileModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFileRepository_CreateFile_Call) Return(n int64, err error) *MockIFileRepository_CreateFile_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIFileRepository_CreateFile_Call) RunAndReturn(run func(item models.FileModel) (int64, error)) *MockIFileRepository_CreateFile_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFile provides a mock function for the type MockIFileRepository
func (_mock *MockIFileRepository) DeleteFile(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIFileRepository_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type MockIFileRepository_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - id int64
func (_e *MockIFileRepository_Expecter) DeleteFile(id interface{}) *MockIFileRepository_DeleteFile_Call {
	return &MockIFileRepository_DeleteFile_Call{Call: _e.mock.On("DeleteFile", id)}
}

func (_c *MockIFileRepository_DeleteFile_Call) Run(run func(id int64)) *MockIFileRepository_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFileRepository_DeleteFile_Call) Return(err error) *MockIFileRepository_DeleteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIFileRepository_DeleteFile_Call) RunAndReturn(run func(id int64) error) *MockIFileRepository_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllFiles provides a mock function for the type MockIFileRepository
func (_mock *MockIFileRepository) GetAllFiles() ([]models.FileModel, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllFiles")
	}

	var r0 []models.FileModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.FileModel, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.FileModel); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FileModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFileRepository_GetAllFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllFiles'
type MockIFileRepository_GetAllFiles_Call struct {
	*mock.Call
}

// GetAllFiles is a helper method to define mock.On call
func (_e *MockIFileRepository_Expecter) GetAllFiles() *MockIFileRepository_GetAllFiles_Call {
	return &MockIFileRepository_GetAllFiles_Call{Call: _e.mock.On("GetAllFiles")}
}

func (_c *MockIFileRepository_GetAllFiles_Call) Run(run func()) *MockIFileRepository_GetAllFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIFileRepository_GetAllFiles_Call) Return(fileModels []models.FileModel, err error) *MockIFileRepository_GetAllFiles_Call {
	_c.Call.Return(fileModels, err)
	return _c
}

func (_c *MockIFileRepository_GetAllFiles_Call) RunAndReturn(run func() ([]models.FileModel, error)) *MockIFileRepository_GetAllFiles_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileById provides a mock function for the type MockIFileRepository
func (_mock *MockIFileRepository) GetFileById(id int64) (*models.FileModel, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetFileById")
	}

	var r0 *models.FileModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*models.FileModel, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *models.FileModel); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FileModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFileRepository_GetFileById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileById'
type MockIFileRepository_GetFileById_Call struct {
	*mock.Call
}

// GetFileById is a helper method to define mock.On call
//   - id int64
func (_e *MockIFileRepository_Expecter) GetFileById(id interface{}) *MockIFileRepository_GetFileById_Call {
	return &MockIFileRepository_GetFileById_Call{Call: _e.mock.On("GetFileById", id)}
}

func (_c *MockIFileRepository_GetFileById_Call) Run(run func(id int64)) *MockIFileRepository_GetFileById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFileRepository_GetFileById_Call) Return(fileModel *models.FileModel, err error) *MockIFileRepository_GetFileById_Call {
	_c.Call.Return(fileModel, err)
	return _c
}

func (_c *MockIFileRepository_GetFileById_Call) RunAndReturn(run func(id int64) (*models.FileModel, error)) *MockIFileRepository_GetFileById_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileByKey provides a mock function for the type MockIFileRepository
func (_mock *MockIFileRepository) GetFileByKey(key string) (*models.FileModel, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetFileByKey")
	}

	var r0 *models.FileModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.FileModel, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.FileModel); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FileModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFileRepository_GetFileByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileByKey'
type MockIFileRepository_GetFileByKey_Call struct {
	*mock.Call
}

// GetFileByKey is a helper method to define mock.On call
//   - key string
func (_e *MockIFileRepository_Expecter) GetFileByKey(key interface{}) *MockIFileRepository_GetFileByKey_Call {
	return &MockIFileRepository_GetFileByKey_Call{Call: _e.mock.On("GetFileByKey", key)}
}

func (_c *MockIFileRepository_GetFileByKey_Call) Run(run func(key string)) *MockIFileRepository_GetFileByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFileRepository_GetFileByKey_Call) Return(fileModel *models.FileModel, err error) *MockIFileRepository_GetFileByKey_Call {
	_c.Call.Return(fileModel, err)
	return _c
}

func (_c *MockIFileRepository_GetFileByKey_Call) RunAndReturn(run func(key string) (*models.FileModel, error)) *MockIFileRepository_GetFileByKey_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFile provides a mock function for the type MockIFileRepository
func (_mock *MockIFileRepository) UpdateFile(item *models.FileModel) error {
	ret := _mock.Called(item)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.FileModel) error); ok {
		r0 = returnFunc(item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIFileRepository_UpdateFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFile'
type MockIFileRepository_UpdateFile_Call struct {
	*mock.Call
}

// UpdateFile is a helper method to define mock.On call
//   - item *models.FileModel
func (_e *MockIFileRepository_Expecter) UpdateFile(item interface{}) *MockIFileRepository_UpdateFile_Call {
	return &MockIFileRepository_UpdateFile_Call{Call: _e.mock.On("UpdateFile", item)}
}

func (_c *MockIFileRepository_UpdateFile_Call) Run(run func(item *models.FileModel)) *MockIFileRepository_UpdateFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.FileModel
		if args[0] != nil {
			arg0 = args[0].(*models.FileModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFileRepository_UpdateFile_Call) Return(err error) *MockIFileRepository_UpdateFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIFileRepository_UpdateFile_Call) RunAndReturn(run func(item *models.FileModel) error) *MockIFileRepository_UpdateFile_Call {
	_c.Call.Return(run)
	return _c
}
