// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"sea-api/internal/models"

	"github.com/jmoiron/sqlx"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIEventRepository creates a new instance of MockIEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIEventRepository {
	mock := &MockIEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIEventRepository is an autogenerated mock type for the IEventRepository type
type MockIEventRepository struct {
	mock.Mock
}

type MockIEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIEventRepository) EXPECT() *MockIEventRepository_Expecter {
	return &MockIEventRepository_Expecter{mock: &_m.Mock}
}

// CreateComponent provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) CreateComponent(component *models.EventComponentModel) (int64, error) {
	ret := _mock.Called(component)

	if len(ret) == 0 {
		panic("no return value specified for CreateComponent")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.EventComponentModel) (int64, error)); ok {
		return returnFunc(component)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.EventComponentModel) int64); ok {
		r0 = returnFunc(component)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.EventComponentModel) error); ok {
		r1 = returnFunc(component)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEventRepository_CreateComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComponent'
type MockIEventRepository_CreateComponent_Call struct {
	*mock.Call
}

// CreateComponent is a helper method to define mock.On call
//   - component *models.EventComponentModel
func (_e *MockIEventRepository_Expecter) CreateComponent(component interface{}) *MockIEventRepository_CreateComponent_Call {
	return &MockIEventRepository_CreateComponent_Call{Call: _e.mock.On("CreateComponent", component)}
}

func (_c *MockIEventRepository_CreateComponent_Call) Run(run func(component *models.EventComponentModel)) *MockIEventRepository_CreateComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.EventComponentModel
		if args[0] != nil {
			arg0 = args[0].(*models.EventComponentModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_CreateComponent_Call) Return(n int64, err error) *MockIEventRepository_CreateComponent_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIEventRepository_CreateComponent_Call) RunAndReturn(run func(component *models.EventComponentModel) (int64, error)) *MockIEventRepository_CreateComponent_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEvent provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) CreateEvent(event *models.EventModel) (int64, error) {
	ret := _mock.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvent")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.EventModel) (int64, error)); ok {
		return returnFunc(event)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.EventModel) int64); ok {
		r0 = returnFunc(event)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.EventModel) error); ok {
		r1 = returnFunc(event)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEventRepository_CreateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEvent'
type MockIEventRepository_CreateEvent_Call struct {
	*mock.Call
}

// CreateEvent is a helper method to define mock.On call
//   - event *models.EventModel
func (_e *MockIEventRepository_Expecter) CreateEvent(event interface{}) *MockIEventRepository_CreateEvent_Call {
	return &MockIEventRepository_CreateEvent_Call{Call: _e.mock.On("CreateEvent", event)}
}

func (_c *MockIEventRepository_CreateEvent_Call) Run(run func(event *models.EventModel)) *MockIEventRepository_CreateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.EventModel
		if args[0] != nil {
			arg0 = args[0].(*models.EventModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_CreateEvent_Call) Return(n int64, err error) *MockIEventRepository_CreateEvent_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIEventRepository_CreateEvent_Call) RunAndReturn(run func(event *models.EventModel) (int64, error)) *MockIEventRepository_CreateEvent_Call {
	_c.Call.Return(run)
	return _c
}

// CreateParticipant provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) CreateParticipant(participant *models.EventParticipantModel) (int64, error) {
	ret := _mock.Called(participant)

	if len(ret) == 0 {
		panic("no return value specified for CreateParticipant")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.EventParticipantModel) (int64, error)); ok {
		return returnFunc(participant)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.EventParticipantModel) int64); ok {
		r0 = returnFunc(participant)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.EventParticipantModel) error); ok {
		r1 = returnFunc(participant)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEventRepository_CreateParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateParticipant'
type MockIEventRepository_CreateParticipant_Call struct {
	*mock.Call
}

// CreateParticipant is a helper method to define mock.On call
//   - participant *models.EventParticipantModel
func (_e *MockIEventRepository_Expecter) CreateParticipant(participant interface{}) *MockIEventRepository_CreateParticipant_Call {
	return &MockIEventRepository_CreateParticipant_Call{Call: _e.mock.On("CreateParticipant", participant)}
}

func (_c *MockIEventRepository_CreateParticipant_Call) Run(run func(participant *models.EventParticipantModel)) *MockIEventRepository_CreateParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.EventParticipantModel
		if args[0] != nil {
			arg0 = args[0].(*models.EventParticipantModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_CreateParticipant_Call) Return(n int64, err error) *MockIEventRepository_CreateParticipant_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIEventRepository_CreateParticipant_Call) RunAndReturn(run func(participant *models.EventParticipantModel) (int64, error)) *MockIEventRepository_CreateParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// CreateScore provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) CreateScore(score *models.ComponentScoreModel) (int64, error) {
	ret := _mock.Called(score)

	if len(ret) == 0 {
		panic("no return value specified for CreateScore")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.ComponentScoreModel) (int64, error)); ok {
		return returnFunc(score)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.ComponentScoreModel) int64); ok {
		r0 = returnFunc(score)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.ComponentScoreModel) error); ok {
		r1 = returnFunc(score)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEventRepository_CreateScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateScore'
type MockIEventRepository_CreateScore_Call struct {
	*mock.Call
}

// CreateScore is a helper method to define mock.On call
//   - score *models.ComponentScoreModel
func (_e *MockIEventRepository_Expecter) CreateScore(score interface{}) *MockIEventRepository_CreateScore_Call {
	return &MockIEventRepository_CreateScore_Call{Call: _e.mock.On("CreateScore", score)}
}

func (_c *MockIEventRepository_CreateScore_Call) Run(run func(score *models.ComponentScoreModel)) *MockIEventRepository_CreateScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.ComponentScoreModel
		if args[0] != nil {
			arg0 = args[0].(*models.ComponentScoreModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_CreateScore_Call) Return(n int64, err error) *MockIEventRepository_CreateScore_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIEventRepository_CreateScore_Call) RunAndReturn(run func(score *models.ComponentScoreModel) (int64, error)) *MockIEventRepository_CreateScore_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComponent provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) DeleteComponent(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComponent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEventRepository_DeleteComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComponent'
type MockIEventRepository_DeleteComponent_Call struct {
	*mock.Call
}

// DeleteComponent is a helper method to define mock.On call
//   - id int64
func (_e *MockIEventRepository_Expecter) DeleteComponent(id interface{}) *MockIEventRepository_DeleteComponent_Call {
	return &MockIEventRepository_DeleteComponent_Call{Call: _e.mock.On("DeleteComponent", id)}
}

func (_c *MockIEventRepository_DeleteComponent_Call) Run(run func(id int64)) *MockIEventRepository_DeleteComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_DeleteComponent_Call) Return(err error) *MockIEventRepository_DeleteComponent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEventRepository_DeleteComponent_Call) RunAndReturn(run func(id int64) error) *MockIEventRepository_DeleteComponent_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEvent provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) DeleteEvent(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEventRepository_DeleteEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEvent'
type MockIEventRepository_DeleteEvent_Call struct {
	*mock.Call
}

// DeleteEvent is a helper method to define mock.On call
//   - id int64
func (_e *MockIEventRepository_Expecter) DeleteEvent(id interface{}) *MockIEventRepository_DeleteEvent_Call {
	return &MockIEventRepository_DeleteEvent_Call{Call: _e.mock.On("DeleteEvent", id)}
}

func (_c *MockIEventRepository_DeleteEvent_Call) Run(run func(id int64)) *MockIEventRepository_DeleteEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_DeleteEvent_Call) Return(err error) *MockIEventRepository_DeleteEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEventRepository_DeleteEvent_Call) RunAndReturn(run func(id int64) error) *MockIEventRepository_DeleteEvent_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteParticipant provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) DeleteParticipant(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteParticipant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEventRepository_DeleteParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteParticipant'
type MockIEventRepository_DeleteParticipant_Call struct {
	*mock.Call
}

// DeleteParticipant is a helper method to define mock.On call
//   - id int64
func (_e *MockIEventRepository_Expecter) DeleteParticipant(id interface{}) *MockIEventRepository_DeleteParticipant_Call {
	return &MockIEventRepository_DeleteParticipant_Call{Call: _e.mock.On("DeleteParticipant", id)}
}

func (_c *MockIEventRepository_DeleteParticipant_Call) Run(run func(id int64)) *MockIEventRepository_DeleteParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_DeleteParticipant_Call) Return(err error) *MockIEventRepository_DeleteParticipant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEventRepository_DeleteParticipant_Call) RunAndReturn(run func(id int64) error) *MockIEventRepository_DeleteParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteScore provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) DeleteScore(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteScore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEventRepository_DeleteScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteScore'
type MockIEventRepository_DeleteScore_Call struct {
	*mock.Call
}

// DeleteScore is a helper method to define mock.On call
//   - id int64
func (_e *MockIEventRepository_Expecter) DeleteScore(id interface{}) *MockIEventRepository_DeleteScore_Call {
	return &MockIEventRepository_DeleteScore_Call{Call: _e.mock.On("DeleteScore", id)}
}

func (_c *MockIEventRepository_DeleteScore_Call) Run(run func(id int64)) *MockIEventRepository_DeleteScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_DeleteScore_Call) Return(err error) *MockIEventRepository_DeleteScore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEventRepository_DeleteScore_Call) RunAndReturn(run func(id int64) error) *MockIEventRepository_DeleteScore_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllEvents provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) GetAllEvents() ([]models.EventModel, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllEvents")
	}

	var r0 []models.EventModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.EventModel, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.EventModel); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.EventModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEventRepository_GetAllEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllEvents'
type MockIEventRepository_GetAllEvents_Call struct {
	*mock.Call
}

// GetAllEvents is a helper method to define mock.On call
func (_e *MockIEventRepository_Expecter) GetAllEvents() *MockIEventRepository_GetAllEvents_Call {
	return &MockIEventRepository_GetAllEvents_Call{Call: _e.mock.On("GetAllEvents")}
}

func (_c *MockIEventRepository_GetAllEvents_Call) Run(run func()) *MockIEventRepository_GetAllEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIEventRepository_GetAllEvents_Call) Return(eventModels []models.EventModel, err error) *MockIEventRepository_GetAllEvents_Call {
	_c.Call.Return(eventModels, err)
	return _c
}

func (_c *MockIEventRepository_GetAllEvents_Call) RunAndReturn(run func() ([]models.EventModel, error)) *MockIEventRepository_GetAllEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetComponentByID provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) GetComponentByID(id int64) (*models.EventComponentModel, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetComponentByID")
	}

	var r0 *models.EventComponentModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*models.EventComponentModel, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *models.EventComponentModel); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EventComponentModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEventRepository_GetComponentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComponentByID'
type MockIEventRepository_GetComponentByID_Call struct {
	*mock.Call
}

// GetComponentByID is a helper method to define mock.On call
//   - id int64
func (_e *MockIEventRepository_Expecter) GetComponentByID(id interface{}) *MockIEventRepository_GetComponentByID_Call {
	return &MockIEventRepository_GetComponentByID_Call{Call: _e.mock.On("GetComponentByID", id)}
}

func (_c *MockIEventRepository_GetComponentByID_Call) Run(run func(id int64)) *MockIEventRepository_GetComponentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_GetComponentByID_Call) Return(eventComponentModel *models.EventComponentModel, err error) *MockIEventRepository_GetComponentByID_Call {
	_c.Call.Return(eventComponentModel, err)
	return _c
}

func (_c *MockIEventRepository_GetComponentByID_Call) RunAndReturn(run func(id int64) (*models.EventComponentModel, error)) *MockIEventRepository_GetComponentByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetComponentsByEventID provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) GetComponentsByEventID(eventID int64) ([]models.EventComponentModel, error) {
	ret := _mock.Called(eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetComponentsByEventID")
	}

	var r0 []models.EventComponentModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) ([]models.EventComponentModel, error)); ok {
		return returnFunc(eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) []models.EventComponentModel); ok {
		r0 = returnFunc(eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.EventComponentModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEventRepository_GetComponentsByEventID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComponentsByEventID'
type MockIEventRepository_GetComponentsByEventID_Call struct {
	*mock.Call
}

// GetComponentsByEventID is a helper method to define mock.On call
//   - eventID int64
func (_e *MockIEventRepository_Expecter) GetComponentsByEventID(eventID interface{}) *MockIEventRepository_GetComponentsByEventID_Call {
	return &MockIEventRepository_GetComponentsByEventID_Call{Call: _e.mock.On("GetComponentsByEventID", eventID)}
}

func (_c *MockIEventRepository_GetComponentsByEventID_Call) Run(run func(eventID int64)) *MockIEventRepository_GetComponentsByEventID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_GetComponentsByEventID_Call) Return(eventComponentModels []models.EventComponentModel, err error) *MockIEventRepository_GetComponentsByEventID_Call {
	_c.Call.Return(eventComponentModels, err)
	return _c
}

func (_c *MockIEventRepository_GetComponentsByEventID_Call) RunAndReturn(run func(eventID int64) ([]models.EventComponentModel, error)) *MockIEventRepository_GetComponentsByEventID_Call {
	_c.Call.Return(run)
	return _c
}

// GetEligibleParticipantByEventID provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) GetEligibleParticipantByEventID(eventID int64) ([]models.EventParticipantModel, error) {
	ret := _mock.Called(eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetEligibleParticipantByEventID")
	}

	var r0 []models.EventParticipantModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) ([]models.EventParticipantModel, error)); ok {
		return returnFunc(eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) []models.EventParticipantModel); ok {
		r0 = returnFunc(eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.EventParticipantModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEventRepository_GetEligibleParticipantByEventID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEligibleParticipantByEventID'
type MockIEventRepository_GetEligibleParticipantByEventID_Call struct {
	*mock.Call
}

// GetEligibleParticipantByEventID is a helper method to define mock.On call
//   - eventID int64
func (_e *MockIEventRepository_Expecter) GetEligibleParticipantByEventID(eventID interface{}) *MockIEventRepository_GetEligibleParticipantByEventID_Call {
	return &MockIEventRepository_GetEligibleParticipantByEventID_Call{Call: _e.mock.On("GetEligibleParticipantByEventID", eventID)}
}

func (_c *MockIEventRepository_GetEligibleParticipantByEventID_Call) Run(run func(eventID int64)) *MockIEventRepository_GetEligibleParticipantByEventID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_GetEligibleParticipantByEventID_Call) Return(eventParticipantModels []models.EventParticipantModel, err error) *MockIEventRepository_GetEligibleParticipantByEventID_Call {
	_c.Call.Return(eventParticipantModels, err)
	return _c
}

func (_c *MockIEventRepository_GetEligibleParticipantByEventID_Call) RunAndReturn(run func(eventID int64) ([]models.EventParticipantModel, error)) *MockIEventRepository_GetEligibleParticipantByEventID_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventByID provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) GetEventByID(id int64) (*models.EventModel, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetEventByID")
	}

	var r0 *models.EventModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*models.EventModel, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *models.EventModel); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EventModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEventRepository_GetEventByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventByID'
type MockIEventRepository_GetEventByID_Call struct {
	*mock.Call
}

// GetEventByID is a helper method to define mock.On call
//   - id int64
func (_e *MockIEventRepository_Expecter) GetEventByID(id interface{}) *MockIEventRepository_GetEventByID_Call {
	return &MockIEventRepository_GetEventByID_Call{Call: _e.mock.On("GetEventByID", id)}
}

func (_c *MockIEventRepository_GetEventByID_Call) Run(run func(id int64)) *MockIEventRepository_GetEventByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_GetEventByID_Call) Return(eventModel *models.EventModel, err error) *MockIEventRepository_GetEventByID_Call {
	_c.Call.Return(eventModel, err)
	return _c
}

func (_c *MockIEventRepository_GetEventByID_Call) RunAndReturn(run func(id int64) (*models.EventModel, error)) *MockIEventRepository_GetEventByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetParticipantByEventAndUserIDs provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) GetParticipantByEventAndUserIDs(eventID int64, user_id int64) (*models.EventParticipantModel, error) {
	ret := _mock.Called(eventID, user_id)

	if len(ret) == 0 {
		panic("no return value specified for GetParticipantByEventAndUserIDs")
	}

	var r0 *models.EventParticipantModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, int64) (*models.EventParticipantModel, error)); ok {
		return returnFunc(eventID, user_id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, int64) *models.EventParticipantModel); ok {
		r0 = returnFunc(eventID, user_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EventParticipantModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64, int64) error); ok {
		r1 = returnFunc(eventID, user_id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEventRepository_GetParticipantByEventAndUserIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParticipantByEventAndUserIDs'
type MockIEventRepository_GetParticipantByEventAndUserIDs_Call struct {
	*mock.Call
}

// GetParticipantByEventAndUserIDs is a helper method to define mock.On call
//   - eventID int64
//   - user_id int64
func (_e *MockIEventRepository_Expecter) GetParticipantByEventAndUserIDs(eventID interface{}, user_id interface{}) *MockIEventRepository_GetParticipantByEventAndUserIDs_Call {
	return &MockIEventRepository_GetParticipantByEventAndUserIDs_Call{Call: _e.mock.On("GetParticipantByEventAndUserIDs", eventID, user_id)}
}

func (_c *MockIEventRepository_GetParticipantByEventAndUserIDs_Call) Run(run func(eventID int64, user_id int64)) *MockIEventRepository_GetParticipantByEventAndUserIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIEventRepository_GetParticipantByEventAndUserIDs_Call) Return(eventParticipantModel *models.EventParticipantModel, err error) *MockIEventRepository_GetParticipantByEventAndUserIDs_Call {
	_c.Call.Return(eventParticipantModel, err)
	return _c
}

func (_c *MockIEventRepository_GetParticipantByEventAndUserIDs_Call) RunAndReturn(run func(eventID int64, user_id int64) (*models.EventParticipantModel, error)) *MockIEventRepository_GetParticipantByEventAndUserIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetParticipantByEventID provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) GetParticipantByEventID(eventID int64) ([]models.EventParticipantModel, error) {
	ret := _mock.Called(eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetParticipantByEventID")
	}

	var r0 []models.EventParticipantModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) ([]models.EventParticipantModel, error)); ok {
		return returnFunc(eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) []models.EventParticipantModel); ok {
		r0 = returnFunc(eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.EventParticipantModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEventRepository_GetParticipantByEventID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParticipantByEventID'
type MockIEventRepository_GetParticipantByEventID_Call struct {
	*mock.Call
}

// GetParticipantByEventID is a helper method to define mock.On call
//   - eventID int64
func (_e *MockIEventRepository_Expecter) GetParticipantByEventID(eventID interface{}) *MockIEventRepository_GetParticipantByEventID_Call {
	return &MockIEventRepository_GetParticipantByEventID_Call{Call: _e.mock.On("GetParticipantByEventID", eventID)}
}

func (_c *MockIEventRepository_GetParticipantByEventID_Call) Run(run func(eventID int64)) *MockIEventRepository_GetParticipantByEventID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_GetParticipantByEventID_Call) Return(eventParticipantModels []models.EventParticipantModel, err error) *MockIEventRepository_GetParticipantByEventID_Call {
	_c.Call.Return(eventParticipantModels, err)
	return _c
}

func (_c *MockIEventRepository_GetParticipantByEventID_Call) RunAndReturn(run func(eventID int64) ([]models.EventParticipantModel, error)) *MockIEventRepository_GetParticipantByEventID_Call {
	_c.Call.Return(run)
	return _c
}

// GetParticipantByID provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) GetParticipantByID(id int64) (*models.EventParticipantModel, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetParticipantByID")
	}

	var r0 *models.EventParticipantModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*models.EventParticipantModel, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *models.EventParticipantModel); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EventParticipantModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEventRepository_GetParticipantByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParticipantByID'
type MockIEventRepository_GetParticipantByID_Call struct {
	*mock.Call
}

// GetParticipantByID is a helper method to define mock.On call
//   - id int64
func (_e *MockIEventRepository_Expecter) GetParticipantByID(id interface{}) *MockIEventRepository_GetParticipantByID_Call {
	return &MockIEventRepository_GetParticipantByID_Call{Call: _e.mock.On("GetParticipantByID", id)}
}

func (_c *MockIEventRepository_GetParticipantByID_Call) Run(run func(id int64)) *MockIEventRepository_GetParticipantByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_GetParticipantByID_Call) Return(eventParticipantModel *models.EventParticipantModel, err error) *MockIEventRepository_GetParticipantByID_Call {
	_c.Call.Return(eventParticipantModel, err)
	return _c
}

func (_c *MockIEventRepository_GetParticipantByID_Call) RunAndReturn(run func(id int64) (*models.EventParticipantModel, error)) *MockIEventRepository_GetParticipantByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetParticipantByUserAndEventIDs provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) GetParticipantByUserAndEventIDs(user_id int, eventID int64) (*models.EventParticipantModel, error) {
	ret := _mock.Called(user_id, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetParticipantByUserAndEventIDs")
	}

	var r0 *models.EventParticipantModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int64) (*models.EventParticipantModel, error)); ok {
		return returnFunc(user_id, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int64) *models.EventParticipantModel); ok {
		r0 = returnFunc(user_id, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EventParticipantModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int64) error); ok {
		r1 = returnFunc(user_id, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEventRepository_GetParticipantByUserAndEventIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParticipantByUserAndEventIDs'
type MockIEventRepository_GetParticipantByUserAndEventIDs_Call struct {
	*mock.Call
}

// GetParticipantByUserAndEventIDs is a helper method to define mock.On call
//   - user_id int
//   - eventID int64
func (_e *MockIEventRepository_Expecter) GetParticipantByUserAndEventIDs(user_id interface{}, eventID interface{}) *MockIEventRepository_GetParticipantByUserAndEventIDs_Call {
	return &MockIEventRepository_GetParticipantByUserAndEventIDs_Call{Call: _e.mock.On("GetParticipantByUserAndEventIDs", user_id, eventID)}
}

func (_c *MockIEventRepository_GetParticipantByUserAndEventIDs_Call) Run(run func(user_id int, eventID int64)) *MockIEventRepository_GetParticipantByUserAndEventIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIEventRepository_GetParticipantByUserAndEventIDs_Call) Return(eventParticipantModel *models.EventParticipantModel, err error) *MockIEventRepository_GetParticipantByUserAndEventIDs_Call {
	_c.Call.Return(eventParticipantModel, err)
	return _c
}

func (_c *MockIEventRepository_GetParticipantByUserAndEventIDs_Call) RunAndReturn(run func(user_id int, eventID int64) (*models.EventParticipantModel, error)) *MockIEventRepository_GetParticipantByUserAndEventIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetParticipantByUserID provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) GetParticipantByUserID(user_id int) ([]models.EventParticipantModel, error) {
	ret := _mock.Called(user_id)

	if len(ret) == 0 {
		panic("no return value specified for GetParticipantByUserID")
	}

	var r0 []models.EventParticipantModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]models.EventParticipantModel, error)); ok {
		return returnFunc(user_id)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []models.EventParticipantModel); ok {
		r0 = returnFunc(user_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.EventParticipantModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(user_id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEventRepository_GetParticipantByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParticipantByUserID'
type MockIEventRepository_GetParticipantByUserID_Call struct {
	*mock.Call
}

// GetParticipantByUserID is a helper method to define mock.On call
//   - user_id int
func (_e *MockIEventRepository_Expecter) GetParticipantByUserID(user_id interface{}) *MockIEventRepository_GetParticipantByUserID_Call {
	return &MockIEventRepository_GetParticipantByUserID_Call{Call: _e.mock.On("GetParticipantByUserID", user_id)}
}

func (_c *MockIEventRepository_GetParticipantByUserID_Call) Run(run func(user_id int)) *MockIEventRepository_GetParticipantByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_GetParticipantByUserID_Call) Return(eventParticipantModels []models.EventParticipantModel, err error) *MockIEventRepository_GetParticipantByUserID_Call {
	_c.Call.Return(eventParticipantModels, err)
	return _c
}

func (_c *MockIEventRepository_GetParticipantByUserID_Call) RunAndReturn(run func(user_id int) ([]models.EventParticipantModel, error)) *MockIEventRepository_GetParticipantByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetParticipantsByEventAndUserIDs provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) GetParticipantsByEventAndUserIDs(eventID int64, userIDs []int64) ([]models.EventParticipantModel, error) {
	ret := _mock.Called(eventID, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetParticipantsByEventAndUserIDs")
	}

	var r0 []models.EventParticipantModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, []int64) ([]models.EventParticipantModel, error)); ok {
		return returnFunc(eventID, userIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, []int64) []models.EventParticipantModel); ok {
		r0 = returnFunc(eventID, userIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.EventParticipantModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64, []int64) error); ok {
		r1 = returnFunc(eventID, userIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEventRepository_GetParticipantsByEventAndUserIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParticipantsByEventAndUserIDs'
type MockIEventRepository_GetParticipantsByEventAndUserIDs_Call struct {
	*mock.Call
}

// GetParticipantsByEventAndUserIDs is a helper method to define mock.On call
//   - eventID int64
//   - userIDs []int64
func (_e *MockIEventRepository_Expecter) GetParticipantsByEventAndUserIDs(eventID interface{}, userIDs interface{}) *MockIEventRepository_GetParticipantsByEventAndUserIDs_Call {
	return &MockIEventRepository_GetParticipantsByEventAndUserIDs_Call{Call: _e.mock.On("GetParticipantsByEventAndUserIDs", eventID, userIDs)}
}

func (_c *MockIEventRepository_GetParticipantsByEventAndUserIDs_Call) Run(run func(eventID int64, userIDs []int64)) *MockIEventRepository_GetParticipantsByEventAndUserIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 []int64
		if args[1] != nil {
			arg1 = args[1].([]int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIEventRepository_GetParticipantsByEventAndUserIDs_Call) Return(eventParticipantModels []models.EventParticipantModel, err error) *MockIEventRepository_GetParticipantsByEventAndUserIDs_Call {
	_c.Call.Return(eventParticipantModels, err)
	return _c
}

func (_c *MockIEventRepository_GetParticipantsByEventAndUserIDs_Call) RunAndReturn(run func(eventID int64, userIDs []int64) ([]models.EventParticipantModel, error)) *MockIEventRepository_GetParticipantsByEventAndUserIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetScoreByID provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) GetScoreByID(id int64) (*models.ComponentScoreModel, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetScoreByID")
	}

	var r0 *models.ComponentScoreModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*models.ComponentScoreModel, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *models.ComponentScoreModel); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ComponentScoreModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEventRepository_GetScoreByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScoreByID'
type MockIEventRepository_GetScoreByID_Call struct {
	*mock.Call
}

// GetScoreByID is a helper method to define mock.On call
//   - id int64
func (_e *MockIEventRepository_Expecter) GetScoreByID(id interface{}) *MockIEventRepository_GetScoreByID_Call {
	return &MockIEventRepository_GetScoreByID_Call{Call: _e.mock.On("GetScoreByID", id)}
}

func (_c *MockIEventRepository_GetScoreByID_Call) Run(run func(id int64)) *MockIEventRepository_GetScoreByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_GetScoreByID_Call) Return(componentScoreModel *models.ComponentScoreModel, err error) *MockIEventRepository_GetScoreByID_Call {
	_c.Call.Return(componentScoreModel, err)
	return _c
}

func (_c *MockIEventRepository_GetScoreByID_Call) RunAndReturn(run func(id int64) (*models.ComponentScoreModel, error)) *MockIEventRepository_GetScoreByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetScoresByParticipantID provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) GetScoresByParticipantID(participantID int64) ([]models.ComponentScoreModel, error) {
	ret := _mock.Called(participantID)

	if len(ret) == 0 {
		panic("no return value specified for GetScoresByParticipantID")
	}

	var r0 []models.ComponentScoreModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) ([]models.ComponentScoreModel, error)); ok {
		return returnFunc(participantID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) []models.ComponentScoreModel); ok {
		r0 = returnFunc(participantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ComponentScoreModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(participantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEventRepository_GetScoresByParticipantID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScoresByParticipantID'
type MockIEventRepository_GetScoresByParticipantID_Call struct {
	*mock.Call
}

// GetScoresByParticipantID is a helper method to define mock.On call
//   - participantID int64
func (_e *MockIEventRepository_Expecter) GetScoresByParticipantID(participantID interface{}) *MockIEventRepository_GetScoresByParticipantID_Call {
	return &MockIEventRepository_GetScoresByParticipantID_Call{Call: _e.mock.On("GetScoresByParticipantID", participantID)}
}

func (_c *MockIEventRepository_GetScoresByParticipantID_Call) Run(run func(participantID int64)) *MockIEventRepository_GetScoresByParticipantID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_GetScoresByParticipantID_Call) Return(componentScoreModels []models.ComponentScoreModel, err error) *MockIEventRepository_GetScoresByParticipantID_Call {
	_c.Call.Return(componentScoreModels, err)
	return _c
}

func (_c *MockIEventRepository_GetScoresByParticipantID_Call) RunAndReturn(run func(participantID int64) ([]models.ComponentScoreModel, error)) *MockIEventRepository_GetScoresByParticipantID_Call {
	_c.Call.Return(run)
	return _c
}

// GetScoresByParticipantIDs provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) GetScoresByParticipantIDs(participantIDs []int64) ([]models.ComponentScoreModel, error) {
	ret := _mock.Called(participantIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetScoresByParticipantIDs")
	}

	var r0 []models.ComponentScoreModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]int64) ([]models.ComponentScoreModel, error)); ok {
		return returnFunc(participantIDs)
	}
	if returnFunc, ok := ret.Get(0).(func([]int64) []models.ComponentScoreModel); ok {
		r0 = returnFunc(participantIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ComponentScoreModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]int64) error); ok {
		r1 = returnFunc(participantIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEventRepository_GetScoresByParticipantIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScoresByParticipantIDs'
type MockIEventRepository_GetScoresByParticipantIDs_Call struct {
	*mock.Call
}

// GetScoresByParticipantIDs is a helper method to define mock.On call
//   - participantIDs []int64
func (_e *MockIEventRepository_Expecter) GetScoresByParticipantIDs(participantIDs interface{}) *MockIEventRepository_GetScoresByParticipantIDs_Call {
	return &MockIEventRepository_GetScoresByParticipantIDs_Call{Call: _e.mock.On("GetScoresByParticipantIDs", participantIDs)}
}

func (_c *MockIEventRepository_GetScoresByParticipantIDs_Call) Run(run func(participantIDs []int64)) *MockIEventRepository_GetScoresByParticipantIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []int64
		if args[0] != nil {
			arg0 = args[0].([]int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_GetScoresByParticipantIDs_Call) Return(componentScoreModels []models.ComponentScoreModel, err error) *MockIEventRepository_GetScoresByParticipantIDs_Call {
	_c.Call.Return(componentScoreModels, err)
	return _c
}

func (_c *MockIEventRepository_GetScoresByParticipantIDs_Call) RunAndReturn(run func(participantIDs []int64) ([]models.ComponentScoreModel, error)) *MockIEventRepository_GetScoresByParticipantIDs_Call {
	_c.Call.Return(run)
	return _c
}

// MassCreateComponent provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) MassCreateComponent(components []models.EventComponentModel, tx *sqlx.Tx) error {
	ret := _mock.Called(components, tx)

	if len(ret) == 0 {
		panic("no return value specified for MassCreateComponent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]models.EventComponentModel, *sqlx.Tx) error); ok {
		r0 = returnFunc(components, tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEventRepository_MassCreateComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MassCreateComponent'
type MockIEventRepository_MassCreateComponent_Call struct {
	*mock.Call
}

// MassCreateComponent is a helper method to define mock.On call
//   - components []models.EventComponentModel
//   - tx *sqlx.Tx
func (_e *MockIEventRepository_Expecter) MassCreateComponent(components interface{}, tx interface{}) *MockIEventRepository_MassCreateComponent_Call {
	return &MockIEventRepository_MassCreateComponent_Call{Call: _e.mock.On("MassCreateComponent", components, tx)}
}

func (_c *MockIEventRepository_MassCreateComponent_Call) Run(run func(components []models.EventComponentModel, tx *sqlx.Tx)) *MockIEventRepository_MassCreateComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []models.EventComponentModel
		if args[0] != nil {
			arg0 = args[0].([]models.EventComponentModel)
		}
		var arg1 *sqlx.Tx
		if args[1] != nil {
			arg1 = args[1].(*sqlx.Tx)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIEventRepository_MassCreateComponent_Call) Return(err error) *MockIEventRepository_MassCreateComponent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEventRepository_MassCreateComponent_Call) RunAndReturn(run func(components []models.EventComponentModel, tx *sqlx.Tx) error) *MockIEventRepository_MassCreateComponent_Call {
	_c.Call.Return(run)
	return _c
}

// MassCreateParticipant provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) MassCreateParticipant(participants []models.EventParticipantModel, tx *sqlx.Tx) error {
	ret := _mock.Called(participants, tx)

	if len(ret) == 0 {
		panic("no return value specified for MassCreateParticipant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]models.EventParticipantModel, *sqlx.Tx) error); ok {
		r0 = returnFunc(participants, tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEventRepository_MassCreateParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MassCreateParticipant'
type MockIEventRepository_MassCreateParticipant_Call struct {
	*mock.Call
}

// MassCreateParticipant is a helper method to define mock.On call
//   - participants []models.EventParticipantModel
//   - tx *sqlx.Tx
func (_e *MockIEventRepository_Expecter) MassCreateParticipant(participants interface{}, tx interface{}) *MockIEventRepository_MassCreateParticipant_Call {
	return &MockIEventRepository_MassCreateParticipant_Call{Call: _e.mock.On("MassCreateParticipant", participants, tx)}
}

func (_c *MockIEventRepository_MassCreateParticipant_Call) Run(run func(participants []models.EventParticipantModel, tx *sqlx.Tx)) *MockIEventRepository_MassCreateParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []models.EventParticipantModel
		if args[0] != nil {
			arg0 = args[0].([]models.EventParticipantModel)
		}
		var arg1 *sqlx.Tx
		if args[1] != nil {
			arg1 = args[1].(*sqlx.Tx)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIEventRepository_MassCreateParticipant_Call) Return(err error) *MockIEventRepository_MassCreateParticipant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEventRepository_MassCreateParticipant_Call) RunAndReturn(run func(participants []models.EventParticipantModel, tx *sqlx.Tx) error) *MockIEventRepository_MassCreateParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// MassCreateScore provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) MassCreateScore(scores []models.ComponentScoreModel, tx *sqlx.Tx) error {
	ret := _mock.Called(scores, tx)

	if len(ret) == 0 {
		panic("no return value specified for MassCreateScore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]models.ComponentScoreModel, *sqlx.Tx) error); ok {
		r0 = returnFunc(scores, tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEventRepository_MassCreateScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MassCreateScore'
type MockIEventRepository_MassCreateScore_Call struct {
	*mock.Call
}

// MassCreateScore is a helper method to define mock.On call
//   - scores []models.ComponentScoreModel
//   - tx *sqlx.Tx
func (_e *MockIEventRepository_Expecter) MassCreateScore(scores interface{}, tx interface{}) *MockIEventRepository_MassCreateScore_Call {
	return &MockIEventRepository_MassCreateScore_Call{Call: _e.mock.On("MassCreateScore", scores, tx)}
}

func (_c *MockIEventRepository_MassCreateScore_Call) Run(run func(scores []models.ComponentScoreModel, tx *sqlx.Tx)) *MockIEventRepository_MassCreateScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []models.ComponentScoreModel
		if args[0] != nil {
			arg0 = args[0].([]models.ComponentScoreModel)
		}
		var arg1 *sqlx.Tx
		if args[1] != nil {
			arg1 = args[1].(*sqlx.Tx)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIEventRepository_MassCreateScore_Call) Return(err error) *MockIEventRepository_MassCreateScore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEventRepository_MassCreateScore_Call) RunAndReturn(run func(scores []models.ComponentScoreModel, tx *sqlx.Tx) error) *MockIEventRepository_MassCreateScore_Call {
	_c.Call.Return(run)
	return _c
}

// MassDeleteComponent provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) MassDeleteComponent(ids []int64) error {
	ret := _mock.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for MassDeleteComponent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]int64) error); ok {
		r0 = returnFunc(ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEventRepository_MassDeleteComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MassDeleteComponent'
type MockIEventRepository_MassDeleteComponent_Call struct {
	*mock.Call
}

// MassDeleteComponent is a helper method to define mock.On call
//   - ids []int64
func (_e *MockIEventRepository_Expecter) MassDeleteComponent(ids interface{}) *MockIEventRepository_MassDeleteComponent_Call {
	return &MockIEventRepository_MassDeleteComponent_Call{Call: _e.mock.On("MassDeleteComponent", ids)}
}

func (_c *MockIEventRepository_MassDeleteComponent_Call) Run(run func(ids []int64)) *MockIEventRepository_MassDeleteComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []int64
		if args[0] != nil {
			arg0 = args[0].([]int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_MassDeleteComponent_Call) Return(err error) *MockIEventRepository_MassDeleteComponent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEventRepository_MassDeleteComponent_Call) RunAndReturn(run func(ids []int64) error) *MockIEventRepository_MassDeleteComponent_Call {
	_c.Call.Return(run)
	return _c
}

// MassDeleteParticipant provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) MassDeleteParticipant(ids []int64) error {
	ret := _mock.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for MassDeleteParticipant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]int64) error); ok {
		r0 = returnFunc(ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEventRepository_MassDeleteParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MassDeleteParticipant'
type MockIEventRepository_MassDeleteParticipant_Call struct {
	*mock.Call
}

// MassDeleteParticipant is a helper method to define mock.On call
//   - ids []int64
func (_e *MockIEventRepository_Expecter) MassDeleteParticipant(ids interface{}) *MockIEventRepository_MassDeleteParticipant_Call {
	return &MockIEventRepository_MassDeleteParticipant_Call{Call: _e.mock.On("MassDeleteParticipant", ids)}
}

func (_c *MockIEventRepository_MassDeleteParticipant_Call) Run(run func(ids []int64)) *MockIEventRepository_MassDeleteParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []int64
		if args[0] != nil {
			arg0 = args[0].([]int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_MassDeleteParticipant_Call) Return(err error) *MockIEventRepository_MassDeleteParticipant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEventRepository_MassDeleteParticipant_Call) RunAndReturn(run func(ids []int64) error) *MockIEventRepository_MassDeleteParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// MassDeleteScore provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) MassDeleteScore(ids []int64) error {
	ret := _mock.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for MassDeleteScore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]int64) error); ok {
		r0 = returnFunc(ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEventRepository_MassDeleteScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MassDeleteScore'
type MockIEventRepository_MassDeleteScore_Call struct {
	*mock.Call
}

// MassDeleteScore is a helper method to define mock.On call
//   - ids []int64
func (_e *MockIEventRepository_Expecter) MassDeleteScore(ids interface{}) *MockIEventRepository_MassDeleteScore_Call {
	return &MockIEventRepository_MassDeleteScore_Call{Call: _e.mock.On("MassDeleteScore", ids)}
}

func (_c *MockIEventRepository_MassDeleteScore_Call) Run(run func(ids []int64)) *MockIEventRepository_MassDeleteScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []int64
		if args[0] != nil {
			arg0 = args[0].([]int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_MassDeleteScore_Call) Return(err error) *MockIEventRepository_MassDeleteScore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEventRepository_MassDeleteScore_Call) RunAndReturn(run func(ids []int64) error) *MockIEventRepository_MassDeleteScore_Call {
	_c.Call.Return(run)
	return _c
}

// MassUpdateComponent provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) MassUpdateComponent(components []models.EventComponentModel) error {
	ret := _mock.Called(components)

	if len(ret) == 0 {
		panic("no return value specified for MassUpdateComponent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]models.EventComponentModel) error); ok {
		r0 = returnFunc(components)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEventRepository_MassUpdateComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MassUpdateComponent'
type MockIEventRepository_MassUpdateComponent_Call struct {
	*mock.Call
}

// MassUpdateComponent is a helper method to define mock.On call
//   - components []models.EventComponentModel
func (_e *MockIEventRepository_Expecter) MassUpdateComponent(components interface{}) *MockIEventRepository_MassUpdateComponent_Call {
	return &MockIEventRepository_MassUpdateComponent_Call{Call: _e.mock.On("MassUpdateComponent", components)}
}

func (_c *MockIEventRepository_MassUpdateComponent_Call) Run(run func(components []models.EventComponentModel)) *MockIEventRepository_MassUpdateComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []models.EventComponentModel
		if args[0] != nil {
			arg0 = args[0].([]models.EventComponentModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_MassUpdateComponent_Call) Return(err error) *MockIEventRepository_MassUpdateComponent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEventRepository_MassUpdateComponent_Call) RunAndReturn(run func(components []models.EventComponentModel) error) *MockIEventRepository_MassUpdateComponent_Call {
	_c.Call.Return(run)
	return _c
}

// MassUpdateParticipant provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) MassUpdateParticipant(participants []models.EventParticipantModel) error {
	ret := _mock.Called(participants)

	if len(ret) == 0 {
		panic("no return value specified for MassUpdateParticipant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]models.EventParticipantModel) error); ok {
		r0 = returnFunc(participants)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEventRepository_MassUpdateParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MassUpdateParticipant'
type MockIEventRepository_MassUpdateParticipant_Call struct {
	*mock.Call
}

// MassUpdateParticipant is a helper method to define mock.On call
//   - participants []models.EventParticipantModel
func (_e *MockIEventRepository_Expecter) MassUpdateParticipant(participants interface{}) *MockIEventRepository_MassUpdateParticipant_Call {
	return &MockIEventRepository_MassUpdateParticipant_Call{Call: _e.mock.On("MassUpdateParticipant", participants)}
}

func (_c *MockIEventRepository_MassUpdateParticipant_Call) Run(run func(participants []models.EventParticipantModel)) *MockIEventRepository_MassUpdateParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []models.EventParticipantModel
		if args[0] != nil {
			arg0 = args[0].([]models.EventParticipantModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_MassUpdateParticipant_Call) Return(err error) *MockIEventRepository_MassUpdateParticipant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEventRepository_MassUpdateParticipant_Call) RunAndReturn(run func(participants []models.EventParticipantModel) error) *MockIEventRepository_MassUpdateParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// MassUpdateScore provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) MassUpdateScore(scores []models.ComponentScoreModel) error {
	ret := _mock.Called(scores)

	if len(ret) == 0 {
		panic("no return value specified for MassUpdateScore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]models.ComponentScoreModel) error); ok {
		r0 = returnFunc(scores)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEventRepository_MassUpdateScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MassUpdateScore'
type MockIEventRepository_MassUpdateScore_Call struct {
	*mock.Call
}

// MassUpdateScore is a helper method to define mock.On call
//   - scores []models.ComponentScoreModel
func (_e *MockIEventRepository_Expecter) MassUpdateScore(scores interface{}) *MockIEventRepository_MassUpdateScore_Call {
	return &MockIEventRepository_MassUpdateScore_Call{Call: _e.mock.On("MassUpdateScore", scores)}
}

func (_c *MockIEventRepository_MassUpdateScore_Call) Run(run func(scores []models.ComponentScoreModel)) *MockIEventRepository_MassUpdateScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []models.ComponentScoreModel
		if args[0] != nil {
			arg0 = args[0].([]models.ComponentScoreModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_MassUpdateScore_Call) Return(err error) *MockIEventRepository_MassUpdateScore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEventRepository_MassUpdateScore_Call) RunAndReturn(run func(scores []models.ComponentScoreModel) error) *MockIEventRepository_MassUpdateScore_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComponent provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) UpdateComponent(component *models.EventComponentModel) error {
	ret := _mock.Called(component)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComponent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.EventComponentModel) error); ok {
		r0 = returnFunc(component)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEventRepository_UpdateComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComponent'
type MockIEventRepository_UpdateComponent_Call struct {
	*mock.Call
}

// UpdateComponent is a helper method to define mock.On call
//   - component *models.EventComponentModel
func (_e *MockIEventRepository_Expecter) UpdateComponent(component interface{}) *MockIEventRepository_UpdateComponent_Call {
	return &MockIEventRepository_UpdateComponent_Call{Call: _e.mock.On("UpdateComponent", component)}
}

func (_c *MockIEventRepository_UpdateComponent_Call) Run(run func(component *models.EventComponentModel)) *MockIEventRepository_UpdateComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.EventComponentModel
		if args[0] != nil {
			arg0 = args[0].(*models.EventComponentModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_UpdateComponent_Call) Return(err error) *MockIEventRepository_UpdateComponent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEventRepository_UpdateComponent_Call) RunAndReturn(run func(component *models.EventComponentModel) error) *MockIEventRepository_UpdateComponent_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEvent provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) UpdateEvent(event *models.EventModel) error {
	ret := _mock.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.EventModel) error); ok {
		r0 = returnFunc(event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEventRepository_UpdateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEvent'
type MockIEventRepository_UpdateEvent_Call struct {
	*mock.Call
}

// UpdateEvent is a helper method to define mock.On call
//   - event *models.EventModel
func (_e *MockIEventRepository_Expecter) UpdateEvent(event interface{}) *MockIEventRepository_UpdateEvent_Call {
	return &MockIEventRepository_UpdateEvent_Call{Call: _e.mock.On("UpdateEvent", event)}
}

func (_c *MockIEventRepository_UpdateEvent_Call) Run(run func(event *models.EventModel)) *MockIEventRepository_UpdateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.EventModel
		if args[0] != nil {
			arg0 = args[0].(*models.EventModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_UpdateEvent_Call) Return(err error) *MockIEventRepository_UpdateEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEventRepository_UpdateEvent_Call) RunAndReturn(run func(event *models.EventModel) error) *MockIEventRepository_UpdateEvent_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateParticipant provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) UpdateParticipant(participant *models.EventParticipantModel) error {
	ret := _mock.Called(participant)

	if len(ret) == 0 {
		panic("no return value specified for UpdateParticipant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.EventParticipantModel) error); ok {
		r0 = returnFunc(participant)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEventRepository_UpdateParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateParticipant'
type MockIEventRepository_UpdateParticipant_Call struct {
	*mock.Call
}

// UpdateParticipant is a helper method to define mock.On call
//   - participant *models.EventParticipantModel
func (_e *MockIEventRepository_Expecter) UpdateParticipant(participant interface{}) *MockIEventRepository_UpdateParticipant_Call {
	return &MockIEventRepository_UpdateParticipant_Call{Call: _e.mock.On("UpdateParticipant", participant)}
}

func (_c *MockIEventRepository_UpdateParticipant_Call) Run(run func(participant *models.EventParticipantModel)) *MockIEventRepository_UpdateParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.EventParticipantModel
		if args[0] != nil {
			arg0 = args[0].(*models.EventParticipantModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_UpdateParticipant_Call) Return(err error) *MockIEventRepository_UpdateParticipant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEventRepository_UpdateParticipant_Call) RunAndReturn(run func(participant *models.EventParticipantModel) error) *MockIEventRepository_UpdateParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateScore provides a mock function for the type MockIEventRepository
func (_mock *MockIEventRepository) UpdateScore(score *models.ComponentScoreModel) error {
	ret := _mock.Called(score)

	if len(ret) == 0 {
		panic("no return value specified for UpdateScore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.ComponentScoreModel) error); ok {
		r0 = returnFunc(score)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEventRepository_UpdateScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateScore'
type MockIEventRepository_UpdateScore_Call struct {
	*mock.Call
}

// UpdateScore is a helper method to define mock.On call
//   - score *models.ComponentScoreModel
func (_e *MockIEventRepository_Expecter) UpdateScore(score interface{}) *MockIEventRepository_UpdateScore_Call {
	return &MockIEventRepository_UpdateScore_Call{Call: _e.mock.On("UpdateScore", score)}
}

func (_c *MockIEventRepository_UpdateScore_Call) Run(run func(score *models.ComponentScoreModel)) *MockIEventRepository_UpdateScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.ComponentScoreModel
		if args[0] != nil {
			arg0 = args[0].(*models.ComponentScoreModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEventRepository_UpdateScore_Call) Return(err error) *MockIEventRepository_UpdateScore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEventRepository_UpdateScore_Call) RunAndReturn(run func(score *models.ComponentScoreModel) error) *MockIEventRepository_UpdateScore_Call {
	_c.Call.Return(run)
	return _c
}
