// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIS3StorageService creates a new instance of MockIS3StorageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIS3StorageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIS3StorageService {
	mock := &MockIS3StorageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIS3StorageService is an autogenerated mock type for the IS3StorageService type
type MockIS3StorageService struct {
	mock.Mock
}

type MockIS3StorageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIS3StorageService) EXPECT() *MockIS3StorageService_Expecter {
	return &MockIS3StorageService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockIS3StorageService
func (_mock *MockIS3StorageService) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIS3StorageService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIS3StorageService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIS3StorageService_Expecter) Delete(ctx interface{}, id interface{}) *MockIS3StorageService_Delete_Call {
	return &MockIS3StorageService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockIS3StorageService_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockIS3StorageService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIS3StorageService_Delete_Call) Return(err error) *MockIS3StorageService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIS3StorageService_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockIS3StorageService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Download provides a mock function for the type MockIS3StorageService
func (_mock *MockIS3StorageService) Download(ctx context.Context, id int64) ([]byte, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]byte, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []byte); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIS3StorageService_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockIS3StorageService_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIS3StorageService_Expecter) Download(ctx interface{}, id interface{}) *MockIS3StorageService_Download_Call {
	return &MockIS3StorageService_Download_Call{Call: _e.mock.On("Download", ctx, id)}
}

func (_c *MockIS3StorageService_Download_Call) Run(run func(ctx context.Context, id int64)) *MockIS3StorageService_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIS3StorageService_Download_Call) Return(bytes []byte, err error) *MockIS3StorageService_Download_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockIS3StorageService_Download_Call) RunAndReturn(run func(ctx context.Context, id int64) ([]byte, error)) *MockIS3StorageService_Download_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateDownloadUrlByID provides a mock function for the type MockIS3StorageService
func (_mock *MockIS3StorageService) GenerateDownloadUrlByID(ctx context.Context, id int64) (string, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GenerateDownloadUrlByID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (string, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIS3StorageService_GenerateDownloadUrlByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateDownloadUrlByID'
type MockIS3StorageService_GenerateDownloadUrlByID_Call struct {
	*mock.Call
}

// GenerateDownloadUrlByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIS3StorageService_Expecter) GenerateDownloadUrlByID(ctx interface{}, id interface{}) *MockIS3StorageService_GenerateDownloadUrlByID_Call {
	return &MockIS3StorageService_GenerateDownloadUrlByID_Call{Call: _e.mock.On("GenerateDownloadUrlByID", ctx, id)}
}

func (_c *MockIS3StorageService_GenerateDownloadUrlByID_Call) Run(run func(ctx context.Context, id int64)) *MockIS3StorageService_GenerateDownloadUrlByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIS3StorageService_GenerateDownloadUrlByID_Call) Return(s string, err error) *MockIS3StorageService_GenerateDownloadUrlByID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIS3StorageService_GenerateDownloadUrlByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (string, error)) *MockIS3StorageService_GenerateDownloadUrlByID_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateDownloadUrlByKey provides a mock function for the type MockIS3StorageService
func (_mock *MockIS3StorageService) GenerateDownloadUrlByKey(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GenerateDownloadUrlByKey")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIS3StorageService_GenerateDownloadUrlByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateDownloadUrlByKey'
type MockIS3StorageService_GenerateDownloadUrlByKey_Call struct {
	*mock.Call
}

// GenerateDownloadUrlByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockIS3StorageService_Expecter) GenerateDownloadUrlByKey(ctx interface{}, key interface{}) *MockIS3StorageService_GenerateDownloadUrlByKey_Call {
	return &MockIS3StorageService_GenerateDownloadUrlByKey_Call{Call: _e.mock.On("GenerateDownloadUrlByKey", ctx, key)}
}

func (_c *MockIS3StorageService_GenerateDownloadUrlByKey_Call) Run(run func(ctx context.Context, key string)) *MockIS3StorageService_GenerateDownloadUrlByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIS3StorageService_GenerateDownloadUrlByKey_Call) Return(s string, err error) *MockIS3StorageService_GenerateDownloadUrlByKey_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIS3StorageService_GenerateDownloadUrlByKey_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockIS3StorageService_GenerateDownloadUrlByKey_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockIS3StorageService
func (_mock *MockIS3StorageService) Upload(ctx context.Context, key string, data []byte, contentType string) (int64, error) {
	ret := _mock.Called(ctx, key, data, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, string) (int64, error)); ok {
		return returnFunc(ctx, key, data, contentType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, string) int64); ok {
		r0 = returnFunc(ctx, key, data, contentType)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte, string) error); ok {
		r1 = returnFunc(ctx, key, data, contentType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIS3StorageService_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockIS3StorageService_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - data []byte
//   - contentType string
func (_e *MockIS3StorageService_Expecter) Upload(ctx interface{}, key interface{}, data interface{}, contentType interface{}) *MockIS3StorageService_Upload_Call {
	return &MockIS3StorageService_Upload_Call{Call: _e.mock.On("Upload", ctx, key, data, contentType)}
}

func (_c *MockIS3StorageService_Upload_Call) Run(run func(ctx context.Context, key string, data []byte, contentType string)) *MockIS3StorageService_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIS3StorageService_Upload_Call) Return(n int64, err error) *MockIS3StorageService_Upload_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIS3StorageService_Upload_Call) RunAndReturn(run func(ctx context.Context, key string, data []byte, contentType string) (int64, error)) *MockIS3StorageService_Upload_Call {
	_c.Call.Return(run)
	return _c
}
