// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"sea-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIFormRepository creates a new instance of MockIFormRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIFormRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIFormRepository {
	mock := &MockIFormRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIFormRepository is an autogenerated mock type for the IFormRepository type
type MockIFormRepository struct {
	mock.Mock
}

type MockIFormRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIFormRepository) EXPECT() *MockIFormRepository_Expecter {
	return &MockIFormRepository_Expecter{mock: &_m.Mock}
}

// CreateAnswer provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) CreateAnswer(answer *models.FormAnswerModel) (int64, error) {
	ret := _mock.Called(answer)

	if len(ret) == 0 {
		panic("no return value specified for CreateAnswer")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.FormAnswerModel) (int64, error)); ok {
		return returnFunc(answer)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.FormAnswerModel) int64); ok {
		r0 = returnFunc(answer)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.FormAnswerModel) error); ok {
		r1 = returnFunc(answer)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFormRepository_CreateAnswer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAnswer'
type MockIFormRepository_CreateAnswer_Call struct {
	*mock.Call
}

// CreateAnswer is a helper method to define mock.On call
//   - answer *models.FormAnswerModel
func (_e *MockIFormRepository_Expecter) CreateAnswer(answer interface{}) *MockIFormRepository_CreateAnswer_Call {
	return &MockIFormRepository_CreateAnswer_Call{Call: _e.mock.On("CreateAnswer", answer)}
}

func (_c *MockIFormRepository_CreateAnswer_Call) Run(run func(answer *models.FormAnswerModel)) *MockIFormRepository_CreateAnswer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.FormAnswerModel
		if args[0] != nil {
			arg0 = args[0].(*models.FormAnswerModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_CreateAnswer_Call) Return(n int64, err error) *MockIFormRepository_CreateAnswer_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIFormRepository_CreateAnswer_Call) RunAndReturn(run func(answer *models.FormAnswerModel) (int64, error)) *MockIFormRepository_CreateAnswer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAnswersBatch provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) CreateAnswersBatch(answers []models.FormAnswerModel) error {
	ret := _mock.Called(answers)

	if len(ret) == 0 {
		panic("no return value specified for CreateAnswersBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]models.FormAnswerModel) error); ok {
		r0 = returnFunc(answers)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIFormRepository_CreateAnswersBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAnswersBatch'
type MockIFormRepository_CreateAnswersBatch_Call struct {
	*mock.Call
}

// CreateAnswersBatch is a helper method to define mock.On call
//   - answers []models.FormAnswerModel
func (_e *MockIFormRepository_Expecter) CreateAnswersBatch(answers interface{}) *MockIFormRepository_CreateAnswersBatch_Call {
	return &MockIFormRepository_CreateAnswersBatch_Call{Call: _e.mock.On("CreateAnswersBatch", answers)}
}

func (_c *MockIFormRepository_CreateAnswersBatch_Call) Run(run func(answers []models.FormAnswerModel)) *MockIFormRepository_CreateAnswersBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []models.FormAnswerModel
		if args[0] != nil {
			arg0 = args[0].([]models.FormAnswerModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_CreateAnswersBatch_Call) Return(err error) *MockIFormRepository_CreateAnswersBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIFormRepository_CreateAnswersBatch_Call) RunAndReturn(run func(answers []models.FormAnswerModel) error) *MockIFormRepository_CreateAnswersBatch_Call {
	_c.Call.Return(run)
	return _c
}

// CreateForm provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) CreateForm(form *models.FormModel) (int64, error) {
	ret := _mock.Called(form)

	if len(ret) == 0 {
		panic("no return value specified for CreateForm")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.FormModel) (int64, error)); ok {
		return returnFunc(form)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.FormModel) int64); ok {
		r0 = returnFunc(form)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.FormModel) error); ok {
		r1 = returnFunc(form)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFormRepository_CreateForm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateForm'
type MockIFormRepository_CreateForm_Call struct {
	*mock.Call
}

// CreateForm is a helper method to define mock.On call
//   - form *models.FormModel
func (_e *MockIFormRepository_Expecter) CreateForm(form interface{}) *MockIFormRepository_CreateForm_Call {
	return &MockIFormRepository_CreateForm_Call{Call: _e.mock.On("CreateForm", form)}
}

func (_c *MockIFormRepository_CreateForm_Call) Run(run func(form *models.FormModel)) *MockIFormRepository_CreateForm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.FormModel
		if args[0] != nil {
			arg0 = args[0].(*models.FormModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_CreateForm_Call) Return(n int64, err error) *MockIFormRepository_CreateForm_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIFormRepository_CreateForm_Call) RunAndReturn(run func(form *models.FormModel) (int64, error)) *MockIFormRepository_CreateForm_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePage provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) CreatePage(page *models.FormPageModel) (int64, error) {
	ret := _mock.Called(page)

	if len(ret) == 0 {
		panic("no return value specified for CreatePage")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.FormPageModel) (int64, error)); ok {
		return returnFunc(page)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.FormPageModel) int64); ok {
		r0 = returnFunc(page)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.FormPageModel) error); ok {
		r1 = returnFunc(page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFormRepository_CreatePage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePage'
type MockIFormRepository_CreatePage_Call struct {
	*mock.Call
}

// CreatePage is a helper method to define mock.On call
//   - page *models.FormPageModel
func (_e *MockIFormRepository_Expecter) CreatePage(page interface{}) *MockIFormRepository_CreatePage_Call {
	return &MockIFormRepository_CreatePage_Call{Call: _e.mock.On("CreatePage", page)}
}

func (_c *MockIFormRepository_CreatePage_Call) Run(run func(page *models.FormPageModel)) *MockIFormRepository_CreatePage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.FormPageModel
		if args[0] != nil {
			arg0 = args[0].(*models.FormPageModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_CreatePage_Call) Return(n int64, err error) *MockIFormRepository_CreatePage_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIFormRepository_CreatePage_Call) RunAndReturn(run func(page *models.FormPageModel) (int64, error)) *MockIFormRepository_CreatePage_Call {
	_c.Call.Return(run)
	return _c
}

// CreateQuestion provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) CreateQuestion(question *models.FormQuestionModel) (int64, error) {
	ret := _mock.Called(question)

	if len(ret) == 0 {
		panic("no return value specified for CreateQuestion")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.FormQuestionModel) (int64, error)); ok {
		return returnFunc(question)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.FormQuestionModel) int64); ok {
		r0 = returnFunc(question)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.FormQuestionModel) error); ok {
		r1 = returnFunc(question)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFormRepository_CreateQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateQuestion'
type MockIFormRepository_CreateQuestion_Call struct {
	*mock.Call
}

// CreateQuestion is a helper method to define mock.On call
//   - question *models.FormQuestionModel
func (_e *MockIFormRepository_Expecter) CreateQuestion(question interface{}) *MockIFormRepository_CreateQuestion_Call {
	return &MockIFormRepository_CreateQuestion_Call{Call: _e.mock.On("CreateQuestion", question)}
}

func (_c *MockIFormRepository_CreateQuestion_Call) Run(run func(question *models.FormQuestionModel)) *MockIFormRepository_CreateQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.FormQuestionModel
		if args[0] != nil {
			arg0 = args[0].(*models.FormQuestionModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_CreateQuestion_Call) Return(n int64, err error) *MockIFormRepository_CreateQuestion_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIFormRepository_CreateQuestion_Call) RunAndReturn(run func(question *models.FormQuestionModel) (int64, error)) *MockIFormRepository_CreateQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// CreateQuestionsBatch provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) CreateQuestionsBatch(questions []models.FormQuestionModel) error {
	ret := _mock.Called(questions)

	if len(ret) == 0 {
		panic("no return value specified for CreateQuestionsBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]models.FormQuestionModel) error); ok {
		r0 = returnFunc(questions)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIFormRepository_CreateQuestionsBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateQuestionsBatch'
type MockIFormRepository_CreateQuestionsBatch_Call struct {
	*mock.Call
}

// CreateQuestionsBatch is a helper method to define mock.On call
//   - questions []models.FormQuestionModel
func (_e *MockIFormRepository_Expecter) CreateQuestionsBatch(questions interface{}) *MockIFormRepository_CreateQuestionsBatch_Call {
	return &MockIFormRepository_CreateQuestionsBatch_Call{Call: _e.mock.On("CreateQuestionsBatch", questions)}
}

func (_c *MockIFormRepository_CreateQuestionsBatch_Call) Run(run func(questions []models.FormQuestionModel)) *MockIFormRepository_CreateQuestionsBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []models.FormQuestionModel
		if args[0] != nil {
			arg0 = args[0].([]models.FormQuestionModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_CreateQuestionsBatch_Call) Return(err error) *MockIFormRepository_CreateQuestionsBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIFormRepository_CreateQuestionsBatch_Call) RunAndReturn(run func(questions []models.FormQuestionModel) error) *MockIFormRepository_CreateQuestionsBatch_Call {
	_c.Call.Return(run)
	return _c
}

// CreateResponse provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) CreateResponse(response *models.FormResponseModel) (int64, error) {
	ret := _mock.Called(response)

	if len(ret) == 0 {
		panic("no return value specified for CreateResponse")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.FormResponseModel) (int64, error)); ok {
		return returnFunc(response)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.FormResponseModel) int64); ok {
		r0 = returnFunc(response)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.FormResponseModel) error); ok {
		r1 = returnFunc(response)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFormRepository_CreateResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateResponse'
type MockIFormRepository_CreateResponse_Call struct {
	*mock.Call
}

// CreateResponse is a helper method to define mock.On call
//   - response *models.FormResponseModel
func (_e *MockIFormRepository_Expecter) CreateResponse(response interface{}) *MockIFormRepository_CreateResponse_Call {
	return &MockIFormRepository_CreateResponse_Call{Call: _e.mock.On("CreateResponse", response)}
}

func (_c *MockIFormRepository_CreateResponse_Call) Run(run func(response *models.FormResponseModel)) *MockIFormRepository_CreateResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.FormResponseModel
		if args[0] != nil {
			arg0 = args[0].(*models.FormResponseModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_CreateResponse_Call) Return(n int64, err error) *MockIFormRepository_CreateResponse_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIFormRepository_CreateResponse_Call) RunAndReturn(run func(response *models.FormResponseModel) (int64, error)) *MockIFormRepository_CreateResponse_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAnswer provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) DeleteAnswer(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAnswer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIFormRepository_DeleteAnswer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAnswer'
type MockIFormRepository_DeleteAnswer_Call struct {
	*mock.Call
}

// DeleteAnswer is a helper method to define mock.On call
//   - id int64
func (_e *MockIFormRepository_Expecter) DeleteAnswer(id interface{}) *MockIFormRepository_DeleteAnswer_Call {
	return &MockIFormRepository_DeleteAnswer_Call{Call: _e.mock.On("DeleteAnswer", id)}
}

func (_c *MockIFormRepository_DeleteAnswer_Call) Run(run func(id int64)) *MockIFormRepository_DeleteAnswer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_DeleteAnswer_Call) Return(err error) *MockIFormRepository_DeleteAnswer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIFormRepository_DeleteAnswer_Call) RunAndReturn(run func(id int64) error) *MockIFormRepository_DeleteAnswer_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteForm provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) DeleteForm(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteForm")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIFormRepository_DeleteForm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteForm'
type MockIFormRepository_DeleteForm_Call struct {
	*mock.Call
}

// DeleteForm is a helper method to define mock.On call
//   - id int64
func (_e *MockIFormRepository_Expecter) DeleteForm(id interface{}) *MockIFormRepository_DeleteForm_Call {
	return &MockIFormRepository_DeleteForm_Call{Call: _e.mock.On("DeleteForm", id)}
}

func (_c *MockIFormRepository_DeleteForm_Call) Run(run func(id int64)) *MockIFormRepository_DeleteForm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_DeleteForm_Call) Return(err error) *MockIFormRepository_DeleteForm_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIFormRepository_DeleteForm_Call) RunAndReturn(run func(id int64) error) *MockIFormRepository_DeleteForm_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePage provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) DeletePage(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIFormRepository_DeletePage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePage'
type MockIFormRepository_DeletePage_Call struct {
	*mock.Call
}

// DeletePage is a helper method to define mock.On call
//   - id int64
func (_e *MockIFormRepository_Expecter) DeletePage(id interface{}) *MockIFormRepository_DeletePage_Call {
	return &MockIFormRepository_DeletePage_Call{Call: _e.mock.On("DeletePage", id)}
}

func (_c *MockIFormRepository_DeletePage_Call) Run(run func(id int64)) *MockIFormRepository_DeletePage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_DeletePage_Call) Return(err error) *MockIFormRepository_DeletePage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIFormRepository_DeletePage_Call) RunAndReturn(run func(id int64) error) *MockIFormRepository_DeletePage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteQuestion provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) DeleteQuestion(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQuestion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIFormRepository_DeleteQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQuestion'
type MockIFormRepository_DeleteQuestion_Call struct {
	*mock.Call
}

// DeleteQuestion is a helper method to define mock.On call
//   - id int64
func (_e *MockIFormRepository_Expecter) DeleteQuestion(id interface{}) *MockIFormRepository_DeleteQuestion_Call {
	return &MockIFormRepository_DeleteQuestion_Call{Call: _e.mock.On("DeleteQuestion", id)}
}

func (_c *MockIFormRepository_DeleteQuestion_Call) Run(run func(id int64)) *MockIFormRepository_DeleteQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_DeleteQuestion_Call) Return(err error) *MockIFormRepository_DeleteQuestion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIFormRepository_DeleteQuestion_Call) RunAndReturn(run func(id int64) error) *MockIFormRepository_DeleteQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteResponse provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) DeleteResponse(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteResponse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIFormRepository_DeleteResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteResponse'
type MockIFormRepository_DeleteResponse_Call struct {
	*mock.Call
}

// DeleteResponse is a helper method to define mock.On call
//   - id int64
func (_e *MockIFormRepository_Expecter) DeleteResponse(id interface{}) *MockIFormRepository_DeleteResponse_Call {
	return &MockIFormRepository_DeleteResponse_Call{Call: _e.mock.On("DeleteResponse", id)}
}

func (_c *MockIFormRepository_DeleteResponse_Call) Run(run func(id int64)) *MockIFormRepository_DeleteResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_DeleteResponse_Call) Return(err error) *MockIFormRepository_DeleteResponse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIFormRepository_DeleteResponse_Call) RunAndReturn(run func(id int64) error) *MockIFormRepository_DeleteResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllForms provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) GetAllForms() ([]models.FormModel, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllForms")
	}

	var r0 []models.FormModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.FormModel, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.FormModel); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FormModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFormRepository_GetAllForms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllForms'
type MockIFormRepository_GetAllForms_Call struct {
	*mock.Call
}

// GetAllForms is a helper method to define mock.On call
func (_e *MockIFormRepository_Expecter) GetAllForms() *MockIFormRepository_GetAllForms_Call {
	return &MockIFormRepository_GetAllForms_Call{Call: _e.mock.On("GetAllForms")}
}

func (_c *MockIFormRepository_GetAllForms_Call) Run(run func()) *MockIFormRepository_GetAllForms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIFormRepository_GetAllForms_Call) Return(formModels []models.FormModel, err error) *MockIFormRepository_GetAllForms_Call {
	_c.Call.Return(formModels, err)
	return _c
}

func (_c *MockIFormRepository_GetAllForms_Call) RunAndReturn(run func() ([]models.FormModel, error)) *MockIFormRepository_GetAllForms_Call {
	_c.Call.Return(run)
	return _c
}

// GetAnswersByResponseID provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) GetAnswersByResponseID(responseID int64) ([]models.FormAnswerModel, error) {
	ret := _mock.Called(responseID)

	if len(ret) == 0 {
		panic("no return value specified for GetAnswersByResponseID")
	}

	var r0 []models.FormAnswerModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) ([]models.FormAnswerModel, error)); ok {
		return returnFunc(responseID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) []models.FormAnswerModel); ok {
		r0 = returnFunc(responseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FormAnswerModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(responseID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFormRepository_GetAnswersByResponseID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnswersByResponseID'
type MockIFormRepository_GetAnswersByResponseID_Call struct {
	*mock.Call
}

// GetAnswersByResponseID is a helper method to define mock.On call
//   - responseID int64
func (_e *MockIFormRepository_Expecter) GetAnswersByResponseID(responseID interface{}) *MockIFormRepository_GetAnswersByResponseID_Call {
	return &MockIFormRepository_GetAnswersByResponseID_Call{Call: _e.mock.On("GetAnswersByResponseID", responseID)}
}

func (_c *MockIFormRepository_GetAnswersByResponseID_Call) Run(run func(responseID int64)) *MockIFormRepository_GetAnswersByResponseID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_GetAnswersByResponseID_Call) Return(formAnswerModels []models.FormAnswerModel, err error) *MockIFormRepository_GetAnswersByResponseID_Call {
	_c.Call.Return(formAnswerModels, err)
	return _c
}

func (_c *MockIFormRepository_GetAnswersByResponseID_Call) RunAndReturn(run func(responseID int64) ([]models.FormAnswerModel, error)) *MockIFormRepository_GetAnswersByResponseID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAnswersByResponseIDs provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) GetAnswersByResponseIDs(responseIDs []int64) ([]models.FormAnswerModel, error) {
	ret := _mock.Called(responseIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetAnswersByResponseIDs")
	}

	var r0 []models.FormAnswerModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]int64) ([]models.FormAnswerModel, error)); ok {
		return returnFunc(responseIDs)
	}
	if returnFunc, ok := ret.Get(0).(func([]int64) []models.FormAnswerModel); ok {
		r0 = returnFunc(responseIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FormAnswerModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]int64) error); ok {
		r1 = returnFunc(responseIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFormRepository_GetAnswersByResponseIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnswersByResponseIDs'
type MockIFormRepository_GetAnswersByResponseIDs_Call struct {
	*mock.Call
}

// GetAnswersByResponseIDs is a helper method to define mock.On call
//   - responseIDs []int64
func (_e *MockIFormRepository_Expecter) GetAnswersByResponseIDs(responseIDs interface{}) *MockIFormRepository_GetAnswersByResponseIDs_Call {
	return &MockIFormRepository_GetAnswersByResponseIDs_Call{Call: _e.mock.On("GetAnswersByResponseIDs", responseIDs)}
}

func (_c *MockIFormRepository_GetAnswersByResponseIDs_Call) Run(run func(responseIDs []int64)) *MockIFormRepository_GetAnswersByResponseIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []int64
		if args[0] != nil {
			arg0 = args[0].([]int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_GetAnswersByResponseIDs_Call) Return(formAnswerModels []models.FormAnswerModel, err error) *MockIFormRepository_GetAnswersByResponseIDs_Call {
	_c.Call.Return(formAnswerModels, err)
	return _c
}

func (_c *MockIFormRepository_GetAnswersByResponseIDs_Call) RunAndReturn(run func(responseIDs []int64) ([]models.FormAnswerModel, error)) *MockIFormRepository_GetAnswersByResponseIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetFormAnalysisData provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) GetFormAnalysisData(formID int64) ([]models.FormAnalysisRow, error) {
	ret := _mock.Called(formID)

	if len(ret) == 0 {
		panic("no return value specified for GetFormAnalysisData")
	}

	var r0 []models.FormAnalysisRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) ([]models.FormAnalysisRow, error)); ok {
		return returnFunc(formID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) []models.FormAnalysisRow); ok {
		r0 = returnFunc(formID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FormAnalysisRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(formID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFormRepository_GetFormAnalysisData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFormAnalysisData'
type MockIFormRepository_GetFormAnalysisData_Call struct {
	*mock.Call
}

// GetFormAnalysisData is a helper method to define mock.On call
//   - formID int64
func (_e *MockIFormRepository_Expecter) GetFormAnalysisData(formID interface{}) *MockIFormRepository_GetFormAnalysisData_Call {
	return &MockIFormRepository_GetFormAnalysisData_Call{Call: _e.mock.On("GetFormAnalysisData", formID)}
}

func (_c *MockIFormRepository_GetFormAnalysisData_Call) Run(run func(formID int64)) *MockIFormRepository_GetFormAnalysisData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_GetFormAnalysisData_Call) Return(formAnalysisRows []models.FormAnalysisRow, err error) *MockIFormRepository_GetFormAnalysisData_Call {
	_c.Call.Return(formAnalysisRows, err)
	return _c
}

func (_c *MockIFormRepository_GetFormAnalysisData_Call) RunAndReturn(run func(formID int64) ([]models.FormAnalysisRow, error)) *MockIFormRepository_GetFormAnalysisData_Call {
	_c.Call.Return(run)
	return _c
}

// GetFormByID provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) GetFormByID(id int64) (*models.FormModel, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetFormByID")
	}

	var r0 *models.FormModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*models.FormModel, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *models.FormModel); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FormModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFormRepository_GetFormByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFormByID'
type MockIFormRepository_GetFormByID_Call struct {
	*mock.Call
}

// GetFormByID is a helper method to define mock.On call
//   - id int64
func (_e *MockIFormRepository_Expecter) GetFormByID(id interface{}) *MockIFormRepository_GetFormByID_Call {
	return &MockIFormRepository_GetFormByID_Call{Call: _e.mock.On("GetFormByID", id)}
}

func (_c *MockIFormRepository_GetFormByID_Call) Run(run func(id int64)) *MockIFormRepository_GetFormByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_GetFormByID_Call) Return(formModel *models.FormModel, err error) *MockIFormRepository_GetFormByID_Call {
	_c.Call.Return(formModel, err)
	return _c
}

func (_c *MockIFormRepository_GetFormByID_Call) RunAndReturn(run func(id int64) (*models.FormModel, error)) *MockIFormRepository_GetFormByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFormWithQuestions provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) GetFormWithQuestions(formID int64) ([]models.FormRow, error) {
	ret := _mock.Called(formID)

	if len(ret) == 0 {
		panic("no return value specified for GetFormWithQuestions")
	}

	var r0 []models.FormRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) ([]models.FormRow, error)); ok {
		return returnFunc(formID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) []models.FormRow); ok {
		r0 = returnFunc(formID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FormRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(formID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFormRepository_GetFormWithQuestions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFormWithQuestions'
type MockIFormRepository_GetFormWithQuestions_Call struct {
	*mock.Call
}

// GetFormWithQuestions is a helper method to define mock.On call
//   - formID int64
func (_e *MockIFormRepository_Expecter) GetFormWithQuestions(formID interface{}) *MockIFormRepository_GetFormWithQuestions_Call {
	return &MockIFormRepository_GetFormWithQuestions_Call{Call: _e.mock.On("GetFormWithQuestions", formID)}
}

func (_c *MockIFormRepository_GetFormWithQuestions_Call) Run(run func(formID int64)) *MockIFormRepository_GetFormWithQuestions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_GetFormWithQuestions_Call) Return(formRows []models.FormRow, err error) *MockIFormRepository_GetFormWithQuestions_Call {
	_c.Call.Return(formRows, err)
	return _c
}

func (_c *MockIFormRepository_GetFormWithQuestions_Call) RunAndReturn(run func(formID int64) ([]models.FormRow, error)) *MockIFormRepository_GetFormWithQuestions_Call {
	_c.Call.Return(run)
	return _c
}

// GetNumberOfResponsesByFormID provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) GetNumberOfResponsesByFormID(formID int64) (int, error) {
	ret := _mock.Called(formID)

	if len(ret) == 0 {
		panic("no return value specified for GetNumberOfResponsesByFormID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (int, error)); ok {
		return returnFunc(formID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) int); ok {
		r0 = returnFunc(formID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(formID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFormRepository_GetNumberOfResponsesByFormID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNumberOfResponsesByFormID'
type MockIFormRepository_GetNumberOfResponsesByFormID_Call struct {
	*mock.Call
}

// GetNumberOfResponsesByFormID is a helper method to define mock.On call
//   - formID int64
func (_e *MockIFormRepository_Expecter) GetNumberOfResponsesByFormID(formID interface{}) *MockIFormRepository_GetNumberOfResponsesByFormID_Call {
	return &MockIFormRepository_GetNumberOfResponsesByFormID_Call{Call: _e.mock.On("GetNumberOfResponsesByFormID", formID)}
}

func (_c *MockIFormRepository_GetNumberOfResponsesByFormID_Call) Run(run func(formID int64)) *MockIFormRepository_GetNumberOfResponsesByFormID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_GetNumberOfResponsesByFormID_Call) Return(n int, err error) *MockIFormRepository_GetNumberOfResponsesByFormID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIFormRepository_GetNumberOfResponsesByFormID_Call) RunAndReturn(run func(formID int64) (int, error)) *MockIFormRepository_GetNumberOfResponsesByFormID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPageByFormIdAndPageNumber provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) GetPageByFormIdAndPageNumber(formID int64, pageNumber int) (*models.FormPageModel, error) {
	ret := _mock.Called(formID, pageNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetPageByFormIdAndPageNumber")
	}

	var r0 *models.FormPageModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, int) (*models.FormPageModel, error)); ok {
		return returnFunc(formID, pageNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, int) *models.FormPageModel); ok {
		r0 = returnFunc(formID, pageNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FormPageModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64, int) error); ok {
		r1 = returnFunc(formID, pageNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFormRepository_GetPageByFormIdAndPageNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPageByFormIdAndPageNumber'
type MockIFormRepository_GetPageByFormIdAndPageNumber_Call struct {
	*mock.Call
}

// GetPageByFormIdAndPageNumber is a helper method to define mock.On call
//   - formID int64
//   - pageNumber int
func (_e *MockIFormRepository_Expecter) GetPageByFormIdAndPageNumber(formID interface{}, pageNumber interface{}) *MockIFormRepository_GetPageByFormIdAndPageNumber_Call {
	return &MockIFormRepository_GetPageByFormIdAndPageNumber_Call{Call: _e.mock.On("GetPageByFormIdAndPageNumber", formID, pageNumber)}
}

func (_c *MockIFormRepository_GetPageByFormIdAndPageNumber_Call) Run(run func(formID int64, pageNumber int)) *MockIFormRepository_GetPageByFormIdAndPageNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIFormRepository_GetPageByFormIdAndPageNumber_Call) Return(formPageModel *models.FormPageModel, err error) *MockIFormRepository_GetPageByFormIdAndPageNumber_Call {
	_c.Call.Return(formPageModel, err)
	return _c
}

func (_c *MockIFormRepository_GetPageByFormIdAndPageNumber_Call) RunAndReturn(run func(formID int64, pageNumber int) (*models.FormPageModel, error)) *MockIFormRepository_GetPageByFormIdAndPageNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetPageByID provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) GetPageByID(id int64) (*models.FormPageModel, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetPageByID")
	}

	var r0 *models.FormPageModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*models.FormPageModel, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *models.FormPageModel); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FormPageModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFormRepository_GetPageByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPageByID'
type MockIFormRepository_GetPageByID_Call struct {
	*mock.Call
}

// GetPageByID is a helper method to define mock.On call
//   - id int64
func (_e *MockIFormRepository_Expecter) GetPageByID(id interface{}) *MockIFormRepository_GetPageByID_Call {
	return &MockIFormRepository_GetPageByID_Call{Call: _e.mock.On("GetPageByID", id)}
}

func (_c *MockIFormRepository_GetPageByID_Call) Run(run func(id int64)) *MockIFormRepository_GetPageByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_GetPageByID_Call) Return(formPageModel *models.FormPageModel, err error) *MockIFormRepository_GetPageByID_Call {
	_c.Call.Return(formPageModel, err)
	return _c
}

func (_c *MockIFormRepository_GetPageByID_Call) RunAndReturn(run func(id int64) (*models.FormPageModel, error)) *MockIFormRepository_GetPageByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPagesByFormID provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) GetPagesByFormID(formID int64) ([]models.FormPageModel, error) {
	ret := _mock.Called(formID)

	if len(ret) == 0 {
		panic("no return value specified for GetPagesByFormID")
	}

	var r0 []models.FormPageModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) ([]models.FormPageModel, error)); ok {
		return returnFunc(formID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) []models.FormPageModel); ok {
		r0 = returnFunc(formID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FormPageModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(formID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFormRepository_GetPagesByFormID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPagesByFormID'
type MockIFormRepository_GetPagesByFormID_Call struct {
	*mock.Call
}

// GetPagesByFormID is a helper method to define mock.On call
//   - formID int64
func (_e *MockIFormRepository_Expecter) GetPagesByFormID(formID interface{}) *MockIFormRepository_GetPagesByFormID_Call {
	return &MockIFormRepository_GetPagesByFormID_Call{Call: _e.mock.On("GetPagesByFormID", formID)}
}

func (_c *MockIFormRepository_GetPagesByFormID_Call) Run(run func(formID int64)) *MockIFormRepository_GetPagesByFormID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_GetPagesByFormID_Call) Return(formPageModels []models.FormPageModel, err error) *MockIFormRepository_GetPagesByFormID_Call {
	_c.Call.Return(formPageModels, err)
	return _c
}

func (_c *MockIFormRepository_GetPagesByFormID_Call) RunAndReturn(run func(formID int64) ([]models.FormPageModel, error)) *MockIFormRepository_GetPagesByFormID_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuestionByID provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) GetQuestionByID(id int64) (*models.FormQuestionModel, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetQuestionByID")
	}

	var r0 *models.FormQuestionModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*models.FormQuestionModel, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *models.FormQuestionModel); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FormQuestionModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFormRepository_GetQuestionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuestionByID'
type MockIFormRepository_GetQuestionByID_Call struct {
	*mock.Call
}

// GetQuestionByID is a helper method to define mock.On call
//   - id int64
func (_e *MockIFormRepository_Expecter) GetQuestionByID(id interface{}) *MockIFormRepository_GetQuestionByID_Call {
	return &MockIFormRepository_GetQuestionByID_Call{Call: _e.mock.On("GetQuestionByID", id)}
}

func (_c *MockIFormRepository_GetQuestionByID_Call) Run(run func(id int64)) *MockIFormRepository_GetQuestionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_GetQuestionByID_Call) Return(formQuestionModel *models.FormQuestionModel, err error) *MockIFormRepository_GetQuestionByID_Call {
	_c.Call.Return(formQuestionModel, err)
	return _c
}

func (_c *MockIFormRepository_GetQuestionByID_Call) RunAndReturn(run func(id int64) (*models.FormQuestionModel, error)) *MockIFormRepository_GetQuestionByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuestionsByFormID provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) GetQuestionsByFormID(formID int64) ([]models.FormQuestionModel, error) {
	ret := _mock.Called(formID)

	if len(ret) == 0 {
		panic("no return value specified for GetQuestionsByFormID")
	}

	var r0 []models.FormQuestionModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) ([]models.FormQuestionModel, error)); ok {
		return returnFunc(formID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) []models.FormQuestionModel); ok {
		r0 = returnFunc(formID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FormQuestionModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(formID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFormRepository_GetQuestionsByFormID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuestionsByFormID'
type MockIFormRepository_GetQuestionsByFormID_Call struct {
	*mock.Call
}

// GetQuestionsByFormID is a helper method to define mock.On call
//   - formID int64
func (_e *MockIFormRepository_Expecter) GetQuestionsByFormID(formID interface{}) *MockIFormRepository_GetQuestionsByFormID_Call {
	return &MockIFormRepository_GetQuestionsByFormID_Call{Call: _e.mock.On("GetQuestionsByFormID", formID)}
}

func (_c *MockIFormRepository_GetQuestionsByFormID_Call) Run(run func(formID int64)) *MockIFormRepository_GetQuestionsByFormID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_GetQuestionsByFormID_Call) Return(formQuestionModels []models.FormQuestionModel, err error) *MockIFormRepository_GetQuestionsByFormID_Call {
	_c.Call.Return(formQuestionModels, err)
	return _c
}

func (_c *MockIFormRepository_GetQuestionsByFormID_Call) RunAndReturn(run func(formID int64) ([]models.FormQuestionModel, error)) *MockIFormRepository_GetQuestionsByFormID_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuestionsByPageID provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) GetQuestionsByPageID(pageID int64) ([]models.FormQuestionModel, error) {
	ret := _mock.Called(pageID)

	if len(ret) == 0 {
		panic("no return value specified for GetQuestionsByPageID")
	}

	var r0 []models.FormQuestionModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) ([]models.FormQuestionModel, error)); ok {
		return returnFunc(pageID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) []models.FormQuestionModel); ok {
		r0 = returnFunc(pageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FormQuestionModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(pageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFormRepository_GetQuestionsByPageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuestionsByPageID'
type MockIFormRepository_GetQuestionsByPageID_Call struct {
	*mock.Call
}

// GetQuestionsByPageID is a helper method to define mock.On call
//   - pageID int64
func (_e *MockIFormRepository_Expecter) GetQuestionsByPageID(pageID interface{}) *MockIFormRepository_GetQuestionsByPageID_Call {
	return &MockIFormRepository_GetQuestionsByPageID_Call{Call: _e.mock.On("GetQuestionsByPageID", pageID)}
}

func (_c *MockIFormRepository_GetQuestionsByPageID_Call) Run(run func(pageID int64)) *MockIFormRepository_GetQuestionsByPageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_GetQuestionsByPageID_Call) Return(formQuestionModels []models.FormQuestionModel, err error) *MockIFormRepository_GetQuestionsByPageID_Call {
	_c.Call.Return(formQuestionModels, err)
	return _c
}

func (_c *MockIFormRepository_GetQuestionsByPageID_Call) RunAndReturn(run func(pageID int64) ([]models.FormQuestionModel, error)) *MockIFormRepository_GetQuestionsByPageID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequiredQuestionsByFormID provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) GetRequiredQuestionsByFormID(formID int64) ([]models.FormQuestionModel, error) {
	ret := _mock.Called(formID)

	if len(ret) == 0 {
		panic("no return value specified for GetRequiredQuestionsByFormID")
	}

	var r0 []models.FormQuestionModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) ([]models.FormQuestionModel, error)); ok {
		return returnFunc(formID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) []models.FormQuestionModel); ok {
		r0 = returnFunc(formID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FormQuestionModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(formID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFormRepository_GetRequiredQuestionsByFormID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequiredQuestionsByFormID'
type MockIFormRepository_GetRequiredQuestionsByFormID_Call struct {
	*mock.Call
}

// GetRequiredQuestionsByFormID is a helper method to define mock.On call
//   - formID int64
func (_e *MockIFormRepository_Expecter) GetRequiredQuestionsByFormID(formID interface{}) *MockIFormRepository_GetRequiredQuestionsByFormID_Call {
	return &MockIFormRepository_GetRequiredQuestionsByFormID_Call{Call: _e.mock.On("GetRequiredQuestionsByFormID", formID)}
}

func (_c *MockIFormRepository_GetRequiredQuestionsByFormID_Call) Run(run func(formID int64)) *MockIFormRepository_GetRequiredQuestionsByFormID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_GetRequiredQuestionsByFormID_Call) Return(formQuestionModels []models.FormQuestionModel, err error) *MockIFormRepository_GetRequiredQuestionsByFormID_Call {
	_c.Call.Return(formQuestionModels, err)
	return _c
}

func (_c *MockIFormRepository_GetRequiredQuestionsByFormID_Call) RunAndReturn(run func(formID int64) ([]models.FormQuestionModel, error)) *MockIFormRepository_GetRequiredQuestionsByFormID_Call {
	_c.Call.Return(run)
	return _c
}

// GetResponseByID provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) GetResponseByID(id int64) (*models.FormResponseModel, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetResponseByID")
	}

	var r0 *models.FormResponseModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*models.FormResponseModel, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *models.FormResponseModel); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FormResponseModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFormRepository_GetResponseByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResponseByID'
type MockIFormRepository_GetResponseByID_Call struct {
	*mock.Call
}

// GetResponseByID is a helper method to define mock.On call
//   - id int64
func (_e *MockIFormRepository_Expecter) GetResponseByID(id interface{}) *MockIFormRepository_GetResponseByID_Call {
	return &MockIFormRepository_GetResponseByID_Call{Call: _e.mock.On("GetResponseByID", id)}
}

func (_c *MockIFormRepository_GetResponseByID_Call) Run(run func(id int64)) *MockIFormRepository_GetResponseByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_GetResponseByID_Call) Return(formResponseModel *models.FormResponseModel, err error) *MockIFormRepository_GetResponseByID_Call {
	_c.Call.Return(formResponseModel, err)
	return _c
}

func (_c *MockIFormRepository_GetResponseByID_Call) RunAndReturn(run func(id int64) (*models.FormResponseModel, error)) *MockIFormRepository_GetResponseByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetResponsesByFormID provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) GetResponsesByFormID(formID int64) ([]models.FormResponseModel, error) {
	ret := _mock.Called(formID)

	if len(ret) == 0 {
		panic("no return value specified for GetResponsesByFormID")
	}

	var r0 []models.FormResponseModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) ([]models.FormResponseModel, error)); ok {
		return returnFunc(formID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) []models.FormResponseModel); ok {
		r0 = returnFunc(formID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FormResponseModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(formID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFormRepository_GetResponsesByFormID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResponsesByFormID'
type MockIFormRepository_GetResponsesByFormID_Call struct {
	*mock.Call
}

// GetResponsesByFormID is a helper method to define mock.On call
//   - formID int64
func (_e *MockIFormRepository_Expecter) GetResponsesByFormID(formID interface{}) *MockIFormRepository_GetResponsesByFormID_Call {
	return &MockIFormRepository_GetResponsesByFormID_Call{Call: _e.mock.On("GetResponsesByFormID", formID)}
}

func (_c *MockIFormRepository_GetResponsesByFormID_Call) Run(run func(formID int64)) *MockIFormRepository_GetResponsesByFormID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_GetResponsesByFormID_Call) Return(formResponseModels []models.FormResponseModel, err error) *MockIFormRepository_GetResponsesByFormID_Call {
	_c.Call.Return(formResponseModels, err)
	return _c
}

func (_c *MockIFormRepository_GetResponsesByFormID_Call) RunAndReturn(run func(formID int64) ([]models.FormResponseModel, error)) *MockIFormRepository_GetResponsesByFormID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserResponsesForForm provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) GetUserResponsesForForm(userID int64, formID int64) ([]models.FormResponseModel, error) {
	ret := _mock.Called(userID, formID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserResponsesForForm")
	}

	var r0 []models.FormResponseModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, int64) ([]models.FormResponseModel, error)); ok {
		return returnFunc(userID, formID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, int64) []models.FormResponseModel); ok {
		r0 = returnFunc(userID, formID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FormResponseModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64, int64) error); ok {
		r1 = returnFunc(userID, formID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFormRepository_GetUserResponsesForForm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserResponsesForForm'
type MockIFormRepository_GetUserResponsesForForm_Call struct {
	*mock.Call
}

// GetUserResponsesForForm is a helper method to define mock.On call
//   - userID int64
//   - formID int64
func (_e *MockIFormRepository_Expecter) GetUserResponsesForForm(userID interface{}, formID interface{}) *MockIFormRepository_GetUserResponsesForForm_Call {
	return &MockIFormRepository_GetUserResponsesForForm_Call{Call: _e.mock.On("GetUserResponsesForForm", userID, formID)}
}

func (_c *MockIFormRepository_GetUserResponsesForForm_Call) Run(run func(userID int64, formID int64)) *MockIFormRepository_GetUserResponsesForForm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIFormRepository_GetUserResponsesForForm_Call) Return(formResponseModels []models.FormResponseModel, err error) *MockIFormRepository_GetUserResponsesForForm_Call {
	_c.Call.Return(formResponseModels, err)
	return _c
}

func (_c *MockIFormRepository_GetUserResponsesForForm_Call) RunAndReturn(run func(userID int64, formID int64) ([]models.FormResponseModel, error)) *MockIFormRepository_GetUserResponsesForForm_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAnswer provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) UpdateAnswer(answer *models.FormAnswerModel) error {
	ret := _mock.Called(answer)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAnswer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.FormAnswerModel) error); ok {
		r0 = returnFunc(answer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIFormRepository_UpdateAnswer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAnswer'
type MockIFormRepository_UpdateAnswer_Call struct {
	*mock.Call
}

// UpdateAnswer is a helper method to define mock.On call
//   - answer *models.FormAnswerModel
func (_e *MockIFormRepository_Expecter) UpdateAnswer(answer interface{}) *MockIFormRepository_UpdateAnswer_Call {
	return &MockIFormRepository_UpdateAnswer_Call{Call: _e.mock.On("UpdateAnswer", answer)}
}

func (_c *MockIFormRepository_UpdateAnswer_Call) Run(run func(answer *models.FormAnswerModel)) *MockIFormRepository_UpdateAnswer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.FormAnswerModel
		if args[0] != nil {
			arg0 = args[0].(*models.FormAnswerModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_UpdateAnswer_Call) Return(err error) *MockIFormRepository_UpdateAnswer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIFormRepository_UpdateAnswer_Call) RunAndReturn(run func(answer *models.FormAnswerModel) error) *MockIFormRepository_UpdateAnswer_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateForm provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) UpdateForm(form *models.FormModel) error {
	ret := _mock.Called(form)

	if len(ret) == 0 {
		panic("no return value specified for UpdateForm")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.FormModel) error); ok {
		r0 = returnFunc(form)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIFormRepository_UpdateForm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateForm'
type MockIFormRepository_UpdateForm_Call struct {
	*mock.Call
}

// UpdateForm is a helper method to define mock.On call
//   - form *models.FormModel
func (_e *MockIFormRepository_Expecter) UpdateForm(form interface{}) *MockIFormRepository_UpdateForm_Call {
	return &MockIFormRepository_UpdateForm_Call{Call: _e.mock.On("UpdateForm", form)}
}

func (_c *MockIFormRepository_UpdateForm_Call) Run(run func(form *models.FormModel)) *MockIFormRepository_UpdateForm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.FormModel
		if args[0] != nil {
			arg0 = args[0].(*models.FormModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_UpdateForm_Call) Return(err error) *MockIFormRepository_UpdateForm_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIFormRepository_UpdateForm_Call) RunAndReturn(run func(form *models.FormModel) error) *MockIFormRepository_UpdateForm_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePage provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) UpdatePage(page *models.FormPageModel) error {
	ret := _mock.Called(page)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.FormPageModel) error); ok {
		r0 = returnFunc(page)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIFormRepository_UpdatePage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePage'
type MockIFormRepository_UpdatePage_Call struct {
	*mock.Call
}

// UpdatePage is a helper method to define mock.On call
//   - page *models.FormPageModel
func (_e *MockIFormRepository_Expecter) UpdatePage(page interface{}) *MockIFormRepository_UpdatePage_Call {
	return &MockIFormRepository_UpdatePage_Call{Call: _e.mock.On("UpdatePage", page)}
}

func (_c *MockIFormRepository_UpdatePage_Call) Run(run func(page *models.FormPageModel)) *MockIFormRepository_UpdatePage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.FormPageModel
		if args[0] != nil {
			arg0 = args[0].(*models.FormPageModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_UpdatePage_Call) Return(err error) *MockIFormRepository_UpdatePage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIFormRepository_UpdatePage_Call) RunAndReturn(run func(page *models.FormPageModel) error) *MockIFormRepository_UpdatePage_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateQuestion provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) UpdateQuestion(question *models.FormQuestionModel) error {
	ret := _mock.Called(question)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQuestion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.FormQuestionModel) error); ok {
		r0 = returnFunc(question)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIFormRepository_UpdateQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateQuestion'
type MockIFormRepository_UpdateQuestion_Call struct {
	*mock.Call
}

// UpdateQuestion is a helper method to define mock.On call
//   - question *models.FormQuestionModel
func (_e *MockIFormRepository_Expecter) UpdateQuestion(question interface{}) *MockIFormRepository_UpdateQuestion_Call {
	return &MockIFormRepository_UpdateQuestion_Call{Call: _e.mock.On("UpdateQuestion", question)}
}

func (_c *MockIFormRepository_UpdateQuestion_Call) Run(run func(question *models.FormQuestionModel)) *MockIFormRepository_UpdateQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.FormQuestionModel
		if args[0] != nil {
			arg0 = args[0].(*models.FormQuestionModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_UpdateQuestion_Call) Return(err error) *MockIFormRepository_UpdateQuestion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIFormRepository_UpdateQuestion_Call) RunAndReturn(run func(question *models.FormQuestionModel) error) *MockIFormRepository_UpdateQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateQuestions provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) UpdateQuestions(questions []models.FormQuestionModel) error {
	ret := _mock.Called(questions)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQuestions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]models.FormQuestionModel) error); ok {
		r0 = returnFunc(questions)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIFormRepository_UpdateQuestions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateQuestions'
type MockIFormRepository_UpdateQuestions_Call struct {
	*mock.Call
}

// UpdateQuestions is a helper method to define mock.On call
//   - questions []models.FormQuestionModel
func (_e *MockIFormRepository_Expecter) UpdateQuestions(questions interface{}) *MockIFormRepository_UpdateQuestions_Call {
	return &MockIFormRepository_UpdateQuestions_Call{Call: _e.mock.On("UpdateQuestions", questions)}
}

func (_c *MockIFormRepository_UpdateQuestions_Call) Run(run func(questions []models.FormQuestionModel)) *MockIFormRepository_UpdateQuestions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []models.FormQuestionModel
		if args[0] != nil {
			arg0 = args[0].([]models.FormQuestionModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_UpdateQuestions_Call) Return(err error) *MockIFormRepository_UpdateQuestions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIFormRepository_UpdateQuestions_Call) RunAndReturn(run func(questions []models.FormQuestionModel) error) *MockIFormRepository_UpdateQuestions_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResponseStatus provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) UpdateResponseStatus(id int64, status models.ResponseStatus) error {
	ret := _mock.Called(id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResponseStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, models.ResponseStatus) error); ok {
		r0 = returnFunc(id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIFormRepository_UpdateResponseStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResponseStatus'
type MockIFormRepository_UpdateResponseStatus_Call struct {
	*mock.Call
}

// UpdateResponseStatus is a helper method to define mock.On call
//   - id int64
//   - status models.ResponseStatus
func (_e *MockIFormRepository_Expecter) UpdateResponseStatus(id interface{}, status interface{}) *MockIFormRepository_UpdateResponseStatus_Call {
	return &MockIFormRepository_UpdateResponseStatus_Call{Call: _e.mock.On("UpdateResponseStatus", id, status)}
}

func (_c *MockIFormRepository_UpdateResponseStatus_Call) Run(run func(id int64, status models.ResponseStatus)) *MockIFormRepository_UpdateResponseStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 models.ResponseStatus
		if args[1] != nil {
			arg1 = args[1].(models.ResponseStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIFormRepository_UpdateResponseStatus_Call) Return(err error) *MockIFormRepository_UpdateResponseStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIFormRepository_UpdateResponseStatus_Call) RunAndReturn(run func(id int64, status models.ResponseStatus) error) *MockIFormRepository_UpdateResponseStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertAnswer provides a mock function for the type MockIFormRepository
func (_mock *MockIFormRepository) UpsertAnswer(answer *models.FormAnswerModel) error {
	ret := _mock.Called(answer)

	if len(ret) == 0 {
		panic("no return value specified for UpsertAnswer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.FormAnswerModel) error); ok {
		r0 = returnFunc(answer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIFormRepository_UpsertAnswer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertAnswer'
type MockIFormRepository_UpsertAnswer_Call struct {
	*mock.Call
}

// UpsertAnswer is a helper method to define mock.On call
//   - answer *models.FormAnswerModel
func (_e *MockIFormRepository_Expecter) UpsertAnswer(answer interface{}) *MockIFormRepository_UpsertAnswer_Call {
	return &MockIFormRepository_UpsertAnswer_Call{Call: _e.mock.On("UpsertAnswer", answer)}
}

func (_c *MockIFormRepository_UpsertAnswer_Call) Run(run func(answer *models.FormAnswerModel)) *MockIFormRepository_UpsertAnswer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.FormAnswerModel
		if args[0] != nil {
			arg0 = args[0].(*models.FormAnswerModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFormRepository_UpsertAnswer_Call) Return(err error) *MockIFormRepository_UpsertAnswer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIFormRepository_UpsertAnswer_Call) RunAndReturn(run func(answer *models.FormAnswerModel) error) *MockIFormRepository_UpsertAnswer_Call {
	_c.Call.Return(run)
	return _c
}
