// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"sea-api/internal/models"

	"github.com/jmoiron/sqlx"
	mock "github.com/stretchr/testify/mock"
)

// NewMockISuspensionsRepo creates a new instance of MockISuspensionsRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockISuspensionsRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockISuspensionsRepo {
	mock := &MockISuspensionsRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockISuspensionsRepo is an autogenerated mock type for the ISuspensionsRepo type
type MockISuspensionsRepo struct {
	mock.Mock
}

type MockISuspensionsRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockISuspensionsRepo) EXPECT() *MockISuspensionsRepo_Expecter {
	return &MockISuspensionsRepo_Expecter{mock: &_m.Mock}
}

// CleanExpired provides a mock function for the type MockISuspensionsRepo
func (_mock *MockISuspensionsRepo) CleanExpired() ([]int64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CleanExpired")
	}

	var r0 []int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]int64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []int64); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockISuspensionsRepo_CleanExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanExpired'
type MockISuspensionsRepo_CleanExpired_Call struct {
	*mock.Call
}

// CleanExpired is a helper method to define mock.On call
func (_e *MockISuspensionsRepo_Expecter) CleanExpired() *MockISuspensionsRepo_CleanExpired_Call {
	return &MockISuspensionsRepo_CleanExpired_Call{Call: _e.mock.On("CleanExpired")}
}

func (_c *MockISuspensionsRepo_CleanExpired_Call) Run(run func()) *MockISuspensionsRepo_CleanExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockISuspensionsRepo_CleanExpired_Call) Return(int64s []int64, err error) *MockISuspensionsRepo_CleanExpired_Call {
	_c.Call.Return(int64s, err)
	return _c
}

func (_c *MockISuspensionsRepo_CleanExpired_Call) RunAndReturn(run func() ([]int64, error)) *MockISuspensionsRepo_CleanExpired_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockISuspensionsRepo
func (_mock *MockISuspensionsRepo) Create(suspension *models.SuspensionModel, tx *sqlx.Tx, isHistory bool) (int64, error) {
	ret := _mock.Called(suspension, tx, isHistory)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.SuspensionModel, *sqlx.Tx, bool) (int64, error)); ok {
		return returnFunc(suspension, tx, isHistory)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.SuspensionModel, *sqlx.Tx, bool) int64); ok {
		r0 = returnFunc(suspension, tx, isHistory)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.SuspensionModel, *sqlx.Tx, bool) error); ok {
		r1 = returnFunc(suspension, tx, isHistory)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockISuspensionsRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockISuspensionsRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - suspension *models.SuspensionModel
//   - tx *sqlx.Tx
//   - isHistory bool
func (_e *MockISuspensionsRepo_Expecter) Create(suspension interface{}, tx interface{}, isHistory interface{}) *MockISuspensionsRepo_Create_Call {
	return &MockISuspensionsRepo_Create_Call{Call: _e.mock.On("Create", suspension, tx, isHistory)}
}

func (_c *MockISuspensionsRepo_Create_Call) Run(run func(suspension *models.SuspensionModel, tx *sqlx.Tx, isHistory bool)) *MockISuspensionsRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.SuspensionModel
		if args[0] != nil {
			arg0 = args[0].(*models.SuspensionModel)
		}
		var arg1 *sqlx.Tx
		if args[1] != nil {
			arg1 = args[1].(*sqlx.Tx)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockISuspensionsRepo_Create_Call) Return(n int64, err error) *MockISuspensionsRepo_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockISuspensionsRepo_Create_Call) RunAndReturn(run func(suspension *models.SuspensionModel, tx *sqlx.Tx, isHistory bool) (int64, error)) *MockISuspensionsRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockISuspensionsRepo
func (_mock *MockISuspensionsRepo) Delete(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockISuspensionsRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockISuspensionsRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int64
func (_e *MockISuspensionsRepo_Expecter) Delete(id interface{}) *MockISuspensionsRepo_Delete_Call {
	return &MockISuspensionsRepo_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockISuspensionsRepo_Delete_Call) Run(run func(id int64)) *MockISuspensionsRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockISuspensionsRepo_Delete_Call) Return(err error) *MockISuspensionsRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockISuspensionsRepo_Delete_Call) RunAndReturn(run func(id int64) error) *MockISuspensionsRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type MockISuspensionsRepo
func (_mock *MockISuspensionsRepo) GetByUserID(user_id int64) (*models.SuspensionModel, error) {
	ret := _mock.Called(user_id)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *models.SuspensionModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*models.SuspensionModel, error)); ok {
		return returnFunc(user_id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *models.SuspensionModel); ok {
		r0 = returnFunc(user_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SuspensionModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(user_id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockISuspensionsRepo_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockISuspensionsRepo_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - user_id int64
func (_e *MockISuspensionsRepo_Expecter) GetByUserID(user_id interface{}) *MockISuspensionsRepo_GetByUserID_Call {
	return &MockISuspensionsRepo_GetByUserID_Call{Call: _e.mock.On("GetByUserID", user_id)}
}

func (_c *MockISuspensionsRepo_GetByUserID_Call) Run(run func(user_id int64)) *MockISuspensionsRepo_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockISuspensionsRepo_GetByUserID_Call) Return(suspensionModel *models.SuspensionModel, err error) *MockISuspensionsRepo_GetByUserID_Call {
	_c.Call.Return(suspensionModel, err)
	return _c
}

func (_c *MockISuspensionsRepo_GetByUserID_Call) RunAndReturn(run func(user_id int64) (*models.SuspensionModel, error)) *MockISuspensionsRepo_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}
