ALTER TABLE users MODIFY COLUMN password VARCHAR(255) NOT NULL;
ALTER TABLE users MODIFY COLUMN uni_id VARCHAR(255) NOT NULL;
ALTER TABLE users MODIFY COLUMN username VARCHAR(255) NOT NULL;

ALTER TABLE users MODIFY COLUMN name_ar VARCHAR(255) NOT NULL;
ALTER TABLE users MODIFY COLUMN name_en VARCHAR(255) NOT NULL;
ALTER TABLE users MODIFY COLUMN phone VARCHAR(20) NOT NULL;
ALTER TABLE users MODIFY COLUMN gender VARCHAR(10) NOT NULL;
ALTER TABLE users MODIFY COLUMN department VARCHAR(255) NOT NULL;

ALTER TABLE users MODIFY COLUMN verified tinyint NOT NULL;

DROP TABLE registration_step;