ALTER TABLE users MODIFY COLUMN password VARCHAR(255) NULL;
ALTER TABLE users MODIFY COLUMN uni_id VARCHAR(255) NULL UNIQUE;
ALTER TABLE users MODIFY COLUMN username VARCHAR(255) NULL;

ALTER TABLE users MODIFY COLUMN name_ar VARCHAR(255) NULL;
ALTER TABLE users MODIFY COLUMN name_en VARCHAR(255) NULL;
ALTER TABLE users MODIFY COLUMN phone VARCHAR(20) NULL;
ALTER TABLE users MODIFY COLUMN gender VARCHAR(10) NULL;
ALTER TABLE users MODIFY COLUMN department VARCHAR(255) NULL;

ALTER TABLE users MODIFY COLUMN verified tinyint NOT NULL DEFAULT 0;

CREATE TABLE registration_step (
    reg_code VARCHAR(255) UNIQUE NOT NULL,
    user_id INT NOT NULL,
    step INT NOT NULL,

    FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);