DROP TABLE form_answers;
DROP TABLE form_responses;
DROP TABLE form_questions;
DROP TABLE form_pages;
DROP TABLE forms;
DROP TABLE news_gallery;
DROP TABLE team_members;
DROP TABLE blog_posts;
DROP TABLE gallery_references;
DROP TABLE gallery_assets;
DROP TABLE files;
ALTER TABLE users DROP CONSTRAINT fk_profile_image;
ALTER TABLE users DROP CONSTRAINT unique_profile_image_id;
ALTER TABLE users DROP COLUMN profile_image_id;
ALTER TABLE user_roles DROP CONSTRAINT unique_user_role;