server {
    listen 80;

    # Only allow access to this specific path
    location /public/profiles/ {
        if ($request_uri ~* "/$") {
            return 403;
        }
        proxy_pass http://filer:8888;
    }

    location / {
        return 403;
    }
}