name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: Build
      run: go build -o api cmd/api/main.go

    # - name: Test
    #   run: go test -v ./...

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sea-api
        path: api
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        IMAGE=${{ secrets.DOCKER_USERNAME }}/sea-api-server
        TAG=latest
        COMMIT_SHA=$(git rev-parse --short HEAD)
        docker build -t $IMAGE:$TAG -t $IMAGE:$COMMIT_SHA .
        docker push $IMAGE:$TAG
        docker push $IMAGE:$COMMIT_SHA

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: sea-api
          path: .

      - name: Restart Application on Cloud Machine
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEVELOPMENT_HOST }}
          username: ${{ secrets.DEVELOPMENT_HOST_USERNAME }}
          key: ${{ secrets.DEVELOPMENT_HOST_SSH_PRIVATE_KEY }}
          script: |
            cd /opt/api
            sudo docker compose pull
            sudo docker compose up -d --force-recreate