name: Go CI/CD

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ] # Triggers on semantic version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
    
    - name: Install Swag
      run: go install github.com/swaggo/swag/cmd/swag@latest

    - name: Generate Docs
      run: swag init -g cmd/api/main.go --parseDependency --parseInternal

    - name: Build
      run: go build -o api cmd/api/main.go

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sea-api
        path: api
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        IMAGE=${{ secrets.DOCKER_USERNAME }}/sea-api-server
        COMMIT_SHA=$(git rev-parse --short HEAD)
        
        # Check if run was triggered by a Git tag
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          TAG_NAME=${GITHUB_REF#refs/tags/}
          docker build -t $IMAGE:$TAG_NAME -t $IMAGE:latest -t $IMAGE:$COMMIT_SHA .
          docker push $IMAGE:$TAG_NAME
        else
          docker build -t $IMAGE:latest -t $IMAGE:$COMMIT_SHA .
        fi
        
        docker push $IMAGE:latest
        docker push $IMAGE:$COMMIT_SHA

  deploy-dev:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: sea-api
          path: .

      - name: Restart Application on Development Host
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEVELOPMENT_HOST }}
          username: ${{ secrets.DEVELOPMENT_HOST_USERNAME }}
          key: ${{ secrets.DEVELOPMENT_HOST_SSH_PRIVATE_KEY }}
          script: |
            cd /opt/api
            sudo docker compose pull
            sudo docker compose up -d --force-recreate

  deploy-prod:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: sea-api
          path: .

      - name: Restart Application on Production Host
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_HOST_USERNAME }}
          key: ${{ secrets.PRODUCTION_HOST_SSH_PRIVATE_KEY }}
          script: |
            cd /opt/api
            sudo docker compose pull
            sudo docker compose up -d --force-recreate